### ISSUE TITLE
Chat-Spamming in GM3 inside Eldritch Dimension 

### ISSUE THREAD

**Issue by TheRegulator** [Azanor/thaumcraft-5#11]
While you are in the Eldritch Dimension in Gamemode 3, the message:
Something disrupts your ability to fly
shows the whole time.

http://i.imgur.com/w7dOR30.png

**Comment by Azanor** [comment]
That isn't TC5 is it?

**Comment by TheRegulator** [comment]
yes it is
downloaded it 1,5 hours ago

**Comment by TheRegulator** [comment]
you can see some autocasters and the new crystals in the picture

**Comment by Azanor** [comment]
the lack of starry void blocks confused me, but then I remembered they wont render if you are flying through them.
