### ISSUE TITLE
translations improvement

### ISSUE THREAD

**Issue by Zaltora** [Azanor/thaumcraft-5#110]
I had try to add a page like this : 
tc.research_page.WARP.4=....<text here>
but when i open the book ingame, i didn't see anything.
It is possible to add page into the thaumonomicon ? if not, it is possible to add this feature ?

**Comment by 3TUSK** [comment]
You probably want to use modtweaker.

**Comment by Azanor** [comment]
Sorry, but it is currently not possible.

**Comment by Zaltora** [comment]
well, create mod in java just for that. I will prefer the same mod can add this feature ( i dont know how to do mod too). It is just to get more space to write things in others language.
For now, i remove some <BR>. It is ok. This feature can be great in the future.

**Comment by Azanor** [comment]
I agree which is why I'm not closing this :)

**Comment by Zaltora** [comment]
You are great Azanor :+1:
