### ISSUE TITLE
Server Error: Aura

### ISSUE THREAD

**Issue by ChainedHope** [Azanor/thaumcraft-5#115]
From the server log:
[21:55:14] [Thread-16/WARN] [THAUMCRAFT/]: AURAS TAKING 260 ms LONGER THAN NORMAL

It seems to be causing quite a bit of lag in testing a small server using this mod and a short list of other ones, using Version# 5.0.3. 
Forge Version: 1563

The Server log can be found here: http://pastebin.com/raw.php?i=Wc1t3Nv8

**Comment by sergiolepore** [comment]
Same here

**Comment by Azanor** [comment]
Is the actual message spam causing the lag? I see the log contains the log entries right after it started up which is normal - the server is doing a lot of work at that point and for the first few minutes the aura thread will often fall behind till all the chunks are loaded.

**Comment by ChainedHope** [comment]
Sorry for the long delay.
I left the server running for a half hour and the tps was still low (12tps) and after restarting the server it stayed around the 12tps mark on the server. After uninstalling the mod, tps went back to normal and the server is playable again. Also tried using just Thaumcraft 5.0.3 on the server and no other mods and I was seeing the same tps drop.
