### ISSUE TITLE
Research Note ENTEROUTER not being added to inventory for The Outer Lands Eldritch Research

### ISSUE THREAD

**Issue by Jeyed** [Azanor/thaumcraft-5#118]
Using Thaumcraft 5.0.3 and progressing through research, when we get to "The Outer Lands" research on Eldritch tab, the research note is never added to inventory and this stops progression. Instead, a paper is consumed and it says added to inventory, but no research note is there.

Able to recreate this with the following steps:

Log in with cheats or op yourself
/tc research <name> reset
/tc research <name> OCULUS

Then make sure you have paper and scribing tools in your inventory.
Open Thaumonomicon and go to Eldritch tab
"The Outer Lands" (ENTEROUTER) will be available following "Opening the Eye" (OCULUS) saying click to get a research note.
Click on "The Outer Lands" -> get message that research note was added to inventory
Check inventory -> scribing tools and paper depleted as normal, but no research note in inventory

Work around to continue progression:
/tc research <name> ENTEROUTER

Expected Results:
Research note for The Outer Lands should be in inventory to progress via normal mechanics

**Comment by Azanor** [comment]
You are supposed to get that research automatically when you first enter the outer lands - it is not supposed to be researchable. So yes, it is a bug :)
