### ISSUE TITLE
Jar labels are mostly transparent

### ISSUE THREAD

**Issue by Royal-Jelly** [Azanor/thaumcraft-5#12]
Minimal amount of mods are installed forge used : 11.14.3.1521 and no optifine
![2015-10-30_11 44 09](https://cloud.githubusercontent.com/assets/14046681/10850410/d6c70f28-7efb-11e5-9a17-4144da2c31e4.png)

**Comment by Azanor** [comment]
This is actually a forge bug. A fix is supposedly in the works, but till then not much I can do about it. If you switch to an older forge (like 1521) it should work.

**Comment by Azanor** [comment]
Oops, nevermind. Turns out it was me.
