### ISSUE TITLE
runic shielding causes kick from LAN server

### ISSUE THREAD

**Issue by Pika0** [Azanor/thaumcraft-5#122]
Minecraft 1.8
We both have thaumcraft 5.0.3
Forge 11.14.4.1563  (also still occurs on latest 11.14.4.1577)
We are also using NotEnoughItems

I'm hosting a LAN server for myself and my brother.  Whenever either of us is hit while we have runic shielding equipped, he gets kicked from the server ~30% of the time.  My log doesn't have any errors at that time: http://pastebin.com/8wvyAZFQ
My (almost-complete)l FML-client log: http://pastebin.com/NAhxedy3
His log is much longer:
http://pastebin.com/uLHrKA4X
These logs are from us punching each other a few times until he gets kicked, but it also happens when we get hurt from other sources

**Comment by Azanor** [comment]
I don't actually see any TC related errors in there - just a lot of forge networking errors. Are you both using the same version of forge and your mods?

**Comment by Pika0** [comment]
Double checked just now; we have the same version of everything.
