### ISSUE TITLE
Arcane Pedestal renders two items, mirrored

### ISSUE THREAD

**Issue by Zsashas** [Azanor/thaumcraft-5#125]
Example: https://i.gyazo.com/12d15aa9fe8524ea2fb72c93d5b671a4.mp4

As you can see, the Helm is only supposed to have four horns, not eight. I am unable to find any pattern in what items this happens with, or what other mods cause this.

I have also seen it with swords and such, crossed in an X.

**Comment by DanielAKAKing** [comment]
I've been having this bug aswell.

**Comment by Zaltora** [comment]
This bug is for 1.7.10  version or 1.8 too ?

**Comment by DanielAKAKing** [comment]
1.8

**Comment by Zsashas** [comment]
Both.
