### ISSUE TITLE
[Enhancement] Thaumonomicon links

### ISSUE THREAD

**Issue by Fjolsvin** [Azanor/thaumcraft-5#126]
I'd really appreciate Alchemical brass ingot and Thaumium ingot (and probably even more stuff) to be linked with the recipes in Thaumonomicon, which uses it, i. e. if crafting recipe includes e. g. Alchemical brass plate, I can click the plate picture and see the appropriate recipe. Well, but now I need three Alchemical brass ingots, however I can't click the ingot picture to be linked to Magical metallurgy page and I need to find it manually. Annoying.

**Comment by Azanor** [comment]
Is there a specific recipe this is happening with? I have tried a few and I can click-through to the recipes.
Do you have other mods that add their own versions of brass?

**Comment by Fjolsvin** [comment]
I see. The (just realized) fact is, the both brass and thaumium ingot recipes are on the previous pages within Magical metallurgy chapter. Nevertheless, it still would be awesome to get to the brass/thaumium ingot recipes from the brass/thaumium gear/plate recipes. Even though it seems to be unnecessary now, the modus operandi is as follows: A player finds a device to construct. It has a gear. Link to the gear recipe works, but now the player has no idea in which chapter of Thaumonomicon he/she is, thus it's not that clear the ingot recipe is just few pages back.

Thus, requested links are:
From Brass gear to Alchemical brass ingot
From Brass plate to Alchemical brass ingot
From Thaumium gear to Thaumium ingot
From Thaumium plate to Thaumium ingot

I don't think it's necessary to do the same links from Thaumium tools and armor, as everybody knows the tools and armor recipes, thus he/she will find the Thaumium ingot directly, if needed.
