### ISSUE TITLE
Research dissappears (like it has done many times)

### ISSUE THREAD

**Issue by Hyxaru** [Azanor/thaumcraft-5#127]
I just had my research dissappear for the second time upon loading the world. After my first time, I changed the config so that completed research no longer would get consumed, in case I would have to relearn everything and I like to collect researches.
This time however, I lost all research, even those that are automaticly available. And I cannot gain research notes from them, as they do not exist like the one you get from entering the outerlands.
I'm stuck basicly, and finding out what the commands are is nearly impossible.

**Comment by Reykja** [comment]
I just had the same problem. (I have had it before) The first two of these log files are dated from the session when I noticed the lost research.
The last two are from yesterday, my last session (when I still had my research). There were no crashes or other symptoms to point at in between.

[fml-client-latest.docx](https://github.com/Azanor/thaumcraft-5/files/81056/fml-client-latest.docx)
[latest.docx](https://github.com/Azanor/thaumcraft-5/files/81058/latest.docx)
[fml-client-3.docx](https://github.com/Azanor/thaumcraft-5/files/81057/fml-client-3.docx)
[2016-01-06-2.docx](https://github.com/Azanor/thaumcraft-5/files/81059/2016-01-06-2.docx)
