### ISSUE TITLE
Focus Pouch not working from baubles inventory

### ISSUE THREAD

**Issue by errecepe** [Azanor/thaumcraft-5#129]
I cant attach focis to wands if focus pouch is on baubles inventory, when I join game firts time, until i move the focus pouch to inventory.

Then, after attach one foci to want, I can move back the focus pouch to baubles inventory and it's works fine.

playing on a server, not tested on single player

sorry my poor english

greetings for the mod

@errecepe

**Comment by Fjolsvin** [comment]
Tested on SP, not an issue.

**Comment by Azanor** [comment]
This is actually a baubles bug - it is not properly syncing stuff to the server. I'm going to close this, but I will fix it on the baubles side.
