### ISSUE TITLE
Enhancement: Essentia Combiner

### ISSUE THREAD

**Issue by DanielAKAKing** [Azanor/thaumcraft-5#133]
Dear Azanor,

During my survival I noticed that some Essentia were really hard to get, volantis for example.
I thought: why isn't there a machine in the alchemy page that can help me. We hane an Essentia splitter but no combiner. It could have the exact opposite recipe from the centrifug.

Daniël A.K.A. King

**Comment by Fjolsvin** [comment]
I guess you meant Volatus. Then you must be kidding. Have you ever tried to distillate such common and superfluous thing as... a feather? If only Ordo would be as obtainable as Volatus is...

Anyway, combinig of essentia was an issue even in previous version of Thaumcraft and there is no will nor reason to do that.

Volatus is not scarce at all. Auram is the only one. And it should be. The second one is the previously mentioned Ordo, as there is high consumption of it and poorly accessible resources (smooth sandstone with huge amount of waste aspects, ordo crystals with need of Ordo node and plantable Ordo crystal and a distillation of feathers with huge excess of Aer).

**Comment by Azanor** [comment]
Essentia combining wont be happening - not with the way TC works currently.
