### ISSUE TITLE
Thaumic dioptra material (and few more)

### ISSUE THREAD

**Issue by Fjolsvin** [Azanor/thaumcraft-5#135]
1) Thaumic dioptra, although made from (arcane) stone, behaves as a wooden block, i. e. an axe breaks it faster than a pickaxe. Clearly wrong.

2) Arcane alembic, well, is made from both iron (bucket, brass) and wood, nevertheless the texture of it suggests it's a wooden block. In fact, pickaxe breaks it faster. While it could be intentional, I mention it rather.

3) Auxiliary slurry pump (wood/iron) and Auxiliary venting port (iron) are easily breakable by hand and there is no drop. It may be intentional, although I can't see any meaningful reason for it. Both items are not exactly cheap to make, thus I want to be sure it really is intentional and well considered as well. If so, I strongly recommend to mention the fact in Thaumonomicon.

**Comment by Azanor** [comment]
These are known bugs and will be fixed in the next release. The pump and port will drop if broken with a pick, but their hardness was left at 0 by mistake so they break instantly.
