### ISSUE TITLE
Banners still broken

### ISSUE THREAD

**Issue by mujmajnkraft** [Azanor/thaumcraft-5#136]
Azanor, I've posted a bug with banners in 5.0.2 and you've put there label done for next relase, but it's not fixed in 5.0.3. When I copy a Thaumcraft banner standing in the world to my inventory in creative, it always gives me a crimson banner that looks like white banner when is in my inventory. Even if I hold control and copy it with NBT data, it still gives me a crimson banner. Did you just forget to fix it or is ti a forge problem?

**Comment by Azanor** [comment]
For realzies this time.
