### ISSUE TITLE
not loading

### ISSUE THREAD

**Issue by wmgarden76** [Azanor/thaumcraft-5#137]
I have put thaumcraft 5 into my mods folder with baubles but thaumcraft is not loading. Baubles load up but thaumcaft is not loading. It doesnt crash so i have no crash report the mod just does not load. I have the lastest stable forge and the lastest java.

**Comment by Azanor** [comment]
Which version of forge? The latest forge is for MC 1.8.8, but this mod is only for 1.8

**Comment by wmgarden76** [comment]
I am running mc 1.8 not 1.8.8 and i am running forge 11.14.4.1563 the latest stable version.
