### ISSUE TITLE
Pipeline of tubes with filtering tube is venting

### ISSUE THREAD

**Issue by janinko** [Azanor/thaumcraft-5#139]
When there is a pipeline of tubes connected to a source of **any** (Untyped) suction on one side and a filtering tube on the other side, the tube next to the filtering tube is venting.

Example:
```
suction:  23   22   21   20 
   tube: ==== ==== ==== ====
   type:  Unt  Unt  Unt  Ord
                     Ve   Fi
```
**Ve** - venting tube (Untyped)
**Fi** - filtering tube (Ordo)
The **Ve** tube with suction 21 of Untyped essence is causing tube **Fi** to hav suction 20. Because **Fi** is filtering tube, the suction is of type Ordo. Because **Ve** is connected to tube with suction lower by one and of other type, it is venting.

**Comment by Azanor** [comment]
Hmmm, good point.
