### ISSUE TITLE
thaumcraft crash on start

### ISSUE THREAD

**Issue by Dayyer1** [Azanor/thaumcraft-5#14]
https://www.dropbox.com/s/eyr0vge7p5o38nc/crash-2015-10-30_15.46.49-client.txt?dl=0

Here is the crash report. How can I fix this? Also, if there are more recent downloads, where can I find them?

**Comment by TheRegulator** [comment]
try forge version 11.14.3.1521
maybe it helps

**Comment by TheRegulator** [comment]
And remove Thaumic Tinkerer.
Thats a addon for Thaumcraft 4

**Comment by Dayyer1** [comment]
https://www.dropbox.com/s/eyr0vge7p5o38nc/crash-2015-10-30_15.46.49-client.txt?dl=0

Hmm, that didn't quite work, even when I did remove Thaumic Tinkerer. (Although I think that's a 1.8 version of it.)
Here's the most recent crash report...

**Comment by Azanor** [comment]
Try using forge 1521
