### ISSUE TITLE
Marked filtering tube drops blank label when broken

### ISSUE THREAD

**Issue by janinko** [Azanor/thaumcraft-5#140]
When I break filtering tube that has some essence marked, it drops blank label.

Thaumcraft 5.0.3

**Comment by Azanor** [comment]
That's intended.

**Comment by janinko** [comment]
I meant it shouldn't drop any label, as label is not used to mark the filtering tube. This way I can create unlimited amount of blank labels just by placing filtering tube, marking it (eg. with flask with essence) and breaking it.

**Comment by Azanor** [comment]
Doh, oh yeah. The labels aren't used up anymore.
