### ISSUE TITLE
thaumometer scan of redstone ore causes world corruption

### ISSUE THREAD

**Issue by CheapFrag** [Azanor/thaumcraft-5#144]
at least in creative mode, I have been able to reproduce a world corruption by scanning a block of redstone ore.
This caused instant shutdown of the game session.
Loading the world again automatically exits on loading.

Found in TC 5.0.3 as found in "Thaumcraft 5" mod-pack (TC5 only) on technic-launcher

**Comment by Azanor** [comment]
Unfortunately I cannot reproduce this. You wouldn't happen to have an error log would you?

**Comment by CheapFrag** [comment]
right... here´s the first crash report I got.
[crash-2015-12-05_11.08.46-client.txt](https://github.com/Azanor/thaumcraft-5/files/88029/crash-2015-12-05_11.08.46-client.txt)

The others look pretty similar. It seems to blame the lit redstone.

Clicking on a redstone block in creative caused a crash.
After a re-install of the pack I no longer get this behavior.
So all is fine with TC5 - keep up the good work.

**Comment by Azanor** [comment]
FYI - The original error seemed to be caused by NEI.
