### ISSUE TITLE
Negative value on flux emision(or so I believe)

### ISSUE THREAD

**Issue by Hyxaru** [Azanor/thaumcraft-5#146]
Tainted crawlers emit the flux particles, yet when they are in an aura with flux the levels drop. This might be intentional in the sense that flux is used up to create the fibrious taint that they spawn, yet the particles do not support this theory very well. Therefor I believe flux with an accidental negative value is being injected in the aura.

**Comment by Azanor** [comment]
Nope, they have the same chance to drain flux when a tendril is placed as tendrils do when they spread. So yes, the flux in the aura is supposed to drop.
