### ISSUE TITLE
Strange behavior connected to Totems

### ISSUE THREAD

**Issue by Fjolsvin** [Azanor/thaumcraft-5#148]
I put a shard into a totem of attraction, it was consumed and aura manipulation process began. Now, when I open totem menu again, the inventory of mine occasionaly behaves strange. I can't take (L-click) items from inventory at all in one case and/or I can take stack of items, which is (ostensibly) duplicated, replacing another items in my inventory (even the armor) with the items just picked (after the totem menu is closed, standard inventory opened and those messed stack of items moved, it "replace" the wrong items with the original ones). It doesn't happen all the time, but it happens repeatedly. Also rebooting a game doesn't solve the problem, while doing the same later can help.

I'll give you more details, if I'll be able to find some pattern in the bahavior.

**Comment by Azanor** [comment]
I cannot duplicate this at all. Are you still experiencing it?

**Comment by Fjolsvin** [comment]
I'm not playing since the warp-vanish bug (and till it's fixed), but it happened commonly. I had 5 outer poles under the totem. I have no idea how to help you with this, unfortunately.
