### ISSUE TITLE
Arcane bore powered by essentia

### ISSUE THREAD

**Issue by Fjolsvin** [Azanor/thaumcraft-5#149]
According to Thaumonomicon, Arcane bore should be powered by Perditio in both essentia or vis state. However it always sucks vis from aura only. If connected to an essentia jar via tubes, some essentia is sucked into the tubes (1 essentia per a tube), but not further to the machine. If connected to an essentia jar directly by placing the jar under the Arcane bore base, no essentia is used to power the machine at all.

**Comment by Reykja** [comment]
I've been able to get it powered by essentia by placing a single pipe immediately to one side of the base, and a jar immediately below that.

**Comment by Azanor** [comment]
The machine cannot except essentia from below. I see pipes seem to connect visually (which is a bug I will fix), but it can only accept essentia from the sides.
