### ISSUE TITLE
Slab wrong face culling

### ISSUE THREAD

**Issue by Breush** [Azanor/thaumcraft-5#153]
As the following images show, there's something wrong with the face culling.

Steps to reproduce:
- Place a lower vanilla slab (any kind)
- Place an upper thaumcraft slab (any kind) next to it (of course, you'll need an other block to place this one)

![2015-12-14_17 27 44](https://cloud.githubusercontent.com/assets/8821452/11786711/5ca7ee0a-a288-11e5-972d-663c741f1790.png)
![2015-12-14_17 27 00](https://cloud.githubusercontent.com/assets/8821452/11786712/5cabbd46-a288-11e5-835a-72a4c251d409.png)

**Comment by Azanor** [comment]
Do you have optifine or something similar installed?

**Comment by Breush** [comment]
That was testing (and I re-tested it today) with just forge + thaumcraft.
Can't you reproduce ?

**Comment by Azanor** [comment]
Nope, spent about 30 minutes trying all variations I could think of and the all looked fine for me.
Are you using fast graphics mode or something like that?

**Comment by Breush** [comment]
Well, both fast and detailed graphics are showing this bug.

Here's some more info:
- Minecraft coder pack 9.05
- Forge mod loader 8.0.99.99
- Forge 11.14.4.1577
- Baubles 1.1.1.0
- Thaumcraft 5.0.3

Orientation/Mipmap/Lighting have no effect: still the same bug.
I'm using Linux, might be related to the java version?
Bug appears with or without dedicated GC (NVidia GTX 850 M vs. Intel HD with OpenGL 3.0).

![capture du 2016-01-11 09 18 07](https://cloud.githubusercontent.com/assets/8821452/12229157/d29459e2-b844-11e5-9730-d16135304059.png)

**Comment by Breush** [comment]
If I'm this only one with this issue, it's not a big deal.
Moreover, this is a very specific problem, might not worth spending time on it.

**Comment by Breush** [comment]
Fixed using forge 11.15.0.1694 and thaumcraft 5.1.1.
