### ISSUE TITLE
Greatwood tree destroys compact machine wall

### ISSUE THREAD

**Issue by boundingstar** [Azanor/thaumcraft-5#154]
Growing a greatwood tree inside a compact machine block from the compact machines mod can cause it to replace some of the wall which should be indestructible

**Comment by WhiteScholar** [comment]
Might want to bring this up with that mods author as well, for compatability fixing for this mod and other mods that add large trees that can be grown.

**Comment by boundingstar** [comment]
There was a similar issue with some trees from another mod breaking the compact machines walls, and the compact machines dev said that it had to be a check that the tree does when it grows to not break blocks of a certain hardness https://github.com/SnowShock35/Obscurity/issues/136
