### ISSUE TITLE
Inventory problems with Hungry chest

### ISSUE THREAD

**Issue by KasperFranz** [Azanor/thaumcraft-5#155]
The hungry chest keeps one item in the chest and when other mods pull stuff from it they keeps recieving the same item, causing it to be to many items.

(we are running Infinity 2.2.2), we have reproduced it with 2 diffent mods, Thermal dynamics and Extra utilities 

Sorry for the wording, trying to get around that word someone call this type of bug, so it isn't found by that search query :)

**Comment by mujmajnkraft** [comment]
DO NOT POSR PROBLEMS WITH THAUMCRAFT 4. Azanor doesn´t update Thaumcraft 4 anymore. Maybe it´s not problem with Thaumcraft but with other mods.

**Comment by KasperFranz** [comment]
This is the issue tracker for the mod om curse. 
And yes I'm sure it's a problem with thaumcraft  as it is possible to do with Atleast 2 different other mods 

Den 20/12/2015 1.32 PM skrev mujmajnkraft <notifications@github.com>:

DO NOT POSR PROBLEMS WITH THAUMCRAFT 4. Azanor doesn´t update Thaumcraft 4 anymore. Maybe it´s not problem with Thaumcraft but with other mods.

**Comment by Azanor** [comment]
Does this occur with TC 5?

**Comment by Zsashas** [comment]
It took me a minute to understand what word you were trying to avoid...even if this is only in TC4, it's still a major issue. What methods specifically were you using to extract items?

**Comment by Azanor** [comment]
Well, all is quiet in here and I cant duplicate it in TC5 so closing this until some new info comes forward.
