### ISSUE TITLE
Question and suggestions.

### ISSUE THREAD

**Issue by Hyxaru** [Azanor/thaumcraft-5#160]
Formerly in thaumcraft 4, the arcane bore did not utilize any frugal upgrade on the arcane bore as there was no use for it. With the introduction to a perditio vis cost in thaumcraft 5 for the arcane bore, does it lower the vis costs, and if not isn't that a plausibility?

As a suggestion, could there be a config option to disable the chat lines generated by the thaumometer and the arcane dioptra?

Lastly, as another suggestion, is it possible to add redstone comparator support to the arcane dioptra? I can imagine the comparator emiting a stronger redstone signal based on the strength of the lowest level of an asigned vis type in one of the 13 by 13 chunks displayed. 

Please if you want to take the effort leave a reply with your opinion, I accept any critism. I would realy appriciate it.

**Comment by Azanor** [comment]
The mc forum post would be better for this. The github is for errors.
