### ISSUE TITLE
Cleaning up flux

### ISSUE THREAD

**Issue by Reykja** [Azanor/thaumcraft-5#161]
After heavily polluting my worldspawn chunks in survival mode, I realized that there doesn't seem to be a good way to clean up vitium in the aura. I can clean up taint with ethereal blooms. But the vitium in the aura itself seems to be something I can't do anything about. 
So far the only solution seems to be to let the taint spread, which very slowly depletes the vitium in the aura, and then clean up the taint. The default setting for taint_spread is only 3%, which means that if I want to make any significant dent in the vitium levels, it takes FOREVER. long enough that I ended up spending at least a 10:1 ratio of cleaning up messes to actual progress. But unless I fiddle with the taint_spread in the mod config (which feels a little like cheating), I don't seem to have a way to deal with it.
I don't really want the game mechanic to be free of consequence for using magic. I love the fact that I have to deal with taint and flux goo. But I would really like to have some way, however difficult it might be, to clean up actual vitium.

How about a spell or item that creates a hungry flux node? I am imaging a situation where I could create some sort of flux sink, but then have to deal with the sink itself. After having used a node magnet for the first time, I realized that it's a pain to drag nodes around. Perhaps the tainted node itself could be similarly obnoxious to get rid of after filling it up with the flux from my local aura.

 Or, perhaps even better, how about some forbidden knowledge spells that use vitium vis?

**Comment by Fjolsvin** [comment]
There is a solution. You missed it. Pure nodes have the ability to clean an aura from a vitium. However if the source of vitium is a tainted node, the only way is to merge the node with an another one and hope it will lose its "tainted" prefix.
