### ISSUE TITLE
flux goo appearing in worldspawn chunks for no apparent reason

### ISSUE THREAD

**Issue by Reykja** [Azanor/thaumcraft-5#162]
I originally built my smeltery, centrifuge, and infusion matrix in the chunks surrounding worldspawn. The area started becoming polluted, so I decided to relocate to an area out in a desert that was about 300 meters east. The new area is pretty well polluted now, but I wised up and built everything floating above the ground, so I don't have to worry about keeping anything clean except the area immediately under the platform I'm on.
I've been working on cleaning up the taint in worldspawn, but every time I put in a large batch of things in my essentia smeltery, the worldspawn (which is 300 blocks west of where my smeltery now is) undergoes one of those flux storms and goo appears everywhere. There is an unpolluted area inbetween the two polluted areas.
I'm wondering if the place the flux actually appears somehow didn't change when I moved my smeltery or my centrifuge.

**Comment by Azanor** [comment]
If there is still high levels of flux there then that is to be expected.
