### ISSUE TITLE
Arcane bore mining speed doesn't scale properly

### ISSUE THREAD

**Issue by Reykja** [Azanor/thaumcraft-5#165]
I have an arcane bore that I load up with a Potency V excavation focus and a diamond pickaxe with Efficiency 5. It takes approximately 4 seconds to mine 1 obsidian block. By comparison, my obsidian staff with only a Potency III enchantment can mine an obsidian block in approximately 1 second.

**Comment by MalkContent** [comment]
So what you are saying is a maxed out automatic digger is slower than a 60% maxed out manual digger and that is a problem somehow.
Also: did you feed the poor thing some perditio essentia?

**Comment by Reykja** [comment]
If the slow speeds was intentional, that's fine. (Maybe it was? But why that would be, I don't know.) But yes, I am saying that a maxed out bore is slower than a 60% speed manual digger. 
Yes, it had a full supply of essentia during the test.

**Comment by Reykja** [comment]
Also, I find it strange that the bore seems to struggle especially with obsidian. I laid out 3 stacks in three lines (64 blocks per line), and the max-speed bore averaged .066 seconds per block. I did the same thing with obsidian (same arrangement of blocks, to account for any differences in the seek time of the bore's block-finding algorithm) and the bore averaged 3.96 seconds per block. 
Since stone (hardness 1.5) breaks instantly (in vanilla Minecraft) when digging speed is more than 30 times the hardness of the block, I expected the stone to average significantly lower times than the obsidian. Specifically, I expected the obsidian to take 33.3 times longer than the stone, plus a 1/4 second delay per block. However, even accounting for the .25 second delay, the obsidian still took 57x longer than the stone to mine, per block.
It makes me wonder if the problem isn't that the arcane bore isn't registering as a "suitable tool" for mining obsidian, but it is for stone. 
Anyway, the long story short is that obsidian seems to take an unexpectedly long time to mine versus other blocks.

**Comment by Azanor** [comment]
Obsidian has a huge hardness compared to most other blocks so this is perfectly normal.
