### ISSUE TITLE
No warp from making certain items

### ISSUE THREAD

**Issue by Reykja** [Azanor/thaumcraft-5#167]
I noticed that, despite being forbidden knowledge I don't gain any warp from making a biothaumic mind, nor do I get any from making node magnets or brains in a jar. I also did not get any when I made an infernal furnace.

I do, however, gain warp from making other forbidden knowledge items, such as bottled taint and liquid death.

Just to be clear, I'm speaking entirely of the fabrication of the actual items, not the research.

**Comment by Azanor** [comment]
That is correct - just because the research is forbidden does not mean crafting the item should create warp.
