### ISSUE TITLE
Void Jars give Warp when crafted

### ISSUE THREAD

**Issue by Zsashas** [Azanor/thaumcraft-5#171]
Despite not mentioning this anywhere, or being marked as a Forbidden Research. Inverse of this: https://github.com/Azanor/thaumcraft-5/issues/167

**Comment by Azanor** [comment]
Are you using a modpack or something? They are definitely not set to cause warp in vanilla TC.

**Comment by Azanor** [comment]
Nevermind, there is a bug.
