### ISSUE TITLE
Golems equipped with Dart launchers miss

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#175]
Fiddleing around with them, had a golem shoot a skeleton in the face point blank like 20 times without causing damage. Looked like the projectile either hit and didn't cause damage or disappeared just before connecting.
Other times it worked just fine.
¯\_(ツ)_/¯

**Comment by Azanor** [comment]
That is actually a semi-vanilla thing. The arrow spawns clientside so it looks like it is fired, but on the server you are too close so it misses or never even spawns fully.

**Comment by MalkContent** [comment]
In any case, it's not working reliably :/ golem is completely content to permanently miss a mob 3 blocks in front of it. Also I don't think I ever saw it move. Then again it doesn't have to to get in range, seeing as i placed it inside the guard seals volume.
