### ISSUE TITLE
Fibrious taint has no texture in the world

### ISSUE THREAD

**Issue by Hyxaru** [Azanor/thaumcraft-5#179]

**Comment by Azanor** [comment]
I'm going to need a lot more than this. Taint looks fine for me.

**Comment by Hyxaru** [comment]
![2016-01-11_20 10 29](https://cloud.githubusercontent.com/assets/11833817/12243535/777ef8e0-b89f-11e5-9d3d-8bdd402d86b7.png)
As you can see, the hitbix of fibrious taint is shown, but there are no visuals
