### ISSUE TITLE
I'm curious: Hardcore mechanics?

### ISSUE THREAD

**Issue by Shirolol** [Azanor/thaumcraft-5#18]
Earlier I talked about this phenomenon of Taint literally chasing me.

Now that I thought about it, is this an undocumented Hardcore mechanic? Or really just the game being mean to me?

**Comment by Azanor** [comment]
You probably just got unlucky and had a lot of tainted nodes spawn near you - taint does not forgive, does not forget.... but it also does not chase. Hardcore or otherwise :p

**Comment by Shirolol** [comment]
Wow really? I had this consistently happen in at least 4different attempts. Wherever I went. First I hear thunder in the distance within one day after my arrival(sometimes instantly), then the thunder becomes closer and more frequent, to the point at which it happens several times per minute, then it eventually stops abruptly, but then everything is tainted. 

The world really hates me. :o

**Comment by davue** [comment]
I was also struggling with taint until I found an way to prevent it from coming (Tip: you have to get rid of the vitium in your aura). I like how aggressive it is, if you don't take care of it. It's definitely more difficult than in previous versions of Thaumcraft but in a positive way.

**Comment by Shirolol** [comment]
Read before you post, please. I never had the chance to do dirty magic.
