### ISSUE TITLE
Lots of placed items&objects disappear when upgrading to Thaumcraft 5.1

### ISSUE THREAD

**Issue by Pika0** [Azanor/thaumcraft-5#188]
When updating to Thaumcraft 5.1.0, many Thaumcraft objects that are placed in the world have disappeared.  Thaumcraft items that are stored in chests or player-inventories are unaffected.

Disappearing items include: Infernal furnace, hungry chests(taking their contents with them), essentia jars and pipes, totems, floating infusion matrix cube, magic mirrors.

The following items do not disappear: Vis crystals, research table, aura nodes, silverwood, candles, nitre, centrifuges, the 4 slanted support pillars for infusion, infusion pedestals, infused stone, aura nodes.

This happens when upgrading to 5.1.0 or 5.1.1 from 5.0.3.
From Forge 1577 to Forge 1690.
The log when opening the world in version 5.1.1: [https://paste.ee/p/FejaP](https://paste.ee/p/FejaP)

**Comment by Azanor** [comment]
I few people have reported this, but it is baffling to me. Apart from the normal bugfixes and the addition of golems and a couple of other blocks and items nothing major was changed - this should be like any other update so why blocks are disappearing is a bit puzzling. I suspect it might be something forge related.

**Comment by Azanor** [comment]
Either way, this is not something I will be able to fix on my side as far as I know.
