### ISSUE TITLE
Crash when placing stone while wearing goggles of revealing

### ISSUE THREAD

**Issue by Peach774** [Azanor/thaumcraft-5#189]
I got this crash when wearing goggles of revealing. I do have optifine and possibly as a result, the goggles do not have a texture. http://paste.ee/p/4dtma

**Comment by Azanor** [comment]
How did you get the jar your were trying to place? It has invalid metadata.

**Comment by Peach774** [comment]
It was a labeled fire jar with 13 fire in it when I broke it.

**Comment by Peach774** [comment]
I did use a tinkers construct pick to break it though
