### ISSUE TITLE
Aspect Assignment

### ISSUE THREAD

**Issue by Zsashas** [Azanor/thaumcraft-5#192]
Works just fine when the item is crafted via a crafting table, or even Infusion, but if the item is a result of smelting something, it often has no aspects at all unless purposefully given them.

**Comment by Azanor** [comment]
I'm not sure what you mean. Can you give examples?

**Comment by Zsashas** [comment]
Tinkers Construct Grout. Crafted from Gravel, Sand, and Clay. It has aspects. It gets smelted into Seared Bricks. However, nothing made from seared bricks, or the bricks themselves, have aspects.

Re-thinking this, I guess it makes sense, since the item could change drastically so I'm not sure what I was thinking when I started this...

**Comment by Azanor** [comment]
Yeah. In cases like those it is up to the mod author to add aspects.
