### ISSUE TITLE
100% Eldricht tab appears in survival after visiting creative singleplayer world

### ISSUE THREAD

**Issue by BerciTheBeast** [Azanor/thaumcraft-5#200]
I was researching stuff on my server, when i decided to go check something in creative. i went into a singleplayer creative game, checked what i needed to and then went back onto my server. opon opening the thaumonomicon i noticed a 100% Eldricht tab. when i clicked it it was blank.

Clientside Modlist:
-Minecraft Coder Pack 9.18
-Forge Mod Loader 8.0.99.99
-Minecraft Forge 11.15.0.1692
-Baubles 1.1.3.0
-Thaumcraft 5.1.1
-Inventory Tweaks 1.60-dev-27-43ecdd2
-Just Enough Items 2.15.1.71
-Just Enough Items Addons 0.7.1.28
-JourneyMap 1.8.8-5.1.3
-Waila 1.6.0-B3
-What Are We Looking At 1.4.1

Serverside Modlist:
-Minecraft Coder Pack 9.18
-Forge Mod Loader 8.0.99.99
-Minecraft Forge 11.15.0.1692
-Baubles 1.1.3.0
-Thaumcraft 5.1.1
-JourneyMap 1.8.8-5.1.3

**Comment by BerciTheBeast** [comment]
Issue dissappeared on game restart.

**Comment by Xirema** [comment]
I can confirm that this issue seems to happen on our server as well. If we join a Single-Player game first before joining multiplayer, the Eldritch and Golemancy tabs will be available even if we haven't unlocked anything in them (or can't even click on anything)
