### ISSUE TITLE
unicycle golem can't harvest(not sure if other can)

### ISSUE THREAD

**Issue by Filipmathias** [Azanor/thaumcraft-5#213]
i have a smart, deft unicycle golem that apparently he darts around real fast trying to harvest the different crops this is crops on farmland like potatoes and wheat

also tested pumpkins and sugarcane

**Comment by Azanor** [comment]
Sorry, what happens exactly? Does he move towards the crop, but doesn't actually harvest it?

**Comment by Filipmathias** [comment]
yea he darts around to the different crops but does not harvest.
love the new golems

**Comment by Azanor** [comment]
This is fixed in 5.1.3
