### ISSUE TITLE
barrier stone stopped working

### ISSUE THREAD

**Issue by Filipmathias** [Azanor/thaumcraft-5#214]
i tested with zombies and chickens in 5.1.2

**Comment by Autopoietico** [comment]
![2016-01-13_00 44 52](https://cloud.githubusercontent.com/assets/8708366/12286082/21dbadb6-b98f-11e5-8028-7a428d08d489.png)
Work well for me in Thaumcraft 5.1.2

**Comment by Azanor** [comment]
Is there a redstone signal near your barrier stones? That disables them.

**Comment by Filipmathias** [comment]
oh yea,, sorry about that doh xD had a poweered block beside it, had that since 1.8 did it never work? i could swear it worked before xD
