### ISSUE TITLE
Thaumometer GUI is not showing up on screen

### ISSUE THREAD

**Issue by DarcClan** [Azanor/thaumcraft-5#215]
Thaumometer isn't showing it GUI when held, I can press F to cycle the auras shown (and see the text message of it doing so) and the wand GUI works fine. This is occuring in both 5.1.1 and 5.1.2 for MC 1.8.9 using Forge 1.8.9-11.15.0.1694, also I've tested without any other mods other than Thaumcraft and it makes no difference, this includes removing Optifine.

**Comment by Azanor** [comment]
Hmmm, works perfectly fine for me. Using the same versions of TC and forge.
Are you using a texture pack?

**Comment by DarcClan** [comment]
Yes I am, I removed the resource pack and I did indeed see the Thaumometer GUI. I found the culprit, it was an older HUD.PNG from a BDcraft Thaumcraft texture pack
