### ISSUE TITLE
Arcane Lamp working very slowly/ not working at all

### ISSUE THREAD

**Issue by DarcClan** [Azanor/thaumcraft-5#216]
I placed an Arcane Lamp in the center of my 11x10 house, and removed all torches, the lamp make 1-2 spots of light and nothing else, also did not place lights in adjacent rooms (aka through walls). Lamp light spots took very long time 3-5 mins to show up in dark spots of room, and occasionally disappeared for no reason (light levels only provided by lamp, no other competing light sources).

Further testing was done in a naturally occurring cave entrance, I went into the cave, found a hallway and placed the lamp on the wall exposed on 5 sides to air blocks, it seemed to work a bit better, make 3-4 light spots, though it missed an area withing the 16 block radius (left lamp on wall for 5-10 mins), came back and removed lamp, cut a hole in the wall 1 block deep, placed lamp in hole in wall (1 side exposed to air block), 1 lights generated after 10+ mins (directly in front of lamp). dug one more block deeper, placed lamp there, covered it completely, no lights generated after 10+ mins.

**Comment by Azanor** [comment]
The lamp now requires line of sight to any area it wants to create a 'spot'. Could that be your problem?

**Comment by DarcClan** [comment]
Yes, I figured from testing that it seemed its obeying LOS, but wasn't sure, you might want to elaborate that in the flavor text in the thaumonomicon for the Arcane Lamp. Might save for some confusion from people porting from Thaumcraft 4
