### ISSUE TITLE
new wand focus

### ISSUE THREAD

**Issue by reinder-s** [Azanor/thaumcraft-5#218]
the new wand focus(can't remember what its called atm)
crashes my game whenever i try to use it in addition to that the dimension with id -42 also crashes my game when i enter it

**Comment by Azanor** [comment]
Crash logs would be helpful

**Comment by reinder-s** [comment]
i will get those now

**Comment by reinder-s** [comment]
[fml-client-latest.txt](https://github.com/Azanor/thaumcraft-5/files/88826/fml-client-latest.txt)

**Comment by Azanor** [comment]
Is it the vis focus you are talking about? That error was fixed a few versions ago. Try TC 5.1.3.

**Comment by reinder-s** [comment]
yes that one
and thanks :D
