### ISSUE TITLE
Infusion Matrix ignores infusion pillar data (direction it faces)

### ISSUE THREAD

**Issue by Hyxaru** [Azanor/thaumcraft-5#219]
Simply having four infusion pillar in the right spots is acceptable as a complete infusion altar. While not impacting gameplay or looking glitchy, it is quite amusing to see.
![2016-01-13_13 32 48](https://cloud.githubusercontent.com/assets/11833817/12294411/94dd775c-b9fa-11e5-9b1b-87d84498229c.png)

**Comment by Hyxaru** [comment]
Not a bug? Alright then.

**Comment by Azanor** [comment]
Lets just say not worth fixing :p
