### ISSUE TITLE
Fatal exception while in LAN

### ISSUE THREAD

**Issue by apotheoseGrifter** [Azanor/thaumcraft-5#227]
Using certain devices while in LAN seems to cause everyone who is not the host to disconnect with a message stating "A fatal exception has occurred" or occasionally a simple "Disconnected." I've confirmed that this happens most frequently when using the Essentia Smeltery, but has also happened with the Infernal Furnace, and the Crucible. It is not completely consistent for any of them. It never occurs with the Crystallizer and has not occurred thus far with the Centrifuge or Infusion Altar (though I only used the latter two once each). The tentative hypothesis is that it's related to flux being released, but it's not completely consistent even then so it's hard to say.

There are no crash reports, so I'll append some client logs to this report. One should be the error in the world we normally play in, the other should be the test world where we isolated Thaumcraft. I forgot to keep track of exactly which logs belonged to which sessions while testing (at least a few was on a different computer), but after some perusal I *think* these are the right ones:

http://pastebin.com/hX4DeVnz
https://paste.ee/p/kidvN

In addition, one of the logs may show an instance where the game froze while one of us was trying to save & exit, which requires a force-close to get out. This seems to happen most often when the non-host has already been disconnected at least once by the above bug, but that may be a false correlation. If it's unrelated, however, it seems to be a minor issue; it doesn't corrupt anything as far as I can tell.

EDIT: One more thing-- usually, the non-host player can't log back on after being disconnected until the relevant machine finishes what it was doing (i.e. the Essentia Smeltery finishes smelting). However, sometimes the disconnect is precipitated by a great deal of lag rather than occurring instantly, and I once managed to reconnect during that period and experienced a moderate amount of lag. (Server lag in both instances, I believe.) Oddly, the host doesn't appear to experience any lag whatsoever.

**Comment by Azanor** [comment]
There are a lot of thaumcraft related networking errors in those logs, though it doesn't seem to specify what is causing it. It just seems like the general pipeline for thaumcraft packets fails.
It is very strange and I cant duplicate the error on my side.
Do you have and thaumcraft addon mods?

**Comment by apotheoseGrifter** [comment]
I added Thaumic Infusion at one point early in the modpack, but removed it before we started the current world. While I would love to use some of the other addons, none of the rest are clearly labeled as 1.8.9, and Curse complains if I try to add anything that isn't explicitly 1.8.9 to the modpack.

If you also mean mods that add Thaumcraft compatibility rather than just mods that are expansions to Thaumcraft, the ones that I know or suspect have Thaumcraft compatibility would be Biomes O' Plenty, Blood Magic, Hammerz, and JEI Addons (and JEI, of course). There might be more, but I'd have to check. I can provide the whole mod list later.

Also, in case it's relevant, we both use Java 8.

**Comment by Azanor** [comment]
Looks like it might be a forge bug

**Comment by Azanor** [comment]
Also this has been reporting in https://github.com/Azanor/thaumcraft-5/issues/244 so I'm closing it as a duplicate. Continue discussion in #224 if you wish.

**Comment by Azanor** [comment]
Actually nevermind, reponing since this one is a bit neater :p

**Comment by apotheoseGrifter** [comment]
Thanks, I do my best. :P

**Comment by Azanor** [comment]
Looks like this was fixed on the forge side, so (in theory) the latest and greatest forge should solve your problems.
