### ISSUE TITLE
Possible Dupe bug?

### ISSUE THREAD

**Issue by bbqx** [Azanor/thaumcraft-5#230]
Playing the FTB unstable 1.8 pack. When crafting in the arcane workbench, just before taking out a completed item on the right side, Middle mouse click on the center of the 3x3 grid on the left side. The crafted item will move to the 3x3 grid without expending resources.

**Comment by Azanor** [comment]
Since middle mouse clicking like that is not vanilla behavior this bug would lie with whatever mod is adding that functionality.
