### ISSUE TITLE
Fog conflict with BetterRain

### ISSUE THREAD

**Issue by OreCruncher** [Azanor/thaumcraft-5#233]
I have reports that [BetterRain](https://github.com/OreCruncher/BetterRain) and Thaumcraft are having a conflict when handling fog effects.  BetterRain modifies fog density and coloration based on weather events as well as player biome.  This conflicts with Thaumcraft when it wants to have effects related to the Eldritch Guardian and some of the Thaumcraft potions.

At the moment the only way I can see resolving the issue is if Thaumcraft sets the result state of the FogDensity/RenderFogEvent to a value other than DEFAULT when it actually affects a change to fog.  In BetterRain I can lower my event handlers priority and check the result of the event to see if something else attempted a modification.

If you think there are other ways to handle let me know.  Thanks!

**Comment by MrGraphic** [comment]
Now after last update ( 5.1.4 ) you don't even need BetterRain to brake foggy "atmosphere". Fog effect after change does not return to correct state ( pre Guardian ). It looks like attenuation from effect has been removed and everything is surrounded with very thin fog.
