### ISSUE TITLE
Possible bug with Totem of Attraction - Totem poles

### ISSUE THREAD

**Issue by ThePB** [Azanor/thaumcraft-5#234]
I'm not sure that i'm understanding exactly the inner workings of the Totem but it seems like it either doesn't benefit from outer poles or it misses chunks while displacing aura.

What i did: I tried to move vitium from a group of chunks in a 9*9 area to a group of 3*3 (assuming that flux would then leak all the excess in nearby chunks via aura balancing.)
I've used really little vitium in the aura, but spread over .

Sadly i have no starting situation since i wasn't testing for bugs :D but this is the result
![2016-01-14_14 53 32mod](https://cloud.githubusercontent.com/assets/5775528/12330760/06251e8c-bae7-11e5-94ac-42ba6f07b2e2.png)

If i read the dioptra correctly each chunk is represented as an intersection of lines. I hope it's visible enough.

the third chunk from the dioprta chunk is the one with the highest amount of vitium, is one chunk farther away from the pole (pure node nearby messing with the directions, sigh)

This is the pole
![2016-01-14_14 53 00](https://cloud.githubusercontent.com/assets/5775528/12326389/d6233ff4-bad0-11e5-831d-f8f40f98e819.png)

It should, if i'm right, pull all the vitium from the external 3 chunks of a 9*9 area into the inner 3*3
But, as it's seen in the dioptra, there's still remaining vitium in areas that SHOULD have been cleansed (the ones on the left of the crystal.)

I tried adding more shards to see if it's just a "timing" problem, but it really doesn't go away.

![2016-01-14_14 52 00](https://cloud.githubusercontent.com/assets/5775528/12330817/3943aedc-bae7-11e5-9b8e-36569e131a64.png)

I do not think it's possible for the low amount of vitium that there was to have corrupted shards, having them releasing flux... so i was a little bit baffled.

I tried again in new chunks, and in short the results

![2016-01-14_17 59 10](https://cloud.githubusercontent.com/assets/5775528/12331628/a7114c6e-baea-11e5-9621-5e23b91ef6f5.png)
![2016-01-14_17 59 12](https://cloud.githubusercontent.com/assets/5775528/12331627/a710926a-baea-11e5-824a-2323691270bd.png)
![2016-01-14_18 00 27](https://cloud.githubusercontent.com/assets/5775528/12331629/a7120f46-baea-11e5-857e-1b8089f76fbd.png)
![2016-01-14_18 09 32](https://cloud.githubusercontent.com/assets/5775528/12331626/a70f76d2-baea-11e5-9094-b655aa67ca9f.png)

It almost seems like the poles are not counted towards the range of the totem. Mind you, i used just 3 shards in the second test.

Edit: I just used a jar full of macihna to create a slight amount of flux.

TC 5.1.3, baubles 1.1.3.0, forge 1690, journeymap 5.1.3 , Blood Magic 2.0.0 - 3, buildcraft 7.2.0 pre6, chisel and bits 1.8 beta 1, inventory tweaks 1.6 rev 27, jei 2.14.0.67, mantle 0.6 jenkins 60, mmm mmm mmm mmm 1.9b, silent's gems 1.3.8b, TiCo 2.0.1

**Comment by Azanor** [comment]
Each time the totem pole 'ticks' it selects a random chunk to draw from in the outer area and places it in a random chunk in the inner area. You might just be experiencing bad RNG. 
There might also be a source of flux in that chunk like a tainted node deep underground.

**Comment by ThePB** [comment]
the tainted node theory would be a TRULY unlucky one to be on 2 completely random test chunks, but the random chunk draining might explain it.
Theoretically i would have a ... 1/72? chance each totem tick (second?) to get that random chunk, making it possible i suppose to never draining it....I'll try feeding the 2 situations with quite a bit more shards to check if in the long run it gets fixed

**Comment by ThePB** [comment]
As promised, here to report. It's still consuming the last shard of 64, but the situation is:
![2016-01-15_16 03 04](https://cloud.githubusercontent.com/assets/5775528/12356213/9d36f6f0-bba1-11e5-8683-e4d083312a87.png)
I dare to say there's no tainted node involved, no shards, just not a single (well, a single) move that was made. Either i was hit by random for over 9000 damage, or there's something wrong.

**Comment by Azanor** [comment]
I did quite a bit of testing and everything seems to be working exactly as I expect it to. I will keep monitoring it, but closing this for now until something new comes up.

**Comment by ThePB** [comment]
I'll keep an eye open too :D Thanks for all the hard work!
