### ISSUE TITLE
[1.8.9-5.1.3] Possible Bug: Control Seal: Empty + Ender Chest

### ISSUE THREAD

**Issue by Xiaminou** [Azanor/thaumcraft-5#235]
I can't place a Control Seal: Empty on an Ender Chest, it just opens the chest. Is that intended?

EDIT: I don't know if it's been reported but in order to place a Seal on to a pedestal to upgrade it you need to use a hopper, might want to do something about that like shift + right click.

**Comment by Azanor** [comment]
Vanilla ender chests don't count as normal inventories and cant interact with most mod created inventory systems. In fact, if you take a closer look you will see that the hopper is not able to transfer items into the ender chest either.

**Comment by Xiaminou** [comment]
damn Vanilla! I miss Ender Storage...
