### ISSUE TITLE
Thaumium Fortress Armor Faceplates not crafting

### ISSUE THREAD

**Issue by mcjonesmike** [Azanor/thaumcraft-5#238]
I was doing mi thaumcraft 5 thing, and got to the stage where I could make the fortress armor and it's many faceplates. So I go to my infusion altar, get everything ready, whack my matrix with my wand and it doesn't craft. The altar won't even begin to draw the essentia out of it's jars. I have a few pics:
![2016-01-14_20 00 46](https://cloud.githubusercontent.com/assets/16712053/12342567/9e12a0fe-baf9-11e5-9fa1-d285a0895237.png)
![2016-01-14_20 00 54](https://cloud.githubusercontent.com/assets/16712053/12342574/abbb69f2-baf9-11e5-99c3-d449f4d57b67.png)
![2016-01-14_20 00 58](https://cloud.githubusercontent.com/assets/16712053/12342575/ac0ec1e2-baf9-11e5-8735-14e30a224dcc.png)
These pictures are from before and after i right clicked the matrix

**Comment by mcjonesmike** [comment]
*my

**Comment by CubeTwo** [comment]
https://github.com/Azanor/thaumcraft-5/issues/249

**Comment by Cirom** [comment]
I was going to report this bug too, but in realising there was already a case for it.. I'll simply supply some extra images here, which give some extra information.

http://imgur.com/a/bdqEo

Simply put, it seems that one of the ingredients is actually the result. (ie: to make the Thaumium Fortress Helmet of Revealing, you need a Thaumium Fortress Helmet of Revealing. As opposed to a regular Thaumium Fortress Helmet.)

**Comment by CubeTwo** [comment]
Hello.  I wait for new update and same problem has left.
So i cant craft Thaumium Fortress Helm with faceplates.
For craft Thaumium Fortress Helm with Goggles of revealing need Thaumium Fortress Helm with Goggles of revealing, And for craft others faceplates same problem.
http://imgur.com/a/hhk7f
Thaumcraft-1.8.9-5.1.4
Forge-11.15.0.1709

**Comment by Xirema** [comment]
I've been told that this is caused by a conflict with JEI-Addons. I haven't personally verified whether this is the case or not.

**Comment by Azanor** [comment]
I've seen the report about JEI-Addons as well. I have been able to craft a goggles helm and faceplates on my test world after fixing the bug, but I don't use JEI-addons so I cant confirm if that is true.
