### ISSUE TITLE
array index out of bounds

### ISSUE THREAD

**Issue by Darktotaled** [Azanor/thaumcraft-5#239]
Hello Azanor o/

I'm having this crash. I have a couple of mods along Thaumcraft 5.

Here is the pastebin: http://pastebin.com/RuyN5xhb

The mods are:
ArmorStatusHUD
bspkrsCore
BetterFps
Chameleon
CCC
ExNihilo 2
Highlands
Inventory Tweaks
NotEnoughItems
ProgressiveAutomation
ShadersMod
StorageDrawers
Thaumcraft 5.0.2( I downloaded this one after seeing the 5.0.3 having the same crash)
VeinMiner
VersionChecker

I hope it helps you finding the problem. I'll keep trying to run this.

Thanks for your time Azanor o/

Awesome mod btw
See ya on dire's Season 8

**Comment by Azanor** [comment]
Are you using texture packs of some kind?

**Comment by Darktotaled** [comment]
Soartex x32 i guess. I took shaders and better fps out and it worked btw

**Comment by Azanor** [comment]
Yeah, one of those mods was more than likely trying to bake an invalid model.

**Comment by Darktotaled** [comment]
Thanks Azanor. Keep the amazing job on Thaumcraft. I'll be following you in twitter. O/
