### ISSUE TITLE
Infusion Matrix make crash the game when placed on the altar

### ISSUE THREAD

**Issue by LokyLive** [Azanor/thaumcraft-5#240]
Hey i was building my infusion altar and when i've placed infusion matrix to finish my altar my game crashed and i can't load my map the game crash xD

Forge version : 11.15.0.1697
Thaumcraft version : 1.8.9-5.1.3

http://pastebin.com/Tx9rVmaX

**Comment by Azanor** [comment]
Could you try loading the map without thaumicinfusion installed?

**Comment by LokyLive** [comment]
I get the same idea this moorning and now it works thanks for help and good job for thaumcraft 5 ,p

**Comment by Azanor** [comment]
I'm still trying to track down the exact cause, but so far it seemt to be TI

**Comment by LokyLive** [comment]
Agree with you , without TI my save works well
