### ISSUE TITLE
Balance Shards Bug

### ISSUE THREAD

**Issue by UnstableCodeScarlet** [Azanor/thaumcraft-5#242]
I'm using one of each crystal to make a balance shard, but every time I throw in the catalyst it consumes it instead. is there a way to create a balance shard without this happening? Or is this just a bug?

**Comment by phit** [comment]
i get that with every crucible crafting, works fine in singleplayer but not on a server
server modlist:
>ActuallyAdditions-1.8.9-r23.jar
AuraCascade-1.8.8-v0.2.2a.jar
Baubles-1.8.9-1.1.3.0.jar
BetterBuildersWands-0.4.2-1.8.9r73+04b6c51.jar
BiomesOPlenty-1.8.9-3.0.0.1636-universal.jar
BloodMagic-1.8.9-2.0.0-5.jar
Botania.r1.8-248-MC1.8-64e3a96.jar
buildcraft-7.2.0-pre6.jar
Chameleon-1.8.8-0.2.0.jar
Charset-0.1.3-d0f7c0d0f2c326419bbc9c22.jar
Chisel-MC1.8.9-0.0.2.4.jar
chiselsandbits-mc1.8.9-v1.8-beta15.jar
ComputerCraft1.77pr0.jar
CosmeticArmorReworked-1.8.9-v1.jar
EssentialCmds-6.8d.jar
FastLeafDecay-1.8-1.6.jar
flatcoloredblocks-mc1.8.9-v1.5.jar
inventorysorter-1.8.9-0.7.1+23.jar
IronBackpacks-1.8-1.0.7.jar
jei_1.8.9-2.18.0.87.jar
journeymap-1.8.8-5.1.3-unlimited.jar
JWIN_v0.11.1_1.8.9.jar
Mantle-1.8.9-0.6.jenkins70.jar
mcjtylib-1.8.9-1.8.1beta4.jar
MCMultiPart-1.0.4-universal.jar
MmmMmmMmmMmm-1.9b.jar
Morpheus-1.8.9-2.0.57.jar
OpenComputers-MC1.8.9-1.5.21.1.jar
PermissionsEx-Sponge.jar
Ping-1.8.9-1.1.1.B10-universal.jar
PneumaticCraft-1.8.8-1.13.1-universal.jar
RandomThings-MC1.8.8-3.5.7.jar
rftools-1.8.9-4.20beta8.jar
spongeforge-1.8.9-1694-3.1.0-BETA-1049.jar
StorageDrawers-1.8.8-2.2.0.jar
TConstruct-1.8.9-2.0.1.jenkins43.jar
Thaumcraft-1.8.9-5.1.3.jar
Waila-1.6.0-B3_1.8.8.jar
Wawla-1.4.1-1.8+.jar
worldedit-forge-mc1.8.9-6.1.1-SNAPSHOT-dist.jar

**Comment by Zsashas** [comment]
Doesn't each shard have 2 of the primal aspect? I believe you need 2 of each for a balanced shard. It may simply be that one of the aspects is disappearing before you can throw in the catalyst shard, especially if you are doing it one at a time. Try throwing in some extra items to make sure you have enough aspects.

**Comment by phit** [comment]
not op, but I tried various crucible craftings with goggles on to make sure nothing is disappearing before throwing in the catalyst
like I said works fine in ssp but not in smp, I'm starting to suspect it might be SpongeForge causing this

**Comment by UnstableCodeScarlet** [comment]
I'm in SSP.
Also I have tried overdosing on aspects as well, and it didn't work.
Goggles of revealing say I have enough aspects as well.

**Comment by Azanor** [comment]
I suspect this is related to some mod or plugin. I've tested it on several different servers and in single player without any problem. Try removing mods one by one that interact with thaumcraft in some way and see if the recipe starts working.
I'm closing this for now, but feel free to reopen if the problem persists after you tried the above.

**Comment by phit** [comment]
Okay, i can confirm it is a bug with SpongeForge, tried with mods:
* Forge 1.8.9-11.15.0.1709
* Baubles-1.8.9-1.1.3.0.jar
* jei_1.8.9-2.19.0.94.jar
* Thaumcraft-1.8.9-5.1.3.jar
* spongeforge-1.8.9-1694-3.1.0-BETA-1061.jar

gave myself all research, then tried to craft two nitor with 3 coal and 6 torches, when i throw in the 2 glowstone the aspects get added to the crucible
![screenshot](https://cloud.githubusercontent.com/assets/2097483/12429669/d213dca6-beeb-11e5-8b03-3ddc84f9d906.png)

as soon as i remove spongeforge it works!

another thing when spongeforge is installed, rightclicking the crucible with a bucket of water, fills it but also places a source block of water next to it

I'll open a bug on the SpongeForge issue tracker

**Comment by Azanor** [comment]
Thanks
