### ISSUE TITLE
Golems - Control Seal: Block Breaker - Blacklist/Whitelist not working correctly (with torches?)

### ISSUE THREAD

**Issue by Cirom** [Azanor/thaumcraft-5#246]
ThaumCraft version: 5.1.3
Forge version: 11.15.0.1697

Essentially, when putting torches in the Blacklist / Whitelist slot of the Control Seal: Block Breaker's GUI, a golem is *supposed* to either only destroy torches, or destroy everything BUT torches. But it appears torches are ignored by the seal. (Could this be an issue with metadata, block states or NBT data?)

I made an Imgur album here to more easily explain the issue, as I find it easier to explain with pictures: http://imgur.com/a/SZ7sX

If this is an intended feature, would it be possible to have an Advanced Block Breaker for metadata/NBT support then, in a similar manner to the other Advanced seals?

**Comment by Azanor** [comment]
It is highly likely to be a metadata issue. I will take a look at either improving the base seal or creating an advanced version.
