### ISSUE TITLE
Bug in the Golemancy Tab

### ISSUE THREAD

**Issue by R3dstonedust** [Azanor/thaumcraft-5#247]
I cannot advance in the Golemancy-Tab. I have Basic Golemancy, Hungry Chest, Material Studies: Wood, Material Studies: Iron, Material Studies: Brass, Material Studies: Thaumium and Material Studies: Clay unlocked. Also the Golem Control Seal-Research is blinking, but if I click on it, nothing happens. I think the next research I would need is the clockwork mind, but there is no research for that available.
![unbenannt2](https://cloud.githubusercontent.com/assets/16723408/12360484/8ffd26d2-bbb8-11e5-83df-000e2b2b8d08.png)

**Comment by Geronimo747** [comment]
not a bug you need scan a angry zombie or brain  iam not sure which of the the two need to be scaned

**Comment by R3dstonedust** [comment]
Thank you very much. Now I can continue my research. Although it seems pretty bugged that the Golem Control Seals Research was blinking and nothing happens when I clicked it.
