### ISSUE TITLE
Whitelist Golems - Control Seal: Use - Blacklist/Whitelist not working correctly (with saplings)

### ISSUE THREAD

**Issue by CubeTwo** [Azanor/thaumcraft-5#250]
Control Seal: Use - Blacklist/Whitelist not working correctly with saplings.
I put sapling to Control Seal: Use Whitelist sapling( for tree farm) golem just use what he have in hand, sometimes he put sapling, sometimes he put (what he have in hands) wood or ect.
http://imgur.com/a/xl2v8
Thaumcraft-1.8.9-5.1.3
Forge-11.15.0.1697

**Comment by Azanor** [comment]
You have "use mod" selected which means it will use any item that comes from the same mod as the one in the filter.
