### ISSUE TITLE
golems should prefer to put items in inventories matching their filter before unfiltered inventories

### ISSUE THREAD

**Issue by 13eyedog** [Azanor/thaumcraft-5#251]
occasionally golems will put items I have chests for into the catch all, even with the catch all chest being set to -5 priority. It's sorta annoying!

**Comment by Azanor** [comment]
That is what the priority system is for, but if that it happening then there is a bug there that needs fixing. I will take a look at it.

**Comment by 13eyedog** [comment]
I ~think~ it was happening because the higher priority chest was 3 blocks off the ground, although the golem had climbing legs, and would occasionally accidentally decide to climb up that high, it usually decided it was out of reach and defaulted to the low priority one.

**Comment by Azanor** [comment]
That is possible. If a golem can't fulfil a task in a timely manner the task will get cancelled and it will perform another valid task on the list.
I think I will extend the timout a bit to give golem more of chance to reach their destination.
