### ISSUE TITLE
Reading Thaumcraft Research Pattern

### ISSUE THREAD

**Issue by knoxz** [Azanor/thaumcraft-5#255]
Hi there,
I wanted to code a clientside only mod for thaumcraft 5. A research helper for lazy or bored people. I am playing most of the time on a server where you can not decide if you want it to be easy mode or not.
Is there a way to read the active research when doing it? Like the structure and the available aspects?

If not could this be added to the API maybe?

**Comment by Azanor** [comment]
When you say active research, do you mean the research currently being worked on in the research table?

**Comment by knoxz** [comment]
Yes. Corner aspects, free spaces between them and the available aspects.

**Comment by Azanor** [comment]
Unfortunately not, nor is this the kind of thing usually available via an API. You will have to resort to java voodoo for this I'm afraid. Or just read it from the research note item nbt.
