### ISSUE TITLE
client crashes with falling sand or gravel

### ISSUE THREAD

**Issue by sixkiller5** [Azanor/thaumcraft-5#256]
forge-11.15.0.1697 TC version 5.1.3

whenever sand or gravel is falling my client crashes with the following error log: http://pastebin.com/NUd8AEsy

**Comment by knoxz** [comment]
Not a thaumcraft issue.
-> drunkmafia.thaumicinfusion

**Comment by sixkiller5** [comment]
sorry, i am kinda new to this reporting thing.
