### ISSUE TITLE
Breaking the block that a crystal is on does not give drops from the crystal

### ISSUE THREAD

**Issue by ThomasRules2000** [Azanor/thaumcraft-5#258]
When breaking the block that a vis shard crystal is attached to, the crystal disappears, but does not drop any shards.
This must be a worldgen crystal, and not a user created one.
Found when mining coal, and a water crystal did not appear from it

**Comment by Azanor** [comment]
Tried my best to duplicate this, but for me the crystals always drop when I break the block they are attached to. 
Remember, the crystal will only drop if ALL adjacent blocks are broken. As long as the crystal 'block' remains adjacent to another stone block it will not break and drop its goodies.

**Comment by ThomasRules2000** [comment]
Video confirmation of this bug:
https://youtu.be/JJbl00V25SU

**Comment by ThomasRules2000** [comment]
I'm honestly not sure which subversion of the mod this bug was in, but it was the latest version as of 16/01/16 at 6:45 PM GMT.

**Comment by Azanor** [comment]
The video just shows exactly what I explained above. When you break the block the shard is still attached to another solid block of coal.
