### ISSUE TITLE
Filling essentia transfuser prefers full labeled void jars over empty labeled jars occasionally

### ISSUE THREAD

**Issue by 13eyedog** [Azanor/thaumcraft-5#259]
Happens when the transfuser decided that the void jar was its filling destination when no other destinations are available, such as when all valid labeled jars are full, but when space frees up in a labeled jar, the transfuser will continue to fill the void jar

**Comment by Azanor** [comment]
Unfortunately there is no real way around it, unless you place the void jar further away than the normal jar.
