### ISSUE TITLE
essentia mirrors + transfusers?

### ISSUE THREAD

**Issue by 13eyedog** [Azanor/thaumcraft-5#260]
I was under the impression that the mirrors would allow pulling essentia through transfusers over distance. Oversight or balance feature?

**Comment by Azanor** [comment]
It does indeed work that way. Is your mirror and transfuser actually facing each other and within range?

**Comment by 13eyedog** [comment]
They're facing, as far as I can tell.
![2016-01-18_15 49 54](https://cloud.githubusercontent.com/assets/16729633/12402504/6edcfd8e-bdfb-11e5-9ddf-0eed8c30092f.png)
![2016-01-18_15 50 09](https://cloud.githubusercontent.com/assets/16729633/12402505/6ee0ece6-bdfb-11e5-8e6d-a272d1cd1057.png)
