### ISSUE TITLE
Unable to select Barrier stones for use with the focus of equal trade or builder focus.

### ISSUE THREAD

**Issue by Scorch-Mechanic** [Azanor/thaumcraft-5#262]
Holding shift and rightclicking a barrier stone with either focus does not change the target to Barrier Stone, and as such they cannot be used to replace other blocks nor be placed in the world generally with the builder focus. The equal trade focus works fine with the paving stones of travel, oddly (I haven't tried with the builder focus, but it was able to select paving stones of travel for placement).

Thaumcraft 5.1.3, Forge 11.15.0.1699

**Comment by Azanor** [comment]
They are tile entities and you cannot select tile entities to use with either of those foci.
