### ISSUE TITLE
[Compat] Everfull urn and Botania

### ISSUE THREAD

**Issue by KaseiFR** [Azanor/thaumcraft-5#266]
Hello,

If I recall correctly, the Everfull Urn used to fill nearby Petal Apothicary from Botania. As much as I like to throw water buckets at it, I tried the urn with Thaumcraft 5.1.3 and Botania r248 and it doesn't seem to work anymore (the crucible works fine).

Was this change intended, or was this feature just lost during the update?

**Comment by MalkContent** [comment]
(would also be neat if it could refill cauldrons, however useless that may be)

**Comment by Azanor** [comment]
The urns searches for any forge compatible fluid container that can be filled with water from the top. Possibly the Petal Apothicary isn't one of those anymore? Maybe you should report this in the botania github and reference this.

**Comment by williewillus** [comment]
botania 1.8 porter here, the old Everfull Urn in 1.7.10 was from an addon and had explicit compat for the apothecary, the apothecary does not accept automated liquid in other ways, so I think this is just a wontfix, unless @Vazkii wants to let the apothecary get filled by pipes, which I doubt ;p

**Comment by KaseiFR** [comment]
If we're waiting for @Vazkii 's approval on something that's basically a magic block (place it and forget it), I can close the issue ^^
I just don't want a complex redstone system just to fill the apothecary :(
Thanks for the awesome porting job by the way.

**Comment by Vazkii** [comment]
Well, @Azanor if you want...
https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/api/item/IPetalApothecary.java
Also...
https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/api/item/IExoflameHeatable.java

I'm sure everyone would love you for it.
*hides*

**Comment by Azanor** [comment]
Ohnoes!

In general I don't add explicit mod support because I'm incredibly lazy, but I'll take a look at this.

**Comment by Ioandar** [comment]
TC and Botania my favourite mods by far and I would be very happy if TC and Batania could work this out :)
