### ISSUE TITLE
Taint Cloud appers to cause tick (server) lag

### ISSUE THREAD

**Issue by chainingsolid** [Azanor/thaumcraft-5#271]
Minecraft Version 1.8.9
Forge Version: 11.15.0.1705
Thuamcraft Version: 5.1.3
TickProfiler (https://github.com/nallar/TickProfiler) what I used to find out what caused the lag

I have replicated it several times by just causing taint and waiting for the clouds.
The profiler above listed the clouds as causing the most lag.
I was able to fix the lag by have a command block kill all taint clouds and hooking it up to a redstone clock.

To be clear this is lagging the internal server, the tps(time per tick) is being effected not fps(frames per second), the client runs fine

how much the tps goes down varies from only missing a few ticks to 15 or more

**Comment by Azanor** [comment]
A single cloud should not cause that much lag, but it is possible for loads of them to. I assume you had lots of them?

**Comment by chainingsolid** [comment]
Your right 1 or 2 isn't bad at all, but 4 or 5 hurts(down to 10 tps) and this is in a world I made just to test this, so there's nothing else in it, just taint. So a lot turns out to be still in the single digits. I have a quad core and a GPU so this isn't my machine being slow. A taint node can cause enough of these clouds and to my knowledge there's no quick way in game to deal with them with out cheating. (I had 2 of them in spawn, eventually killed via commands, vitium aura is left however, had single digit tps for a bit).

**Comment by Azanor** [comment]
Taint clouds will be a lot rarer in the next release and I will probably remove them in the next major update in favour for a new mechanic I am working on. For now though there is not real way to reduce their performance hit without completely removing them from the game.
