### ISSUE TITLE
Goggles of Revealing don't need to be worn

### ISSUE THREAD

**Issue by Zsashas** [Azanor/thaumcraft-5#272]
They provide their effect even when just held in the hand.

**Comment by Azanor** [comment]
That is probably a side effect of a recent API change. I actually don't think this is a bug, more of an unexpected feature. I could see not actually wearing the goggles, just holding them and every now and again putting them to my face to check what is going on sort of like welding goggles.

**Comment by Zsashas** [comment]
That seems more like the effect you'd expect from holding the Thaumometer, however. The goggles were always something that had to be worn to have effect...

I do like that description though :P
