### ISSUE TITLE
Creative/Single Player World Cheat Sheet Use

### ISSUE THREAD

**Issue by AngelKairi** [Azanor/thaumcraft-5#273]
Just a tiny thing. Whilst streaming my little playthrough of 1.8 mods, I came across a little bug on my way while looking up what to do to get my next research tab. So.

1. I opened up the mod options to turn on Cheat Sheet.
2. Went into a new creative world.
3. Went back to survival world. Did not turn cheat sheet off.
4. Checked book. All research was reset.
5. Turned cheat sheet off and reopened the world.
6. All Research is reset.

It appears to override the research on my world when I toggle the cheat sheet. Just something I found over on my stream. If you need more information on this, just ask.

**Comment by Azanor** [comment]
When you say reset, do you mean everything was removed?

**Comment by AngelKairi** [comment]
While the cheat sheet is ACTIVE, all the research becomes unusable in survival. So when I took off the cheat sheet, all the research was reset. All gone.
