### ISSUE TITLE
Nodes generate in the End

### ISSUE THREAD

**Issue by Hyxaru** [Azanor/thaumcraft-5#274]
In thaumcraft 4, nodes used to be unable to generate in the End, but recently I discovered that they do now. While it might seem odd to exclude a dimension from nodes, honestly it might be cool in the sense that it is an alien world. It would certainly feel good to have some control of excluding tainted nodes and makes thaumostatic trips allot scarier through the void.

Opinion aside is this a bug or was it the case in Thaumcraft 4, just curious.

**Comment by Zsashas** [comment]
This definitely was not the case in TC4. I'm surprised I never noticed this myself though...lol.

**Comment by Azanor** [comment]
The problem is that if someone decides to set up base in the end the aura will drain quite quickly and they will soon find themselves in a taint hell. Will what you are suggesting does sound cool on paper, it could really mess with someones gameplay experience.
