### ISSUE TITLE
Crashing from particles

### ISSUE THREAD

**Issue by ClutchCabbage** [Azanor/thaumcraft-5#275]
http://pastebin.com/5eHF8VRp (If you don't wanna grab the upload)
[crash-2016-01-18_21.19.38-client.txt](https://github.com/Azanor/thaumcraft-5/files/95236/crash-2016-01-18_21.19.38-client.txt)

Keep crashing when teleporting to magical forest. The crash report seems to lead to you.
Thaumcraft 1.7.10 v4.2.3.5

**Comment by Azanor** [comment]
Sorry, this version of TC is no longer supported. The bug has been fixed in TC 5
