### ISSUE TITLE
aspect filling prio wrong - aspect jar not used even if in range, nearer but empty

### ISSUE THREAD

**Issue by Ioandar** [Azanor/thaumcraft-5#276]
here is what I see currently in TC5.1.3 world:

labled jars of an aspect that are empty will not be used but instead the void jar of same aspect will be filled and so aspects will be voided without ever using the empty labled jar of that aspect

FILLING as golems did in TC4 (i think):
1.) select all jars in ranged
2.) order them by aspect and then order normal/void

if (labeled jar of aspect found){
if (labeled jar is not full) then fill this else fill others normal jars of that aspect
else if void jar of that aspect is found -> fill this vaid jar
}

If no destination can be found (all jars full and no void). aspect stays alembic

can someone please check this if it also happens in your world?

TC5.1.3
Forge 1707

**Comment by Azanor** [comment]
What exactly are you referring to? Pipes or transfusers?

**Comment by Ioandar** [comment]
oh, sorry, transfusers

**Comment by Azanor** [comment]
The problem is that the processing for the transfusers happens a lot more often than it did for golems. Sorting them like that will add a lot of overhead to an already slow operation.
The simplest solution would just to make sure your void jars are further away than the other jars.

**Comment by Ioandar** [comment]
@Azanor 
okay, but that does not solve the problem -> A labeled jar will not be filled if it is *empty* (even *if* it is 
nearer to the transfuser)

I have my upper row all void and normal jar. all void jars stand on the normal jars of same aspect.

so the void jars of same aspect are farer away from the labeled jars of same aspect

The farer away void jar will be filled (which you said it will not)

*the strange thing -> If I put some aspect into a normal labeled jar, then suddenly it will be filled!*
