### ISSUE TITLE
Missing Eldritch Research

### ISSUE THREAD

**Issue by kingofrunes** [Azanor/thaumcraft-5#279]
I'm pretty sure it's bugged but could you double check this for Azanor. I only know of the existance of this through the creative research.

This is the research I'm missing: http://puu.sh/mBs46/9733d18c40.png

Revelations in the Outer Lands

Now I know this thing has a bunch of ??? which indicates it can be scanned but scanning it does nothing: http://puu.sh/mzKK5.png

This is what my current Eldritch Research looks like to show I should have all the proper gated research: http://puu.sh/mBsBu/431e09feac.png

I've also tried scanning a runed tablet and the ancient doorway as well as putting the runed tablet on the ancient doorway and defeating the boss. All to no avail of course. Seeing that I've scanned everything else I could in the Eldritch Dimension I have to believe that this is glitched in some way.

**Comment by Azanor** [comment]
Nope, there are just some stuff you have missed scanning. In short: scan anything "eldritch" - even eldritch stuff in the overworld.

**Comment by kingofrunes** [comment]
Really? I did scan the Eldritch stones in the overworld and got the Eldritch Infusion Altar. What other Eldritch things could I possibly scan?

**Comment by Azanor** [comment]
Did you scan a boss  and some other eldritch mobs?

**Comment by kingofrunes** [comment]
Oh right, that would probably help, I was too busy trying not to die to scan them. I guess that solves that then. Thanks Azanor.

**Comment by Azanor** [comment]
:)
