### ISSUE TITLE
Primal Focus and autocaster don't get along well.

### ISSUE THREAD

**Issue by 13eyedog** [Azanor/thaumcraft-5#281]
(ignoring the absurdity of even using a primal focus in an autocaster...)

Most of the time, the autocaster can't even fire the primal focus, though increased levels of frugal make it happen more often, so I assume what is happening is that it can't cast because the randomized vis cost is too high for the internal buffer, and when it randomly drops low enough it will fire.

**Comment by Azanor** [comment]
Pretty much. And beside that it is not a good idea to do it anyway since often the primal orbs just come right back at the caster. 
Either way, no bug here.
