### ISSUE TITLE
Node merging - propriety and dimension saving weirdness

### ISSUE THREAD

**Issue by ThePB** [Azanor/thaumcraft-5#282]
I've had this issue previously but i just attributed it to bad memory.
While trying to set up the thaumcraft only test for totem poles i've run into a tainted node.
(sorry, no screens of this, i really was not expecting it)

trying to stop it from interfering (and wanting to test a bit of merging) i just spawned a bunch (4 or 5) creative nodes near it. From a Tainted 60 (don't remember the aspect, sorry) it became a Tainted 80 vinculum (the nodes i spawned merged into a normal vinculum). i placed a silverwood, and after merging to a pure aqua 10+ node it became a pure 85 vinculum node. I let it work a bit in cleansing the aura. It became a pure 82 vinculum node. The dioptra i plomped nearby showed a steady reduction on the spike of vitium aura. it was working.

Logged off and on again... i see this.

![2016-01-19_14 31 06](https://cloud.githubusercontent.com/assets/5775528/12420582/cacfcece-bebd-11e5-9a2d-bc6ce1f40314.png)

WTF?

well. long story short, i try to merge it with other pure nodes (thanks silverwood... 1 node in 56 trees...yes i've time on my hands today :D) no propriety change... other 2 nodes, nothing, just increase in size.

I spam a little bit of creative node...(again, 4 or 5 nodes in quick succession) and i obtain this.

![2016-01-19_14 54 48](https://cloud.githubusercontent.com/assets/5775528/12420630/19daf4c6-bebe-11e5-8029-41c38ebc306a.png)

Logging off and on....

![2016-01-19_14 55 23](https://cloud.githubusercontent.com/assets/5775528/12420638/248dcff6-bebe-11e5-8238-d8f3035f9799.png)

I have no idea if this is on your side, forge's or simply a vanilla quirk that does not fit with the way nodes are coded. Or if it is due to data loss in spamming creative nodes... but well...

Sorry Azanor to bother you with weird things.

(Tc 513, forge 1707, baubles 1130, nothing else. Vanilla launcher)

**Comment by Azanor** [comment]
I'm scratching my head at this one. I can't really explain it. I will keep the report open and monitor it to see if I find similar issues and a possible cause.

**Comment by Shirolol** [comment]
It seems like the client and the server can't agree on the product of two merging nodes.

If you mix node types the client oftenly chooses the weaker one, while the server picks the stronger one. If you then relog the client's error gets corrected.

**Comment by Azanor** [comment]
I should mention I found the cause for this - just forgot to update the github here with 'solved'. Like a numpty I did the merging both server and clientside and since there is a random element to how nodes merge it means that the node on the server will be different from the node on the client. They ended up being desynced and the problem will only reveal itself when you relog.
