### ISSUE TITLE
 Localization to Russian

### ISSUE THREAD

**Issue by Mana3195** [Azanor/thaumcraft-5#283]
When translating the game with the mod thaumcraft, in thaumic book displays the number of bad aspects ( not visible numbers) Increase please them.

**Comment by Azanor** [comment]
Not sure what you mean. Can I get a screenshot please.

**Comment by Mana3195** [comment]
http://i.imgur.com/DIpfJkY.png

**Comment by Azanor** [comment]
There is a config option that will increase the size of those numbers. It is called large_tag_text.

**Comment by Mana3195** [comment]
Thank you so much
