### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by CubeTwo** [Azanor/thaumcraft-5#291]
Hello. Why you closed my topic and dont fix that bug? I wait for new update and same problem has left.
So i cant craft Thaumium Fortress Helm with faceplates.
For craft Thaumium Fortress Helm with Goggles of revealing need Thaumium Fortress Helm with Goggles of revealing, And for craft others faceplates same problem.
http://imgur.com/a/hhk7f
Thaumcraft-1.8.9-5.1.4
Forge-11.15.0.1709

**Comment by Xirema** [comment]
Don't title issue submissions as "Bug". If the issue persisted through the update, just comment on the closed thread that the issue is still happening in the new version.
