### ISSUE TITLE
Infernal Furnace looses items.

### ISSUE THREAD

**Issue by chrisbecke** [Azanor/thaumcraft-5#294]
TC 1.5.3 with Forge 1705 running on a dedicated server.

I made my first batch of Balance Shards (32) took 16 of them and tossed them into the Infernal Furnace. I threw a couple in using 'Q' and then the entire stack with Ctrl-Q.

When I went to collect, I picked up 11 Salis Mundis.

A subsequent test, throw in 4 stacks of cobblestone. Exactly 3 stacks of smooth stone came out.

**Comment by Hyxaru** [comment]
Azanor please don´t say the infernal furnace destroys the item, turning it into flux like the essentia smeltery....

**Comment by chrisbecke** [comment]
I have updated to Forge 1710, and TC 1.5.4 and performed the same test. 4 stacks of cobblestone in - 2 stacks had to be thrown in multiple times as they kept glitching out the furnace.

In the previous tests I did search around my Infernal Furnace to see if the items had glitched out and did not find them.
