### ISSUE TITLE
Ticking Tile entity with runic matrix

### ISSUE THREAD

**Issue by Blackwindinsocks** [Azanor/thaumcraft-5#295]
Happens whenever i place one, doesn't matter where.
 using FTB Unstable, figured it wouldnt hurt to throw the crash report here.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  LoadingPlugin (RandomThings-MC1.8.8-3.5.7.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.3.jar)
  thaumicinfusion (ThaumicInfusion-4.73.jar)
  LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 1/20/16 9:18 PM
Description: Ticking block entity

java.lang.AbstractMethodError: net.minecraft.block.BlockAir.canStabaliseInfusion(Lnet/minecraft/world/World;Lnet/minecraft/util/BlockPos;)Z
	at thaumcraft.common.tiles.crafting.TileInfusionMatrix.getSurroundings(TileInfusionMatrix.java:648)
	at thaumcraft.common.tiles.crafting.TileInfusionMatrix.func_73660_a(TileInfusionMatrix.java:217)
	at net.minecraft.world.World.func_72939_s(World.java:1716)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2089)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at thaumcraft.common.tiles.crafting.TileInfusionMatrix.getSurroundings(TileInfusionMatrix.java:648)
	at thaumcraft.common.tiles.crafting.TileInfusionMatrix.func_73660_a(TileInfusionMatrix.java:217)

-- Block entity being ticked --
Details:
	Name: TileInfusionMatrix // thaumcraft.common.tiles.crafting.TileInfusionMatrix
	Block type: ID #742 (tile.infusion_matrix // thaumcraft.common.blocks.devices.BlockInfusionMatrix)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (96,66,342), Chunk: (at 0,4,6 in 6,21; contains blocks 96,0,336 to 111,255,351), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #742 (tile.infusion_matrix // thaumcraft.common.blocks.devices.BlockInfusionMatrix)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1716)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['kirbyking987'/4185, l='MpServer', x=97.55, y=65.80, z=341.52]]
	Chunk stats: MultiplayerChunkCache: 10, 10
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 140.00,64.00,252.00 - World: (140,64,252), Chunk: (at 12,4,12 in 8,15; contains blocks 128,0,240 to 143,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 390806 game time, 535389 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 3 total; [EntityPlayerSP['kirbyking987'/4185, l='MpServer', x=97.55, y=65.80, z=341.52], EntityAuraNode['Aura Node'/4189, l='MpServer', x=171.50, y=88.50, z=461.50], EntityBat['Bat'/3951, l='MpServer', x=92.28, y=16.03, z=321.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1370417704 bytes (1306 MB) / 2603089920 bytes (2482 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 3 total; -Xms256M -Xmx5120M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 1, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.0.1697 55 mods loaded, 55 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.18} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.0.1697-universal.jar) 
	UCHIJAAAA	Forge{11.15.0.1697} [Minecraft Forge] (forge-1.8.9-11.15.0.1697-universal.jar) 
	UCHIJAAAA	bagginses{@VERSION@} [Bagginses] (Bagginses-2.1.3-1.8.9.jar) 
	UCHIJAAAA	BloodMagic{1.8.9-2.0.0-5} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-5.jar) 
	UCHIJAAAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAAAA	Thaumcraft{5.1.3} [Thaumcraft] (Thaumcraft-1.8.9-5.1.3.jar) 
	UCHIJAAAA	Botania{r1.8-249} [Botania] (Botania.r1.8-248-MC1.8-64e3a96.jar) 
	UCHIJAAAA	BuildCraft|Core{7.2.0-pre6} [BuildCraft] (buildcraft-7.2.0-pre6.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.2.0-pre6} [BC Transport] (buildcraft-7.2.0-pre6.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.2.0-pre6} [BC Factory] (buildcraft-7.2.0-pre6.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.2.0-pre6} [BC Silicon] (buildcraft-7.2.0-pre6.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.2.0-pre6} [BC Robotics] (buildcraft-7.2.0-pre6.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.2.0-pre6} [BC Energy] (buildcraft-7.2.0-pre6.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.2.0-pre6} [BC Builders] (buildcraft-7.2.0-pre6.jar) 
	UCHIJAAAA	mcmultipart{1.0.4} [MCMultiPart] (MCMultiPart-1.0.4-universal.jar) 
	UCHIJAAAA	CharsetLib{0.1.3} [‽] (Charset-0.1.3-d0f7c0d0f2c326419bbc9c22.jar) 
	UCHIJAAAA	CharsetTweaks{0.1.3} [*] (Charset-0.1.3-d0f7c0d0f2c326419bbc9c22.jar) 
	UCHIJAAAA	CharsetWires{0.1.3} [+] (Charset-0.1.3-d0f7c0d0f2c326419bbc9c22.jar) 
	UCHIJAAAA	CharsetAudio{0.1.3} [♫] (Charset-0.1.3-d0f7c0d0f2c326419bbc9c22.jar) 
	UCHIJAAAA	CharsetPipes{0.1.3} [|] (Charset-0.1.3-d0f7c0d0f2c326419bbc9c22.jar) 
	UCHIJAAAA	CharsetGates{0.1.3} [&] (Charset-0.1.3-d0f7c0d0f2c326419bbc9c22.jar) 
	UCHIJAAAA	chisel{@VERSION@} [Chisel] (Chisel-MC1.8.9-0.0.2.4.jar) 
	UCHIJAAAA	chiselsandbits{@version@} [Chisels & Bits] (chiselsandbits-mc1.8.9-v1.8-beta8.jar) 
	UCHIJAAAA	compasscoords{1.8.9-0.2.6} [Compass Co-ords] (CompassCoords-1.8.9-0.2.6.jar) 
	UCHIJAAAA	ComputerCraft{1.77pr0} [ComputerCraft] (ComputerCraft1.77pr0.jar) 
	UCHIJAAAA	crafttweaker{3.0.0} [crafttweaker] (CraftTweaker-Customized-1.8.8-3.0.1.jar) 
	UCHIJAAAA	CustomMainMenu{1.9.3} [Custom Main Menu] (CustomMainMenu-MC1.8.8-1.9.3.jar) 
	UCHIJAAAA	ezstorage{1.0} [EZ Storage] (ezstorage-1.8.9-1.2.2.jar) 
	UCHIJAAAA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.8.9-v1.3} [Flat Colored Blocks] (flatcoloredblocks-mc1.8.9-v1.5.jar) 
	UCHIJAAAA	furnus{1.4} [Furnus] (Furnus-1.8.9-1.4.jar) 
	UCHIJAAAA	hopperducts{1.4.6} [Hopper Ducts] (hopperducts-mc1.8.8-1.4.6.jar) 
	UCHIJAAAA	inventorysorter{0.7.1+23} [Simple Inventory sorting] (inventorysorter-1.8.9-0.7.1+23.jar) 
	UCHIJAAAA	IronChest{6.0.115.759} [Iron Chest] (ironchest-1.8.9-6.0.115.759.jar) 
	UCHIJAAAA	JEI{2.17.3.83} [Just Enough Items] (jei_1.8.9-2.17.3.83.jar) 
	UCHIJAAAA	JEIAddons{0.8.1.30} [Just Enough Items Addons] (JEIAddons_1.8.9-0.8.1.30.jar) 
	UCHIJAAAA	journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
	UCHIJAAAA	jeresources{0.1.1.@BUILD@} [Just Enough Resources] (JustEnoughResources-1.8.9-0.1.1.jar) 
	UCHIJAAAA	llor{1.0.4-mc1.8.8} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.0.4-mc1.8.8.jar) 
	UCHIJAAAA	mantle{1.8.9-0.6.jenkins70} [Mantle] (Mantle-1.8.9-0.6.jenkins70.jar) 
	UCHIJAAAA	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
	UCHIJAAAA	Morpheus{1.8.9-2.0.57} [Morpheus] (Morpheus-1.8.9-2.0.57.jar) 
	UCHIJAAAA	fodc{1.7.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.7.1.jar) 
	UCHIJAAAA	playerrugs{0.0.1} [Player Rugs] (PlayerRugs-1.8.8-1.2.0.jar) 
	UCHIJAAAA	PneumaticCraft{1.13.0 - err} [PneumaticCraft] (PneumaticCraft-1.8.8-1.13.1-universal.jar) 
	UCHIJAAAA	progressiveautomation{1.6.16} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.16.jar) 
	UCHIJAAAA	RandomThings{3.5.7} [Random Things] (RandomThings-MC1.8.8-3.5.7.jar) 
	UCHIJAAAA	ResourceLoader{1.4} [Resource Loader] (ResourceLoader-MC1.8.8-1.4.jar) 
	UCHIJAAAA	rftools{4.20beta8} [RFTools] (rftools-1.8.9-4.20beta8.jar) 
	UCHIJAAAA	simpleretrogen{2.2.1+2} [Simple Retrogen] (simpleretrogen-1.8.9-2.2.1+2.jar) 
	UCHIJAAAA	tconstruct{1.8.9-2.0.1.jenkins44} [Tinkers' Construct] (TConstruct-1.8.9-2.0.1.jenkins44.jar) 
	UCHIJAAAA	thaumicinfusion{4.73} [Thaumic Infusion] (ThaumicInfusion-4.73.jar) 
	UCHIJAAAA	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UCHIJAAAA	wawla{1.4.1} [What Are We Looking At] (Wawla-1.4.1-1.8+.jar) 
	Loaded coremods (and transformers): 
NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  net.fybertech.nwr.NowWithRendering
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
LoadingPlugin (RandomThings-MC1.8.8-3.5.7.jar)
  lumien.randomthings.asm.ClassTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.3.jar)
  
thaumicinfusion (ThaumicInfusion-4.73.jar)
  drunkmafia.thaumicinfusion.common.asm.BlockTransformer
  drunkmafia.thaumicinfusion.common.asm.WorldTransformer
LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
  lumien.resourceloader.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13416 Compatibility Profile Context 15.300.1025.0' Renderer: 'AMD Radeon HD 7800 Series'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- TinkerDebug (Enabled/Not Forced)

	Launched Version: 1.8.9
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 7800 Series GL version 4.5.13416 Compatibility Profile Context 15.300.1025.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD FX(tm)-8320 Eight-Core Processor

**Comment by Azanor** [comment]
This is actually a bug with thaumicinfusion as far as I am aware.
