### ISSUE TITLE
Things attached to blocks displaced by portable hole focus pop off and are dropped as items

### ISSUE THREAD

**Issue by Scorch-Mechanic** [Azanor/thaumcraft-5#296]
Forge 11.15.0.1710, Thaumcraft 1.8.9-5.1.4

Torches, redstone, grass, saplings, buttons, levers, crops, flower, anything that requires a block to stick to. They all pop off and are dropped as items when the portable hole focus displaces the block they are attached to. 

Mods:
Baubles-1.8.9-1.1.3.0.jar
Chameleon-1.8.8-0.2.0.jar
Durability Show-1.8.9-2.1.2(1).jar
InventoryTweaks-1.60-beta-29.jar
jei_1.8.9-2.21.0.99.jar
JEIAddons_1.8.9-0.9.0.34.jar
journeymap-1.8.8-5.1.3-unlimited.jar
JWIN_v0.11.1_1.8.9.jar
RoguelikeDungeons-1.8.9-1.4.5.jar
StorageDrawers-1.8.8-2.2.0.jar
Thaumcraft-1.8.9-5.1.4
Waila-1.6.0-B3_1.8.8.jar
Wawla-1.4.1-1.8+.jar

**Comment by Zsashas** [comment]
Well it makes sense, since the Portable Hole temporarily replaces blocks with "Empty Space" blocks.

**Comment by Xirema** [comment]
The only thing I can say to this is that in TC4, these kinds of items would be maintained, not dropped.

I do, however, consider it an open question as to whether they *should* drop or not. On one hand, I like sealing off the area under my altar where I spam candles, and it would be nice to access the area with a Portable hole without risking knocking candles off the floor. On the other hand, it makes a FANTASTIC way to harvest Vis Crystals if they get knocked off when I use a portable hole on an adjacent block.
