### ISSUE TITLE
Chests doesn't open if they have a bottom slab above them.

### ISSUE THREAD

**Issue by MineCharls** [Azanor/thaumcraft-5#299]
Chests doesn't open if they have a bottom slab above them. However it does if it's a top slab and it worked in thaumcraft 5.0.3. It's happening since I updated to 5.1.

**Comment by Azanor** [comment]
Why would a vanilla bug be my problem? My guess is something changed in 1.8.9.

**Comment by MineCharls** [comment]
It does not happen in vanilla minecraft :(

**Comment by Azanor** [comment]
Do you mean vanilla minecraft with or without forge installed?

**Comment by MineCharls** [comment]
Without ':D I see it's a forge bug. Thanks and sorry for bothering!

**Comment by Azanor** [comment]
Np :)
