### ISSUE TITLE
1429 line: CV is present.

### ISSUE THREAD

**Issue by Mexahoid** [Azanor/thaumcraft-5#3]
tc.research_page.ARCANEBORE.3=The bore can be powered with §8Perditio§0 essentia or vis which will greatly speed up the rate at which it mines. Vis or essentia can be provided by pipes and/or relays as normal.<BR>One point of §8Perditio§0 essentia will speed the bore for the next 20 blocks mined. Alternatively 5 CV is required per block mined and the bore can accept up to 100 CV per tick.

I don't think that this is intended.

**Comment by Azanor** [comment]
nope
