### ISSUE TITLE
Golems don't work properly/don't follow seal reqests

### ISSUE THREAD

**Issue by BerciTheBeast** [Azanor/thaumcraft-5#301]
I made a golem that's supposed to farm sugar cane for me. It sort of worked for a bit and then it stopped and stood still. After I left the game I noticed this in the server console: 

http://imgur.com/a/Ad6eh

(sorry, i don't know how to paste bin it since i don't know where to find the relevant logs)
I think it did start working once I left its working area, but I didn't stay around to watch. I'm pretty sure its supposed to work even if I'm around.

Playing Thaumcraft 5.1.4 on server with forge 1705.

**Comment by 13eyedog** [comment]
You need to extend the seal's range up to encompass the tops of the sugar canes, because those are what the golems actually look for to farm.

**Comment by Azanor** [comment]
Yup, you just need to increase the range of the seal.

As a bonus you did manage to report an error in regards to the elemental axe which is what is listed in those logs.  :)
