### ISSUE TITLE
Golems with deft property kill's doesn't count as a player kill.

### ISSUE THREAD

**Issue by MineCharls** [Azanor/thaumcraft-5#306]
The no longer drop the armor, or zombie brains or rare drops like they did in TC4, I don't know if this is intended or not, in that case pardon the ignorance.

**Comment by Azanor** [comment]
You might just be getting bad RNG. Mobs killed by golems still drop XP and the same flag that causes mobs to drop XP is used to determine if they drop their rare drops.
