### ISSUE TITLE
Taint dust does not break quickly with shovel

### ISSUE THREAD

**Issue by Quarg** [Azanor/thaumcraft-5#308]
The tool used has no effect on the time taken to break taint dust, and similarly the shovel of the earthmover has no effect on it.

Taint dust is currently extremely slow and inconvenient to get rid of at the moment as a result, and I can't help but feel like that is not intended.

**Comment by Xirema** [comment]
Taint dust will slowly dissolve and eventually dissipate over time, so it's not strictly necessary to proactively remove it.

**Comment by Pika0** [comment]
You can also remove it by placing things (like torches) in its spaces (just like removing a water source block).

**Comment by Quarg** [comment]
Though I was aware of being able to place things to destroy it, I was intending on breaking it properly, as it has occasional random drops, including things such as taint tendrils, which can be useful.

I also have not observed the dust dissipate over time, though I have not tested that thoroughly.
