### ISSUE TITLE
Weird errors in console that i think are aura related

### ISSUE THREAD

**Issue by BerciTheBeast** [Azanor/thaumcraft-5#310]
I know the description is very vague, but i do get errors in the console, something about Aurahandling.

http://imgur.com/JaIkm3g

TC 5.1.4 on server with forge 1705

**Comment by sfPlayer1** [comment]
I'm getting this as well on FC1.

InventoryArcaneWorkbench.field_70465_c (=eventHandler) must be null while this happens.

**Comment by Azanor** [comment]
Not really a bug, just a printStackTrace left in where it should not be.
