### ISSUE TITLE
Thaumcraft 4 Buildcraft Incompatibility

### ISSUE THREAD

**Issue by Nosnamreh** [Azanor/thaumcraft-5#323]
Hi there!

The Buildcraft Miner (Not Quarry. The Robot) isn't mining shards, though it does get amber and cinnabar ores. The bug on the BC side can be found here:

https://github.com/BuildCraft/BuildCraft/issues/3189

I'm a huge Thaumcraft fan, and really wish other mods would update to 1.8.9. Thank you for your time.

**Comment by Azanor** [comment]
Crystals currently don't have ore dictionary entries which is probably the cause. I will add it which should hopefully help with this.

**Comment by Nosnamreh** [comment]
Thank you!

I feel like the same issue would cause a small dilemma for Thaumcraft 5, with the vis crystals.

In my opinion (I'm not an experienced dev in any regard, just a player who loves the mods), robots should be able to mine those too. This would create a little issue where the thaumaturge in question would need to make some delay system to keep his robots from harvesting the crystals prematurely (assuming they grow. I could be making a big idiot out of myself). To me, that feels much more fun than having to mine them by hand (Or use golems. Hmm.)

Regardless of the future, thanks for the quick response. Myself, and I'm sure a few others, really appreciate it.
