### ISSUE TITLE
Crash with BOP, Just a Few Fish and Thaumcraft

### ISSUE THREAD

**Issue by sweetsosweet** [Azanor/thaumcraft-5#324]
Hi, I downloaded the [Just a Few Fish](http://minecraft.curseforge.com/projects/just-a-few-fish) mod by tmtrvlr , but I get a crash when I load it into a new world. 

[Here's my report](http://pastebin.com/DG3BhBZN)

The weird thing is it seems to work with just BOP and JAFF, but when I add Thaumcraft I get the crash. I'm not sure if this is an issue between all three mods or just one, but I've checked with the other two mods, and neither say they would cause the issue as they are based on vanilla code. Would Thaumcraft be causing issues with animals spawning??

Thanks for any help!

**Comment by Azanor** [comment]
The error seems related to BoP. It might not be caused by BoP however, but something is messing with it. I do know however TC works with BoP, so the problem might lie with Just a few Fish. I suggest you log the error with BoP.
