### ISSUE TITLE
5.1.4 warp effect causes black screen

### ISSUE THREAD

**Issue by Yavos** [Azanor/thaumcraft-5#327]
Some warp effect in version 5.1.4 seems to make my screen completely black. I can still get into menus (like exit or inventory) but I can't see anything. Only guessing the button's location helps.

It belongs to the message "The light suddenly becomes overwhelmingly bright and burns your skin." It seemed to go away after ~2 minutes, though. The second time it happened I died from burning and the effect remained even after I restarted my client until I managed to click the revive button that was hidden somewhere behind that black minecraft window.

For completion here's a list of my currently installed mods:
Forge 1.8.9-11.15.0.1710
Blood Magic 2.0.0-3
Chameleon 0.2.1
Chisels & Bits 1.8.2
DummyCore 2.1.189.12
Flat Colored Blocks 1.5
Guide-API 2.0.0 (Custom Build)
Inventory Tweaks 1.60 beta-30
Iron Chest 6.0.119.765
JourneyMap 5.1.3
JEI 2.21.0.98
JEI Addons 0.9.0.32
Morpheus 2.0.57
Optifine 1.8.9 HD U H2 (maybe the one causing this?)
Storage Drawers 2.2.1
Thaumcraft 5.1.4
ThaumicBases 1.4.189.9

**Comment by Azanor** [comment]
This happens on certain system configurations. There is a config option to turn off the warp FX.
