### ISSUE TITLE
Server crash loop in Outer Lands

### ISSUE THREAD

**Issue by NonanteSeize** [Azanor/thaumcraft-5#334]
Server is on a Windows 7 Workstation where I also play.
12 Go RAM, good processor.

Server is on 1.8.9

Mods on server are :
- Forge (1.8.9) 11.15.0.1719
- Thaumcraft (1.8.9) 5.1.4
- JEI (1.8.9) 2.22.4.106
- Buildcraft (ALPHA for 1.8.9) 7.2.0-pre6

Clients have the same, plus Xaeros minimap (1.8.9) v1.7.9

A friend and me just opened an Outer Lands portal, and explored for about 5 minutes.
When we came upon a small room with purple liquid in a 3x3 pool (taint is my best guess),
Server crashed.
Restarted server, logged back in, less than a second later crash again.
Needless to say, the server is in a crash loop since I don't know of a way to move my character and I really would like to visit the Outer Lands since this is the next logical step in progression.

Crash report at http://pastebin.com/vx74h30h

Thanks for your time,
Nonantes.

EDIT 29/01:
I tried getting back with a few crashes and seemed to have gotten out of it. I explored the other way for a short while and did not experience any crashes. Got back to overworld.

I'll try and go back into that corner and see if it crashes again. (after a backup of course)

**Comment by Azanor** [comment]
According to the crashlog it looks like it might have been some sort of vanilla bug. I don't see anything TC related. Closing this for now, but let me know if this happens again.
