### ISSUE TITLE
thaumcraft 4 - fatal error occoured connection terminated

### ISSUE THREAD

**Issue by johnfg12** [Azanor/thaumcraft-5#341]
@Slind14 @bookerthegeek @sirwilli on the Civilization modpack we are having huge issues https://mineyourmind.net/forum/threads/civilization-new-social-mym-original-by-krhymez.14454/

on the server we are having larges issues for example when putting a aspect research on a research note it give us a fata error this also happens with changing wand focuses from what i have heard this is not createing log lines about the problem either if someone e could help it would be greatly apprcated i cant live this out thaumcraft thanks johnfg12

**Comment by Slind14** [comment]
booker is already looking into it and trying to find out the cause. We know that it is save data related as with a fresh world those issues don't exist.

**Comment by bookerthegeek** [comment]
https://gist.github.com/bookerthegeek/b974977209b7c6c2de6e

This is the only thing I can find

**Comment by Slind14** [comment]
com.rwtema.extrautils.item.ItemLawSword.attackEntity

**Comment by Azanor** [comment]
modpack specific + tc 4 = not my problem
