### ISSUE TITLE
Thaumcraft 5 problem

### ISSUE THREAD

**Issue by MrElmar** [Azanor/thaumcraft-5#342]
Hello.
I use Mincraft 1.8.9, Forge 11.51.1.1722 and Thaumcraft 5.1.
Forge gives an error. Reports that can not load Thaumcraft mod. [Forge 1.8.9 (2016-01-31).log.txt](https://github.com/Azanor/thaumcraft-5/files/111028/Forge.1.8.9.2016-01-31.log.txt)
I tried use Mincraft 1.8 and Thaumcraft 5.0 and it didn't work.
Only Mincraft 1.7.10 and Thaumcraft 4.2.3 work.

Windows 10, Java 1.8(71)

Please help me :(

**Comment by Azanor** [comment]
There is a thaumcraft config option to turn off shaders. That might solve your problem.
