### ISSUE TITLE
Craftable slimeballs

### ISSUE THREAD

**Issue by DanielAKAKing** [Azanor/thaumcraft-5#347]
Great and mighty Azanor,

It would be nice if there would be an entropic processing way to create slimeballs, ofcourse you already made a duplication version of it but it is just so hard to get a slimeball in the first place, while it is still used in some of the coolest recipes. 

Daniël

**Comment by Azanor** [comment]
That is sort of the point though. It is hard to get. It is a balancing part of the recipe and it anyway doesn't make much sense as an entropic recipe.
