### ISSUE TITLE
Project E Crash

### ISSUE THREAD

**Issue by drago15243** [Azanor/thaumcraft-5#35]
I get a crash with thaumcraft when project e is also on.

http://pastebin.com/uYQkZib3

Has something to do with rm armor I think, any way to solve this without removing it?

**Comment by Shadows-of-Fire** [comment]
ProjectE is running an outdated Thaumcraft API. RM and Gem armors integrate goggles of revealing.

**Comment by Shadows-of-Fire** [comment]
Update ProjectE 1.8 to V1.1.1
Bug is fixed.

**Comment by drago15243** [comment]
thanks =D
