### ISSUE TITLE
Can't craft any of the face plates or the goggles for thaumium fortress armor 

### ISSUE THREAD

**Issue by Dune2959** [Azanor/thaumcraft-5#354]
I'm using thaumcraft 5 v5.1.4 and it wont allow me to start the infusion process i believe the crafting recipe is bugged/incorrect and is asking for the product as the component, in the end not making any of the face plates and the goggles or revealing available for the fortress armor.

**Comment by yamahito** [comment]
Me too in both v5.1.4 and v5.1.5

**Comment by Scorch-Mechanic** [comment]
Are either of you using JEI Addons? If so, remove it and try again. JEI Addons is a known cause of this bug.

**Comment by Azanor** [comment]
Yup, JEI addons related.

**Comment by yamahito** [comment]
Yup, fixed it for me!

**Comment by Dune2959** [comment]
Thanks guys
