### ISSUE TITLE
piston crashing

### ISSUE THREAD

**Issue by scoobvie** [Azanor/thaumcraft-5#36]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8-5.0.1.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.139-universal.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 11/2/15 4:38 AM
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at net.minecraft.client.renderer.tileentity.TileEntityPistonRenderer.func_178461_a(SourceFile:59)
	at net.minecraft.client.renderer.tileentity.TileEntityPistonRenderer.func_180535_a(SourceFile:23)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(SourceFile:114)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(SourceFile:102)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:655)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1297)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1210)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1035)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityPistonRenderer.func_178461_a(SourceFile:59)
	at net.minecraft.client.renderer.tileentity.TileEntityPistonRenderer.func_180535_a(SourceFile:23)

-- Block Entity Details --
Details:
	Name: Piston // net.minecraft.tileentity.TileEntityPiston
	Block type: ID #36 (tile.null // net.minecraft.block.BlockPistonMoving)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (540,64,165), Chunk: (at 12,4,5 in 33,10; contains blocks 528,0,160 to 543,255,175), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Actual block type: ID #36 (tile.null // net.minecraft.block.BlockPistonMoving)
	Actual block data value: 5 / 0x5 / 0b0101
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(SourceFile:114)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(SourceFile:102)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:655)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1297)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1210)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Scooby4440'/346, l='MpServer', x=541.23, y=65.19, z=166.46]]
	Chunk stats: MultiplayerChunkCache: 422, 422
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 224.00,64.00,256.00 - World: (224,64,256), Chunk: (at 0,4,0 in 14,16; contains blocks 224,0,256 to 239,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 70782 game time, 70782 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 172 total; [EntityChicken['Chicken'/514, l='MpServer', x=463.50, y=72.00, z=143.50], EntitySkeleton['Skeleton'/518, l='MpServer', x=620.28, y=66.00, z=235.16], EntityAuraNode['Aura Node'/520, l='MpServer', x=643.50, y=71.50, z=283.50], EntitySheep['Sheep'/537, l='MpServer', x=465.34, y=66.00, z=236.81], EntitySkeleton['Skeleton'/540, l='MpServer', x=590.50, y=64.00, z=189.50], EntityTaintacle['Taintacle'/544, l='MpServer', x=591.50, y=64.00, z=196.50], EntityRabbit['Rabbit'/546, l='MpServer', x=583.09, y=63.00, z=240.41], EntityRabbit['Rabbit'/547, l='MpServer', x=594.13, y=68.00, z=243.47], EntityItem['item.item.seeds'/554, l='MpServer', x=597.16, y=65.00, z=225.53], EntityAuraNode['Aura Node'/561, l='MpServer', x=447.50, y=66.50, z=194.50], EntitySkeleton['Skeleton'/563, l='MpServer', x=499.50, y=64.00, z=128.50], EntityZombie['Zombie'/572, l='MpServer', x=506.50, y=64.00, z=126.50], EntityBat['Bat'/579, l='MpServer', x=506.79, y=39.02, z=116.46], EntityBat['Bat'/580, l='MpServer', x=481.84, y=22.84, z=131.32], EntityBat['Bat'/581, l='MpServer', x=524.25, y=15.00, z=166.50], EntityBat['Bat'/583, l='MpServer', x=497.46, y=48.86, z=136.81], EntityBat['Bat'/584, l='MpServer', x=499.03, y=44.88, z=125.22], EntityAuraNode['Aura Node'/329, l='MpServer', x=408.50, y=74.50, z=130.50], EntityBat['Bat'/590, l='MpServer', x=510.41, y=17.39, z=204.03], EntityBat['Bat'/594, l='MpServer', x=606.61, y=17.24, z=197.90], EntityPlayerSP['Scooby4440'/346, l='MpServer', x=541.23, y=65.19, z=166.46], EntityCreeper['Creeper'/348, l='MpServer', x=530.50, y=13.00, z=168.50], EntityItem['item.item.seeds'/349, l='MpServer', x=543.06, y=64.00, z=164.16], EntityZombie['Zombie'/350, l='MpServer', x=540.06, y=64.00, z=174.41], EntitySkeleton['Skeleton'/351, l='MpServer', x=543.00, y=64.00, z=161.41], EntityItem['item.tile.dirt.default'/352, l='MpServer', x=525.13, y=62.00, z=166.88], EntityItem['item.tile.dirt.default'/353, l='MpServer', x=525.50, y=62.00, z=160.88], EntityItem['item.tile.dirt.default'/354, l='MpServer', x=525.13, y=62.00, z=163.34], EntityItem['item.tile.dirt.default'/355, l='MpServer', x=525.13, y=62.00, z=164.56], EntityItem['item.tile.dirt.default'/356, l='MpServer', x=525.88, y=62.00, z=161.63], EntitySheep['Sheep'/357, l='MpServer', x=520.06, y=64.00, z=171.16], EntityItem['item.tile.dirt.default'/358, l='MpServer', x=536.84, y=62.00, z=158.13], EntityItem['item.tile.dirt.default'/359, l='MpServer', x=538.88, y=63.00, z=158.88], EntityItem['item.tile.dirt.default'/360, l='MpServer', x=537.97, y=63.00, z=158.88], EntitySheep['Sheep'/361, l='MpServer', x=527.97, y=63.00, z=157.00], EntityAuraNode['Aura Node'/362, l='MpServer', x=550.50, y=33.50, z=166.50], EntityXPOrb['Experience Orb'/363, l='MpServer', x=558.44, y=63.00, z=173.44], EntityXPOrb['Experience Orb'/364, l='MpServer', x=557.34, y=63.00, z=172.53], EntityXPOrb['Experience Orb'/365, l='MpServer', x=559.91, y=63.00, z=172.75], EntityItem['item.tile.doublePlant.sunflower'/366, l='MpServer', x=557.72, y=63.00, z=171.44], EntityXPOrb['Experience Orb'/367, l='MpServer', x=559.28, y=63.00, z=168.38], EntityItem['item.item.tainted.slime'/368, l='MpServer', x=558.84, y=63.00, z=171.34], EntityCreeper['Creeper'/1392, l='MpServer', x=498.50, y=23.00, z=134.50], EntityItem['item.tile.doublePlant.sunflower'/369, l='MpServer', x=544.09, y=64.00, z=164.97], EntityZombie['Zombie'/881, l='MpServer', x=504.69, y=64.00, z=92.28], EntityZombie['Zombie'/370, l='MpServer', x=549.50, y=64.00, z=161.50], EntityItem['item.item.seeds'/371, l='MpServer', x=543.59, y=64.00, z=191.31], EntityItem['item.item.seeds'/372, l='MpServer', x=541.38, y=65.05, z=187.47], EntityItem['item.item.seeds'/373, l='MpServer', x=541.31, y=64.00, z=191.59], EntityItem['item.item.seeds'/374, l='MpServer', x=542.50, y=65.00, z=189.31], EntitySpider['Spider'/375, l='MpServer', x=525.97, y=63.00, z=174.63], EntityItem['item.tile.dirt.default'/376, l='MpServer', x=516.59, y=61.00, z=158.13], EntityItem['item.tile.dirt.default'/377, l='MpServer', x=514.13, y=61.00, z=158.13], EntityItem['item.tile.dirt.default'/378, l='MpServer', x=514.97, y=61.00, z=158.13], EntityItem['item.tile.sand.default'/379, l='MpServer', x=516.28, y=61.00, z=158.13], EntityZombie['Zombie'/380, l='MpServer', x=548.50, y=23.00, z=156.50], EntityCreeper['Creeper'/381, l='MpServer', x=544.94, y=64.00, z=155.38], EntityCreeper['Creeper'/382, l='MpServer', x=547.50, y=64.00, z=153.50], EntityXPOrb['Experience Orb'/383, l='MpServer', x=558.47, y=63.00, z=176.66], EntitySheep['Sheep'/384, l='MpServer', x=557.53, y=52.00, z=193.75], EntityItem['item.item.seeds'/386, l='MpServer', x=546.63, y=65.00, z=188.53], EntitySkeleton['Skeleton'/388, l='MpServer', x=504.38, y=63.00, z=160.81], EntityItem['item.item.seeds'/389, l='MpServer', x=568.31, y=62.00, z=167.88], EntityItem['item.tile.doublePlant.sunflower'/390, l='MpServer', x=540.44, y=64.00, z=192.59], EntitySheep['Sheep'/391, l='MpServer', x=512.06, y=63.00, z=200.22], EntitySkeleton['Skeleton'/392, l='MpServer', x=516.50, y=64.00, z=133.50], EntityCreeper['Creeper'/393, l='MpServer', x=556.44, y=29.00, z=138.44], EntityZombie['Zombie'/394, l='MpServer', x=553.41, y=29.00, z=139.41], EntityEldritchGuardian['Eldritch Guardian'/395, l='MpServer', x=557.59, y=51.00, z=191.23], EntityTurretBasic['Automated Crossbow'/396, l='MpServer', x=572.19, y=63.03, z=180.97], EntityTaintacle['Taintacle'/397, l='MpServer', x=562.50, y=64.00, z=191.50], EntityTurretFocus['Autocaster'/398, l='MpServer', x=574.50, y=67.00, z=182.50], EntityTurretFocus['Autocaster'/399, l='MpServer', x=568.50, y=68.00, z=189.50], EntitySheep['Sheep'/400, l='MpServer', x=573.50, y=64.00, z=181.59], EntitySkeleton['Skeleton'/401, l='MpServer', x=548.50, y=53.00, z=205.50], EntityItem['item.item.seeds'/403, l='MpServer', x=554.94, y=67.00, z=207.28], EntityItem['item.item.seeds'/404, l='MpServer', x=551.00, y=68.00, z=204.91], EntityBat['Bat'/405, l='MpServer', x=496.25, y=36.06, z=140.22], EntityBat['Bat'/406, l='MpServer', x=498.25, y=38.19, z=128.23], EntityZombie['Zombie'/407, l='MpServer', x=504.41, y=64.00, z=134.34], EntityTurretFocus['Autocaster'/408, l='MpServer', x=569.50, y=67.00, z=205.50], EntityTurretBasic['Automated Crossbow'/409, l='MpServer', x=572.69, y=65.00, z=197.97], EntityCreeper['Creeper'/410, l='MpServer', x=495.50, y=64.00, z=166.50], EntityZombie['Zombie'/411, l='MpServer', x=542.53, y=16.00, z=113.94], EntityXPOrb['Experience Orb'/412, l='MpServer', x=582.97, y=60.00, z=162.75], EntityXPOrb['Experience Orb'/413, l='MpServer', x=583.13, y=60.00, z=163.56], EntityZombie['Zombie'/414, l='MpServer', x=588.22, y=62.19, z=169.09], EntityXPOrb['Experience Orb'/415, l='MpServer', x=582.25, y=60.00, z=163.34], EntityItem['item.item.spiderEye'/416, l='MpServer', x=581.44, y=60.00, z=163.84], EntityBat['Bat'/417, l='MpServer', x=528.73, y=53.88, z=223.45], EntitySheep['Sheep'/418, l='MpServer', x=542.13, y=69.00, z=218.03], EntitySheep['Sheep'/419, l='MpServer', x=540.31, y=69.00, z=217.41], EntitySheep['Sheep'/420, l='MpServer', x=512.84, y=67.00, z=208.03], EntityZombie['Zombie'/421, l='MpServer', x=515.50, y=68.00, z=222.50], EntityCreeper['Creeper'/422, l='MpServer', x=514.50, y=68.00, z=214.50], EntityCreeper['Creeper'/423, l='MpServer', x=518.50, y=68.00, z=213.50], EntitySkeleton['Skeleton'/424, l='MpServer', x=544.50, y=15.00, z=116.50], EntityCreeper['Creeper'/425, l='MpServer', x=553.50, y=64.00, z=117.50], EntityCreeper['Creeper'/426, l='MpServer', x=554.50, y=64.00, z=119.50], EntityItem['item.tile.doublePlant.sunflower'/427, l='MpServer', x=582.31, y=63.00, z=180.00], EntityItem['item.item.wispy_essence'/428, l='MpServer', x=576.31, y=63.00, z=178.38], EntityItem['item.item.shard.flux'/429, l='MpServer', x=587.22, y=64.00, z=185.44], EntityTurretFocus['Autocaster'/430, l='MpServer', x=578.50, y=64.00, z=187.50], EntityItem['item.item.shard.water'/431, l='MpServer', x=583.88, y=64.00, z=185.84], EntityItem['item.item.shard.air'/432, l='MpServer', x=582.25, y=64.00, z=187.53], EntitySheep['Sheep'/433, l='MpServer', x=550.78, y=67.00, z=215.09], EntitySheep['Sheep'/434, l='MpServer', x=547.56, y=68.00, z=222.00], EntityItem['item.tile.doublePlant.sunflower'/435, l='MpServer', x=549.75, y=68.00, z=223.44], EntitySheep['Sheep'/436, l='MpServer', x=547.69, y=68.00, z=219.91], EntitySheep['Sheep'/437, l='MpServer', x=506.84, y=68.00, z=212.19], EntityCreeper['Creeper'/438, l='MpServer', x=487.50, y=64.00, z=139.50], EntityCreeper['Creeper'/439, l='MpServer', x=509.16, y=13.00, z=112.16], EntitySkeleton['Skeleton'/440, l='MpServer', x=508.16, y=31.00, z=116.44], EntitySkeleton['Skeleton'/441, l='MpServer', x=501.50, y=33.00, z=122.50], EntitySheep['Sheep'/442, l='MpServer', x=496.16, y=64.00, z=113.16], EntitySheep['Sheep'/443, l='MpServer', x=500.00, y=64.00, z=116.69], EntitySheep['Sheep'/444, l='MpServer', x=504.06, y=64.00, z=119.84], EntityThaumicSlime['Thaumic Slime'/445, l='MpServer', x=578.50, y=63.00, z=206.47], EntityAuraNode['Aura Node'/701, l='MpServer', x=681.50, y=76.50, z=165.50], EntityItem['item.item.wispy_essence'/446, l='MpServer', x=576.53, y=65.00, z=199.53], EntityItem['item.tile.doublePlant.sunflower'/447, l='MpServer', x=587.97, y=64.00, z=193.19], EntityItem['item.item.wispy_essence'/448, l='MpServer', x=580.88, y=65.00, z=200.44], EntityItem['item.tile.doublePlant.sunflower'/449, l='MpServer', x=577.53, y=66.00, z=201.25], EntityItem['item.item.wispy_essence'/450, l='MpServer', x=573.31, y=60.00, z=209.91], EntityItem['item.item.seeds'/451, l='MpServer', x=566.91, y=67.00, z=211.28], EntityItem['item.item.seeds'/452, l='MpServer', x=568.66, y=67.00, z=210.22], EntityItem['item.item.seeds'/453, l='MpServer', x=568.44, y=65.00, z=221.66], EntityItem['item.tile.doublePlant.sunflower'/454, l='MpServer', x=567.53, y=66.00, z=214.94], EntitySheep['Sheep'/455, l='MpServer', x=538.13, y=69.00, z=227.19], EntityZombie['Zombie'/456, l='MpServer', x=531.31, y=69.00, z=223.88], EntityCreeper['Creeper'/457, l='MpServer', x=515.50, y=48.00, z=233.50], EntityBat['Bat'/458, l='MpServer', x=525.41, y=46.24, z=226.45], EntityBat['Bat'/459, l='MpServer', x=517.26, y=49.02, z=232.38], EntityBat['Bat'/460, l='MpServer', x=506.47, y=49.92, z=221.40], EntityCreeper['Creeper'/461, l='MpServer', x=514.50, y=48.00, z=232.50], EntityCreeper['Creeper'/462, l='MpServer', x=514.50, y=48.00, z=229.50], EntityZombie['Zombie'/463, l='MpServer', x=524.50, y=69.00, z=228.50], EntityZombie['Zombie'/464, l='MpServer', x=529.06, y=69.00, z=226.66], EntityChicken['Chicken'/465, l='MpServer', x=464.50, y=71.00, z=146.50], EntityChicken['Chicken'/466, l='MpServer', x=465.34, y=66.00, z=145.50], EntitySkeleton['Skeleton'/468, l='MpServer', x=512.50, y=63.00, z=106.50], EntityCreeper['Creeper'/469, l='MpServer', x=557.50, y=32.00, z=110.50], EntityBat['Bat'/470, l='MpServer', x=555.09, y=33.10, z=99.31], EntityAuraNode['Aura Node'/471, l='MpServer', x=603.72, y=63.56, z=181.88], EntityItem['item.tile.doublePlant.sunflower'/472, l='MpServer', x=601.22, y=64.00, z=186.00], EntityItem['item.tile.doublePlant.sunflower'/473, l='MpServer', x=602.00, y=64.00, z=187.03], EntityWisp['Wisp'/474, l='MpServer', x=601.91, y=68.36, z=191.89], EntityItem['item.tile.doublePlant.sunflower'/475, l='MpServer', x=551.09, y=68.00, z=227.66], EntityItem['item.item.wispy_essence'/476, l='MpServer', x=577.19, y=62.00, z=209.88], EntityItem['item.item.wispy_essence'/477, l='MpServer', x=580.63, y=63.00, z=212.69], EntityZombie['Zombie'/478, l='MpServer', x=508.50, y=68.00, z=234.50], EntityPig['Pig'/479, l='MpServer', x=470.97, y=63.00, z=139.44], EntityChicken['Chicken'/480, l='MpServer', x=471.34, y=63.00, z=140.59], EntityPig['Pig'/481, l='MpServer', x=468.38, y=64.00, z=134.78], EntityAuraNode['Aura Node'/482, l='MpServer', x=475.50, y=64.50, z=139.50], EntityPig['Pig'/483, l='MpServer', x=467.50, y=70.00, z=130.50], EntitySheep['Sheep'/484, l='MpServer', x=498.41, y=64.00, z=106.31], EntityBat['Bat'/485, l='MpServer', x=561.19, y=33.03, z=107.05], EntityItem['item.tile.doublePlant.sunflower'/486, l='MpServer', x=597.56, y=63.00, z=195.47], EntityItem['item.tile.doublePlant.sunflower'/487, l='MpServer', x=597.31, y=64.00, z=192.59], EntitySkeleton['Skeleton'/488, l='MpServer', x=489.78, y=68.00, z=238.16], EntityZombie['Zombie'/489, l='MpServer', x=487.50, y=56.00, z=110.50], EntitySkeleton['Skeleton'/490, l='MpServer', x=612.50, y=28.00, z=166.50], EntityItem['item.item.seeds'/492, l='MpServer', x=597.63, y=63.00, z=217.44], EntityItem['item.item.seeds'/493, l='MpServer', x=598.69, y=63.00, z=217.81], EntityRabbit['Rabbit'/494, l='MpServer', x=582.91, y=63.00, z=239.41], EntitySheep['Sheep'/501, l='MpServer', x=585.76, y=67.00, z=87.51], EntitySheep['Sheep'/502, l='MpServer', x=582.44, y=68.00, z=87.44], EntitySheep['Sheep'/503, l='MpServer', x=578.44, y=69.00, z=94.17], EntitySheep['Sheep'/504, l='MpServer', x=588.60, y=66.01, z=88.90], EntitySheep['Sheep'/506, l='MpServer', x=489.56, y=68.00, z=242.53], EntitySheep['Sheep'/508, l='MpServer', x=490.94, y=68.00, z=241.00]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2503)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 245700288 bytes (234 MB) / 629964800 bytes (600 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1521 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1521.jar) 
	UCHIJAAAA	Forge{11.14.3.1521} [Minecraft Forge] (forge-1.8-11.14.3.1521.jar) 
	UCHIJAAAA	Baubles{1.1.1.0} [Baubles] (Baubles-1.8-1.1.1.0.jar) 
	UCHIJAAAA	Thaumcraft{5.0.1} [Thaumcraft] (Thaumcraft-1.8-5.0.1.jar) 
	UCHIJAAAA	thaumictinkerer{${version}} [Thaumic Tinkerer] (ThaumicTinkerer-3.0-1.8-166.jar) 
	Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8-5.0.1.jar)
  
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.139-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 358.50' Renderer: 'GeForce GTX 650 Ti/PCIe/SSE2'
	Launched Version: 1.8-forge1.8-11.14.3.1521
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 650 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 358.50, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)

not sure if its thaumcraft or thaumictinkerer causing the crash, im not really sure how to read a crash report past a mod not loading correctly :P
Game crashes when i turn a sticky piston or normal piston on.
tried doing it on a newly created world with the same mods and no crash.

**Comment by Azanor** [comment]
This seems to be a vanilla problem - neither TC or TT are mentioned anywhere in the crashlog.
