### ISSUE TITLE
Game (crashes?) while trading with Pech

### ISSUE THREAD

**Issue by Reykja** [Azanor/thaumcraft-5#360]
I've got a pech thaumaturge trapped in a fenced area, and I've started trading with him. I traded most of a stack of gold coins to him, for which he gave me a number of items. I then started trading common urns and common treasure bags to him. After just a few trades, I'm not longer able to click the dice button. In fact, I lose a great deal of functionality within the game. I can exit the trading screen with the Pech, but once I do I can no longer get in again. I also cannot drop items with my drop-item hot key. I can drop items by click on them in my inventory and then clicking outside the inventory window, but they do not appear on the ground afterward. I can use my axe of the stream to pull items toward me, but I cannot pick any items up. I cannot open chests or attack mobs. Mobs do not move, but the day-night cycle continues. I can break blocks by left-clicking them, but not with my excavation focus. When I click "save and quit to title", the game becomes non-responsive, and I am forced to end the task using task manager.

journeymap-1.8.8-5.1.3b1-unlimited
OptiFine_1.8.9_HD_U_H2
RoguelikeDungeons-1.8.9-1.4.5
Thaumcraft-1.8.9-5.1.5
ThaumicInfusion-1.8.9-4.76
XRay-4.5
Baubles-1.8.9-1.1.3.0

[game output.txt](https://github.com/Azanor/thaumcraft-5/files/116563/game.output.txt)
[launcher log.txt](https://github.com/Azanor/thaumcraft-5/files/116562/launcher.log.txt)

**Comment by DarcClan** [comment]
I've had this happen as well, i think the game crashes when your going to get a pech curse as the trade, i've had the game crash only on trades where that was the likely outcome, basically i've gotten any other trades with him except that, seems the only way to get the pech curse foci is to kill them and hope they drop it

**Comment by Azanorashit** [comment]
I third this, while trading diamonds to a mage pech the game will soft crash, nothing drops from blocks you break, you cant interact with any entities, for the most part, everything int he game except for you stops dead in its tracks. MultiMC's log has nothing about it though.

**Comment by DarcClan** [comment]
have either of you gotten this to happen with the pech scavengers (ones with bows)? i haven't gotten many to spawn so i haven't tried doing much trading with them, seems that foragers are fine though, no soft crashing with them
