### ISSUE TITLE
FPS drop when essentia flows

### ISSUE THREAD

**Issue by Whosphoro** [Azanor/thaumcraft-5#361]
I have been playing TC5 for a month with FPS floating between 60 and 54, which i consider somewhat normal. Today, after switching from 5.1.4 to 5.1.5, I noted that the FPS is dropping to around 45 when essentia flows from smeltery to jars and from jars to thaumatorium.
Setting "B:shaders=" to false or true does not help.
Since 5.1.5 brings a new essentia FX, maybe it is related?

I'm using Forge 1722, JEI, JEI AddOns, Roguelike Dungeons and Chisel & Bits, all up to date.

**Comment by Azanor** [comment]
How big a fps drop?

**Comment by Whosphoro** [comment]
Hi Azanor.
After running some tests, my conclusion is that I had too many item frames on the walls.
The flowing essentia is not causing FPS drops, so I think that is really a non issue.

**Comment by Azanor** [comment]
Excellent.

**Comment by ThePB** [comment]
http://vignette2.wikia.nocookie.net/familyguy/images/8/8d/Burns-excellent.gif/revision/latest?cb=20140924214801

... Sorry, i couldn't resist.

**Comment by Azanor** [comment]
lol
