### ISSUE TITLE
Protection Enchantments (and maybe armor points) are applied to damage absorbed by Runic Shielding

### ISSUE THREAD

**Issue by Scorch-Mechanic** [Azanor/thaumcraft-5#362]
Expected result: Damage absorbed by Runic Shielding is unaffected by Protection enchantments and Armor Points.
Actual result: Wearing full thaumium fortress armor with Protection Enchantments under my Runic Shielding makes me almost completely impervious to mob attacks. (I'm also almost completely impervious without the runic shielding, but that's not the issue at hand here).

Forge 11.14.1.1726, Thaumcraft 5.1.5. Difficulty is Normal.
I've got full thaumium fortress armor, with Protection IV on two of the pieces, plus Blast Protection IV. I have an amulet of Emergency Shielding, a Kinetic Belt, and two rings of Charging, with all the concomitant points of Runic Shielding those baubles normally provide. I have not added any levels of Runic Shielding to any baubles or pieces of armor.

With my armor on, I can stand on a creeper and I'll lose at most one point of runic shielding (half a heart). If I remove all my armor and stand next to a creeper, I lose all my shielding and about half my health. 

Interestingly, it seems that effects triggered by losing all runic shielding will sometimes, but not always, activate when a hit (explosion, strike from zombie pigman) /should/ remove all my runic shielding. Even if it doesn't actually happen because damage reduction applies and causes me to take less (or even no) runic shielding damage at all. For example, when a creeper explodes next to me my kinetic belt will sometimes fire. Just as an experiment I just removed only my amulet of Emergency Shielding and stood next to a creeper. Result: Zero damage to my Runic Shielding.

Other mods:
Chameleon 1.8.9-0.2.1
Durability Show 2.1.2
Inventory Tweaks 1.60-beta-29
JEI 2.22.4.106
Journeymap 1.8.8-5.1.3
JWIN 0.11.1
Roguelike Dungeons 1.8.9-1.4.5
Storage Drawers 1.8.9-2.2.1
Waila 1.6.0-B3_1.8.8
Wawla 1.4.7-1.8+

**Comment by Azanor** [comment]
Runic shielding now uses completely vanilla mechanics to prevent compatibility issues that cropped up in previous versions. Runic shielding now just adds the same sort of bonus 'hearts' you get from golden apples and such. It is basically just extra hit points so yes, armor will get calculated before runic shielding is subtracted.
