### ISSUE TITLE
(1.8.9) (Thaumcraft 5.1.5) Infusing Earth Crystals for placement causes infinite inventory filling bug

### ISSUE THREAD

**Issue by DarcClan** [Azanor/thaumcraft-5#364]
Issue is that if you infuse earth crystal (have not tried the others, assume they also cause this) with salus mundus and a seed to get the placeable version, if you recieve it from the altar your inventory rapidly fills with earth crystals with black/purple box texture, and presists after reloading world (singleplayer) or re-logging back in (multiplayer), also if you try to place them they can be placed but the stack immeditally fills back to 64, dropping them causes them to not be able to be picked up again, and regardless if you have nothing in your inventory you will recieve more crystals, (see below image links for more details)

http://imgur.com/a/waSXq

**Comment by Azanor** [comment]
Which version of forge?
