### ISSUE TITLE
Golems lock up when planting saplings with a Use seal on the ground but not on the side/top of the sapling block space

### ISSUE THREAD

**Issue by OnmyojiOmn** [Azanor/thaumcraft-5#366]
Version 5.1.5

If the seal is on the ground (i.e. the top of block below the sapling block space), the golem will plant one sapling and then repeatedly attempt to use any remaining saplings it's holding in the same spot and lock up. If the seal is placed on the top or side of the block space where the sapling will go and "Click empty air" is checked, the golem will plant one sapling and move on.

**Comment by Azanor** [comment]
This is exactly how it is supposed to work. The golem will just keep trying to use saplings in the first instance since there is nothing telling it to stop. It stops in the second instance since once the sapling is planted it is no longer empty air.
