### ISSUE TITLE
Unlimited Essencia Bug

### ISSUE THREAD

**Issue by alfa38** [Azanor/thaumcraft-5#37]
Using basic essencia smeltry.

Seems like sometimes smelting a golden sword in basic smeltery will result in infinte amount of last drawn essencia. This happens about 30% of time. 

Same with golden pickaxe, resulting in infinite instrumentum essencia, or herba essencia if instr gone into flux. 

Bug seems to appear at random when smelting vanilla items. Will test for thaumcraft items (so far not happened for Warded Jars and Gold cappen Wand)

Bug appears then flux is generated instead of point of essencia. (seems to me like this)

UPD. Essencia is drawn even after game is closed and continued. Until u smelt another item in that smeltery.

Thaumcraft 5.0.1, Forge 1543 and 1521, Java 1.8.0_45.

**Comment by davue** [comment]
I was also experiencing this bug and I could only stop it by destroying the Essentia Smeltery.
But I still don't know what triggers it.
