### ISSUE TITLE
Cannot smelt items with over 50 ct aspects

### ISSUE THREAD

**Issue by Reykja** [Azanor/thaumcraft-5#370]
It is not possible to smelt items in a smeltery with over 50 aspects. While there aren't very many items that would give over 50, enchanted diamond armor is almost always over 50, making them unsmeltable.

Since the smeltery can only hold 50 aspects worth of slurry, I suspect that this has to do with the code that stops the smeltery from starting to smelt an item unless there is enough room in the slurry holder for all of the aspects that will be released by that item. 

I'd be more than happy to have a way to apply some sort of upgrade or enchantment to a smeltery to allow it to hold more than 50 aspects worth of slurry. Perhaps an enhanced version of the void metal smeltery? If that doesn't sound like your preferred solution, the easiest one is probably to simply increase the size of the slurry holder for some, or all, of the various smelteries.

To give you an idea of what might be needed, the item I have that currently has the most aspects is a FP IV, Repair I, Runic Shield +5 Void Thaumaturge Robe that, if I could smelt it, would give 102 total aspects worth of slurry. In the diamond category, my Prot IV, Unbreaking III Diamond chestplate has 66 total aspects to give if smelted. Even an unenchanted diamond chestplate has 52.

I suppose that if you wanted to be more realistic (and evil?), trying to smelt an item that had more aspects than the max a smeltery could handle could just release the rest as flux...

**Comment by Azanor** [comment]
The 50 aspect limit is intended. I might revise this in the future, but not at the moment.
