### ISSUE TITLE
Op bypass

### ISSUE THREAD

**Issue by Bennyboy1695** [Azanor/thaumcraft-5#371]
Was wondering/hoping if it would be possible to add if its not already added, the ability for ops to be able to bypass arcane doors and anything similar. Not a big need as with plugins you can get the /thru command, but i believe it would be super helpful

**Comment by Mexahoid** [comment]
Why do OPs need such thing?

**Comment by MalkContent** [comment]
... arcane door? no such thing in TC 5 (as of yet at least)
you might have an addon or be talking about TC 4, which is no longer supported here
