### ISSUE TITLE
Nerf Sugarcane Lucrum <-> Pech trading

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#373]
Atm it's extremely cheap trading. I.e. With even a moderate sugar cane farm and a captured (nametagged) pech forager you don't ever have to go mining for iron or gold again.

**Comment by MalkContent** [comment]
awesome!
I liked the idea of "wanna have some caaandy?" but it was a bit op :)
maybe it could be kept to get items they collected from the ground back

**Comment by Zsashas** [comment]
Wait, since when does Sugarcane have Lucrum?

**Comment by MalkContent** [comment]
Since tc5. There's no fames anymore and lucrum's the next best thing. Also it's called Desidarium now. Only noticing right now that I failed the name again :|

**Comment by Plystire** [comment]
To clarify: SUGAR has Desiderium, not sugarcane which has Herba, Aqua, and Aer.

**Comment by Zsashas** [comment]
That's the problem with removing aspects, especially so many. The remaining ones have to be stretched even more.

**Comment by MalkContent** [comment]
O, right... sugar ~~cane~~ ... oops.  
And meh. The only problem here is that desiderium being split into lucrum and fames made it easy to spot valuable stuff, which was good for pech. Fames got replaced by victus, really, which makes sense for food.
It's not like it's otherwise hard to trade with pech for cheap, just that sugar was a bit of a nuke.
Issue's marked solved and if you wanna discuss aspects (I, too, miss tempestas), the forum or irc is probably a better place.
