### ISSUE TITLE
Trading with a Pech Mage can halt the game

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#376]
Mods: TC, JEI, OpenComputers. All up to date, Forge x1726
Nothing in the logs about it, game just halts. You can close the Pech Trading GUI and run around, but not interact with anything. Also can't close the game gracefully.
Trading with the two other pech didn't cause any issues. The trade that halts the game still completes.
Wild guessing: A bad item, maybe the vis amulet/stone or a bad potion.

**Comment by yamahito** [comment]
I got a second for this, and was wondering if it was a JEI compatibility thing: any idea when the patch will be released (or is it in 5.1.6 and not in the change log)?

**Comment by Azanor** [comment]
It will be in the next patch which should be soon(tm)
