### ISSUE TITLE
Vague awareness of completion without external walkthrough

### ISSUE THREAD

**Issue by Infernalistgamer** [Azanor/thaumcraft-5#38]
Is there any way you might add some indicator of how close we are to finishing each page of the Thaumonomicon? A numerical percentage, or a sigil filling in? It'd be a major help.  Otherwise, we're forced to go outside the game to determine if we're actually done with each page, or whether there are hidden things yet to be unlocked.  Stressful for completionists and those trying to unlock the Kami armor from one of the secondary mods.

**Comment by Quarg** [comment]
I agree that some way to tell whether or not there is something left to find would be nice.

Perhaps make research that is hidden (by requiring scanning etc) be shown on the page as golden question marks, like the ones that appear around things to scan.
