### ISSUE TITLE
[TC 5.1.6] Elemental Arrows cannot be fired

### ISSUE THREAD

**Issue by Plystire** [Azanor/thaumcraft-5#380]
As the title says, plain and simple. Using vanilla bow, none of the elemental arrows can be used.

To clarify, the bow will draw back the arrow, but releasing neither fires the arrow nor consumes one.

**Comment by Azanor** [comment]
Any other mods installed? For me it works perfectly with both the vanilla and bone bow.

**Comment by Plystire** [comment]
At time of writing this issue, no, I had no other mods installed.

Addendum: Retried in creative world... bow works. Changed game mode to Survival, bow no longer works. Hope that helps!

**Comment by Azanor** [comment]
I tested in both creative and survival with vanilla arrows and all the elemental arrows. It still works fine for me. *shrug*

**Comment by MalkContent** [comment]
In survival, if you have elemental arrows, but no vanilla arrows in your inventory, you can pull the vanilla bow back, but on release nothing happens.  
If you have vanilla arrows in addition to your elemental arrows, you can successfully fire the elemental arrows.
Also minor suggestion: atm you can chose the type of elemental arrow you fire by placing the desired type into a slot with a lower id than the others. It would be neat if you could chose to fire vanilla arrows over elemental ones that way, too :)

**Comment by MalkContent** [comment]
also tagging on: elemental arrows are seemingly not affected by punch or power enchantment

**Comment by Azanor** [comment]
So it turns out this is a forge bug. The ArrowLooseEvent in forge only triggers for vanilla bows after a check is done if the player has a vanilla arrow in their inventory. They need to trigger the event before that check is done.

**Comment by Azanor** [comment]
The punch and knockback thing I can fix however.
