### ISSUE TITLE
[TC 5.1.6] Pedestals not near infusion altar can prevent altar from working

### ISSUE THREAD

**Issue by Plystire** [Azanor/thaumcraft-5#381]
I have my infusion altar on the second floor of my lab. I recently came back from a trip with an Ancient Pedestal. I only had one and didn't feel like crafting more, and since only one would offset the symmetry, I decided it would be better off as decoration right inside my front door, holding a single gold coin.

Unfortunately, a short while later I wanted to infuse some items, and the altar would no longer accept any recipes! It just wouldn't start... I then recalled the pedestal downstairs (admittedly, it was fairly close, about 10 or so blocks from the altar, horizontally, though roughly 6-7 blocks below it). Breaking the pedestal downstairs allowed the altar to start working again. (I could have just taken the item off of it, but what good is a pedestal that's not prominently displaying an item? :P)

I'm not saying the altar shouldn't take such pedestals into account, I was actually pleasantly surprised at how far it could reach to find pedestals! Will want to expand my workshop for a fancier altar! However, please make it so random items on nearby pedestals don't effect whether the recipe will go through or not. I don't mind it increasing the instability, just don't let them prevent it from working completely. I do like showing off my items on pedestals and would hate to be restricted in only using them far away from the altar. :)

**Comment by Azanor** [comment]
Unfortunately that is not possible - the items it finds is how it determines the recipe. It has no way of knowing what is a 'random' item and what is important.

**Comment by Plystire** [comment]
Fair enough.  Maybe consider in the future allowing a shift+right-click with wand to "deactivate" pedestals maybe? Then I could have nearby decorative pedestals? :D

Here's hoping anyway xD
