### ISSUE TITLE
Suggestion: Spawn Crystal Shards harvested with a wand on the player

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#382]
Atm they seem to drop inside the crystal clusters block, causing them to fly all over the place, because the cluster is still occupying the space. In my mind it's "careful harvesting" so the /swoosh/ and /zoom/ of the shards past my head feels off.
I of course accept "it's not a bug, it's a feature!", though x)

**Comment by Azanor** [comment]
Good point.
