### ISSUE TITLE
Essence duplication bug (1.8.9)

### ISSUE THREAD

**Issue by meerkqat** [Azanor/thaumcraft-5#386]
Thaumcraft: 5.6.1
Forge: 11.15.1.1722

Whispy and crystallized essence can be duplicated in the following manner: 
Place a hopper in the world and place a chest on top of the hopper. Put one essence in the hopper (or any amount less than a stack really) and any items into the chest on top. The items from the chest will get pulled into the hopper and stack with the essence item - i.e. convert into essence.

**Comment by Azanor** [comment]
This would be a vanilla minecraft bug then - I don't have control over how the hopper handles items.

**Comment by meerkqat** [comment]
Right, after some further testing it seems I was a bit trigger happy with reporting this, it does seem to be a vanilla problem. Funny how I've never come across it before though.

**Comment by Azanor** [comment]
FYI: 
Build 1.8.9-11.15.1.1724:
	fry: Fixed small bug in item extraction code.

Looks like it was a forge issue and it should be solved in 1724 or later.
