### ISSUE TITLE
Request: text size setting, because of Minecraft non-latin characters bad render

### ISSUE THREAD

**Issue by rinart73** [Azanor/thaumcraft-5#388]
Minecraft renders small non-latin symbols very badly. Just can't see the count (count of aspects while the Researching process and in the Thaumonomicon recipes)

Please introduce some text size setting or something else.

No, I can't install another font via resourcepack because then all text doesn't fits borders and then I just  can't read a half of description of recipe of something.

**Comment by ThePB** [comment]
Check your config file...

    # Setting this to true will make the amount text in aspect tags twice as large. Useful for certain resolutions and custom fonts.
    B:large_tag_text=false

This are the droids... well, this should be what you are looking for, right?
