### ISSUE TITLE
[TC 5.1.6] Greatwood tree grows offset from saplings.

### ISSUE THREAD

**Issue by ErdrickXLII** [Azanor/thaumcraft-5#389]
I placed four Greatwood saplings like:
`XX`
`XX`
but the resulting tree ended up looking like:
`XXOO`
`X OO`

(Where 'X' is sapling and 'O' is wood)

**Comment by Azanor** [comment]
All my trees only require one sapling - since it detected the blocks as occupied it probably got offset a bit to fit in that spot.

**Comment by ErdrickXLII** [comment]
Well, now I just feel dumb.
Ok, thanks, sorry for the false report.
