### ISSUE TITLE
Model/Block State loading failure

### ISSUE THREAD

**Issue by Zsashas** [Azanor/thaumcraft-5#390]
Console gives me this during startup:

https://gist.github.com/Zsashas/5046d1c39be8af31b0de

Also 

[10:43:31] [Client thread/ERROR] [FML]: Supressed additional 57 model loading errors for domain thaumcraft

**Comment by Azanor** [comment]
That's normal (sort of). Not all blocks have models and it all gets vomited to the console for some reason. Forge used to handle it more gracefully, but for some reason they just spam the console with errors now.
