### ISSUE TITLE
Iron-Capped Wooden Wand texture broken

### ISSUE THREAD

**Issue by Zsashas** [Azanor/thaumcraft-5#392]
![2016-02-10_13 11 46](https://cloud.githubusercontent.com/assets/6917535/12961951/f9d102a6-cff7-11e5-8093-a3466452f272.png)

**Comment by Azanor** [comment]
When, why, how? More details would be handy.

**Comment by MalkContent** [comment]
I got that one from time to time, too. Can also affect the wand or the focus. Didn't notice a pattern yet :(
Mods: TC, OpenComputers, JEI (no addons)

**Comment by OnmyojiOmn** [comment]
I had this problem too but forgot to post it. It seemed to happen whenever I used a texture pack, even when the pack didn't touch Thaumcraft. Pixel Reality is one of a couple packs I was trying out; can't remember any others. The problem persisted when I disabled the texture pack and I had to restart the client to get it to go away.

**Comment by Zsashas** [comment]
Does Thaumcraft draw from the vanilla textures to crate the wand textures? Seems like it should use it's own instead, if that's the case.

**Comment by Azanor** [comment]
I use my own textures. I have been struggling to duplicate this, but I will take a look.
