### ISSUE TITLE
Can't unfiuse Runic baubles with more runic shielding.

### ISSUE THREAD

**Issue by Azanorashit** [Azanor/thaumcraft-5#395]
Just doesn't work from the looks of it, thaumium fort armor works just fine, the baubles don't, be it specialized like the emergency shielding or just the basic version, they're uninfusable, which they shouldn't be according to the book.

**Comment by MalkContent** [comment]
Tried with a regular ring of runic shielding, it's working.
Did you account for the preexisting level of it's runic shield in the recipe?

**Comment by Azanorashit** [comment]
I did not, since no other mod that does things like this does that, I figured it would be a matter of adding a second set, not increasing its base.

**Comment by MalkContent** [comment]
Says it right there in the thaumonomicon, last paragraph of runic augmentation <3
