### ISSUE TITLE
thaumonicon page texture links

### ISSUE THREAD

**Issue by jochuan** [Azanor/thaumcraft-5#397]
the research page in the thaumonomicon is showing only missing textures as a result of some of the changes in directories since Thaumcraft 4 when you use the pt_BR.lang. others pages probably have the same issue

**Comment by jochuan** [comment]
https://github.com/Azanor/thaumcraft-5/pull/393

**Comment by Azanor** [comment]
Unfortunately I rely on volunteers to do my translations, so until someone steps forward the pt_BR localization will remain completely out of date.

**Comment by Robijnvogel** [comment]
You want to either leave it completely outdated OR have it completely updated?
That sounds fair enough; prevents confusion on what exactly is up-to-date and what is not. 

I now have the same question as [this guy](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292130-thaumcraft-5-1-6-updated-2016-2-4?comment=33669). I will not be continuing to work on the pt_BR.lang. That task is better reserved for a team of Portuguese and Brazilians. I may help with the nl_NL.lang though.

**Comment by jochuan** [comment]
could you at least disable the pt_BR localization until it is fixed ?

**Comment by Azanor** [comment]
I don't have any plans to move the textures anytime soon.
I will remove the pt_BR lang file till someone submits a new one.

**Comment by jochuan** [comment]
thanks for that
