### ISSUE TITLE
No fences/fence gates from tc woods

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#40]
due to the new type-of-wood kind of crafting for fences, tc wooden planks can't be used to craft fences, which is kind of silly

**Comment by Fjolsvin** [comment]
If you're going to make TC wood full-fledged wood, please note the achievement "Get wood" is not fulfilled by chopping TC wood.

**Comment by MalkContent** [comment]
Well they are oredicted wood logs. Probably more forge's job make it trigger on that.
