### ISSUE TITLE
Misplaced flux in Overworld after entering and exiting Outer Lands?

### ISSUE THREAD

**Issue by GWYOG** [Azanor/thaumcraft-5#402]
Using thaumcraft 5.1.6, every time I enter an eldritch portal and then come back, there will be lots of flux in the vinicity of the portal in Overworld.

Here are the graphs of flux shown on thaumic dioptra in both Outer Lands and Overworld. It is clear that little flux is in Outer Lands and huge amounts of flux are in Overworld.
http://imgur.com/a/x9yYs

As far as I know, flux has a chance to occur when it generates Outer Lands' passages, and this is an amount of 500 per cell in default. I roughly measured its amount with a flux sponge, the sum of the flux in Outer Lands and Overworld is around this number. So I doubt the flux may be misplaced in Overworld.

 Is a bug or a feature that I ignored?

**Comment by Azanor** [comment]
Neither opening the portal nor generating the maze creates any flux at all, nor is it supposed to. The fact that the flux seems to be in two distinct spikes like that leads me to think you have a couple of tainted nodes near your portal.

**Comment by GWYOG** [comment]
Nope, I have tried more than twenty portals, all cases showed the same phenomenon: origin Overworld has no flux, but after I entered the portal and came back in about 20 secs(or more), the Overworld has much flux like the image above showing. 
Actually, this weird phenomenon was first discovered by @MrGTout. So it can be reproduced.

As I checked out your DEV Build code, I found that the Outer Lands seem to generates flux when it generates the passage with taintFibre, and this is 5*100=500 per passage by default. According to the rough measurement by the flux sponge, the amount of flux in Outer Lands is much smaller than it should be. So I guess something went wrong.

**Comment by Azanor** [comment]
The amount is correct, but the taint should be added to the outer lands dimension, unless something is going wrong. I'll go take a look.

**Comment by Azanor** [comment]
Oh crap. Wow, I'm amazed this bug has only been discovered now. Turns out I was storing all recharge tickets (which includes flux pollution) in a static variable... I have no idea why. 

This meant that no matter in which world the ticket was added, the first world to process its auras after the ticket was added would grab it. This was usually the overworld, unless the chunk in question was unloaded.

**Comment by Hyxaru** [comment]
Lol I thought it was somewhat intended. Opening such a strong portal might cause some disturbance in the aura, is what I thought.

**Comment by ThePB** [comment]
Oh that's also why someone was having flux outbreaks in the spawn chunks of the overwolrd (that unless i'm completely wrong are always loaded) while producing flux in the nether?

**Comment by Azanor** [comment]
More than likely.
