### ISSUE TITLE
[Suggestion/Bug?] Control Seal: Store

### ISSUE THREAD

**Issue by ReTeYeZ** [Azanor/thaumcraft-5#405]
Not sure if it is intended like that but a golem shouldn't place items in an inventory, with a store seal with an empty white-list rather if the seal is set to black-list and it is empty, imo.
Would help a lot to have better control of where items are supposed and allowed to go.

**Comment by Berserker66** [comment]
For simple setups it would still be useful to default to a working config, so I'd recommend to also change it to an empty blacklist as default when placing.

**Comment by ReTeYeZ** [comment]
I agree.

**Comment by Azanor** [comment]
Turns out I will be doing this anyway, though for performance reasons. Currently allowing an empty white list to count as an empty black list involves lots of extra array traversing which I want to avoid.
