### ISSUE TITLE
[Suggestion] Carefully Crystal Harvest Research

### ISSUE THREAD

**Issue by ReTeYeZ** [Azanor/thaumcraft-5#406]
Similiar to the node tapping research from TC 4 that prevented you from draining nodes completely (with greatwood or better wand) but insted prevents you from harvesting crystals completely with rightclick.

**Comment by Hyxaru** [comment]
Carefully clicking the right amount of times should do the trick. A small internal cooldown before allowing to pluck another shard might be a good q.o.l. upgrade.

**Comment by Azanor** [comment]
Or, you know, don't just mash down the mousebutton.
