### ISSUE TITLE
Adding focus to auto caster

### ISSUE THREAD

**Issue by seanamor** [Azanor/thaumcraft-5#412]
Minecraft Forge: 11.15.1.1732
SpongeForge: DEV
SpongeAPI: 3.1.0-SNAPSHOT-4c0d27c
Minecraft: 1.8.9
SpongeForge

A couple errors listed below first of which:
http://hastebin.com/mexokuqabe.m
Secondly I am not sure if this one is because im in creative, without the proper research to be doing this. But I get an autocaster from creative, then try adding a focus to it, I have tried pech and lightning so far and both add the focus, but crash the server:
http://hastebin.com/okumobehes.avrasm

**Comment by Azanor** [comment]
Those are both sponge related errors - nothing directly TC related in either of them.
