### ISSUE TITLE
2x2 Arcane levitators causes slow descent    

### ISSUE THREAD

**Issue by jrpoints** [Azanor/thaumcraft-5#413]
When you have arcane levitators in a 2x2 and try to descend but are kinda in the middle of two of them or right in the middle of all of them you descend much slower than normal. Guessing not all of them are seeing the shift key is being held so some are going down some going up kinda canceling each other out. 

Edit: Just had an idea, probably WAY to much work for the pay off but if arcane levitators where multi block and would combine into different sizes at maybe a 2x2, 3x3, 5x5 size, so it was just one big stream that would maybe even let you and items go up farther than the 32 of the normal one, for more cost of course, just an idea.

**Comment by Azanor** [comment]
Not something that can be fixed - even when going down the blocks apply a bit of 'push' to the player - just enough to slow them down. Multiple levitators will all apply this push force and it adds up to make you come down much slower.
