### ISSUE TITLE
Scattershot potentially deals very low damage

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#414]
Example:
Get a scatter shot frost focus (any potency), stand in the face of a zombie and release and be amazed that you can deal as little as 1 damage with the magic shotgun.
:/
I think there's a chance of a shard hitting to delete the remaining shards or something along those lines.

**Comment by Azanor** [comment]
MC has a built in timer that ticks down after a mob takes damage - any additional damage is nullified unless it is more than the original damage taken.
The scattershot resets this timer, but not for every shard. The closer you are, the higher the chance a shard gets though - in other words at short range the focus is a lot more effective than at long range, even if it still seems like all shards are hitting at longer ranges.

**Comment by Azanor** [comment]
Having said that, I am playing with the numbers a bit. The chance for no shards to get through at point blank range is a bit high.

**Comment by MalkContent** [comment]
> The scattershot resets this timer, but not for every shard. The closer you are, the lower the chance a shard gets though - this is to prevent the focus from just blowing everything to kingdom come at close range.

So it is not meant as a shotgun and more of barrage weapon now? :c I thought the nerf was that the time between casts was increased to greater than damage immunity time so you couldn't nuke bosses anymore :|
