### ISSUE TITLE
Graphical bugs with Warp Event and Some Items

### ISSUE THREAD

**Issue by JohnnyG21** [Azanor/thaumcraft-5#417]
When the warp event "A sudden and unnatural hunger consumes you" triggers, the screen fades to black until it's over. This happened to me two times and it's dangerous since you can't see anything, unless you are in F1 Camera. 

There is also another graphical bug with some magical tools and objects. When holding on the hand the Thaumometer, Sanity Checker or any wand, this happens: 
![2016-02-16_23 18 34](https://cloud.githubusercontent.com/assets/17284964/13098644/7b8159de-d509-11e5-9572-fe883ba1e284.png)

The suns gets a black border, some black points appears on the sky (if you hold this items at night the starts look brighter) and the sky light, well, it's very weird. The only way to fix it is to right click with the Thaumometer or to take a Screenshot using F2, but this in only temporary (10-20 seconds). I think this bug only happens to me for some reason. I've been experiencing this bug since the first version and it's still with me after I created a new minecraft folder to start a new map in the last update. 

That's all I guess 😂 Thanks Azanor for this amazing mod ;)

**Comment by JohnnyG21** [comment]
Update: The Deadly Gaze warp event also makes the screen go black :(

**Comment by Azanor** [comment]
Your graphics cards doesn't play nice with shaders, so I suggest you switch them off in the thaumcraft config setting.
