### ISSUE TITLE
Focus: Builder has different reach (?) for cardinal directions

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#419]
This does not affect the maximum number of blocks the focus is capable of placing.
Basically when you stand in the building line's way and cast looking towards North or West, the blocks hit you in the face.
Do the same for South or East, the blocks stop in front of your face.

Also casting against the ceiling will make the building line go to the feet. Just mentioning this one in case it wasn't intended.

No idea if this affects the range at which the focus can be cast, but meh.

**Comment by Xirema** [comment]
It's one of those "off-by-one" issues caused by the fact that the "origin" of the block is at its lower-south-west corner.

**Comment by MalkContent** [comment]
probably. but the combinations are odd
