### ISSUE TITLE
Thaumic Shielding not functioning on Forge Server

### ISSUE THREAD

**Issue by Quiiliitiila** [Azanor/thaumcraft-5#421]
I've tried looking into this issue, but I can't find mention of it anywhere. My community runs a 1.8.9 Forge server with the latest Thaumcraft 5, unfortunately it seems that Runic Shielding doesn't function properly. What essentially happens is that the shielding "hearts" show up and the graphical effects (runes) still appear when being damaged but all damage just goes right to normal HP.

Is this something that's known? Is there a fix? It'd be nice to have some shielding when adventuring around, my Thaumamancer doesn't wear armor. ;)

**Comment by Quiiliitiila** [comment]
Additionally we have the latest 1.8.9 Botania port and another mod called "The Salt Mod". Botania may be screwing with it, but I doubt it has anything to do with the Salt Mod.

**Comment by Azanor** [comment]
I think this might be the result of some sort of mod interaction - I've tested it in both single and multiplayer and everything works fine.
What sort of damage were you taking? Not everything can be absorbed by yellow hearts.

**Comment by Quiiliitiila** [comment]
I went in and tested various types of damage, from fire to arrows from skeletons and physical blows from zombies. 

I've given it some thought, I think it may be an interaction with Sponge, which the server I play on has installed for custom RP chat. I haven't the faintest idea why it'd be messing with TC's code, but apparently it is. Great. Sponge's devs aren't going to give a damn...

If somehow I figure it out, I'll be sure to post it here in case anyone else has the same issue.

**Comment by Shirolol** [comment]
If I were to take a wild guess: The mod you have intercepts the event of something damaging the player, does whatever it wants to do with that and then sets your HP to a certain amount rather than reducing it.

I don't know, though.

**Comment by Azanor** [comment]
Sponge messes with all the things - they intercept a lot of events and do their own thing with them which messes with many mod interactions. Alas, there is now way I can handle all those cases.

Do a test if you can - spawn in some golden apples or something that gives you the vanilla yellow hearts - if they are ignored as well then it is a big bug that needs to be sorted out by one of those mods. I suspect they will be as all runic shielding does is add the vanilla yellow hearts - how damage is subtracted from them is all vanilla code.

**Comment by Quiiliitiila** [comment]
I had forgotten that golden apples add the yellow hearts, I rarely make them in my games. I'll test that out a bit later today.

**Comment by Quiiliitiila** [comment]
Ok, just checked last night (yeah, I know took long enough) and the extra hearts from golden apples do still function normally. The apples give you a spell effect called "absorption" which appears to function exactly like Runic Shielding (albeit without the Vis cost).

I'm starting to think it's perhaps Sponge not playing well with Baubles, but I'll have to do more testing with other Bauble items. I know the Foci Pouch still works just fine when put on the belt Bauble slot.
