### ISSUE TITLE
Icons broken

### ISSUE THREAD

**Issue by mathwiz617** [Azanor/thaumcraft-5#423]
On FTB Unstable 1.8.9, I've had troubles with the icons for some Thaumcraft items in JEI, the inventory, and the creative menu. The textures for placed blocks are fine, and the others on my server don't seem to have any problems with this.

[http://imgur.com/a/1G3sX](url)

TC 5.1.6
Mod pack: FTB Unstable 3.0.29, minecraft 1.8.9
Java 1.8.0_65, on a Mac

**Comment by Azanor** [comment]
Are you using a texture pack?

**Comment by mathwiz617** [comment]
Nope, all default.
