### ISSUE TITLE
Missing Texture for Amber Ore (Amber Bearing Ore?)

### ISSUE THREAD

**Issue by Mickimoo2** [Azanor/thaumcraft-5#431]
I don't know how to report it with files and stuff, but the latest version for 1.8.9 doesn't show the ore version of amber when it is in the world (no texture) so the client thinks it can go right through it where the server rubberbands you back to your previous spot.

If you need any other logs or anything, let me know.

Client Log:
https://gist.github.com/Mickimoo2/ef5a05b04b802178fa25

Server Log:
https://gist.github.com/Mickimoo2/d02c5f79f74f542d2936

**Comment by Azanor** [comment]
I think something might be broken with that block type on your server - I've tested it all over and everything works fine.

**Comment by Mickimoo2** [comment]
I will update all the mods in the pack (besides neo-tech) to their latest version, this includes thaumic-infusion. Forge version: 1732 . I will let you know if anything changes.

**Comment by Mickimoo2** [comment]
Okay decided to update it to Forge 1755, still no fix for the server. What could be causing the problem and is there files that need to be fixed or deleted in order to fix it?

**Comment by Azanor** [comment]
I suspect that somehow the block id for amber differs between your clients and server - how this is happening I have no idea and I am not sure how it can be fixed.

**Comment by Mickimoo2** [comment]
Might I add, this is also happening to a couple of other items from other mods, from what we have seen it is currently these ones:

ProjectE - transmutation table
Thaumcraft 5 - amber ore
Blood Magic - hellfire forge

**Comment by Azanor** [comment]
Yup, I suspect there is a disconnect between the client and the server. Not really something I can do about that unfortunately.

**Comment by Mickimoo2** [comment]
What seemed to fix the problem is
1. stop the server
2. move the world folder elsewhere
3. start the server then stop it
4. copy the level.dat into the original world folder and replace the old one with it
5. move the old world folder back (delete the newer one first) then start the server

This seemed to fill the missing ID range with only the broken blocks being different.

This is what it looked like, the problem in console that is (client):
https://gist.github.com/Mickimoo2/f58475fa6152d19d5a96
