### ISSUE TITLE
Magical Forest does not show up on Maps

### ISSUE THREAD

**Issue by chrisbecke** [Azanor/thaumcraft-5#435]
When using vanilla maps to explore the world, It is not possible to see on the map the location of any Thaumcraft biomes as the usual 'woods' coloration is used rather than Thaumcrafts distinct colouration.

Version: TC 5.1.6

**Comment by Azanor** [comment]
Not much I can do about it unfortunately - map colors are derived from block colors and magical forests will show up as mostly grass and vanilla leaves, thus the map color will appear 'vanilla'.
