### ISSUE TITLE
Images on Thaumonomicon doesn't render

### ISSUE THREAD

**Issue by marcoasfonseca** [Azanor/thaumcraft-5#436]
Hi :)
I was testing the 5.1.6 thaumcraft version and when I open the thaumonomicon, the images don't show up, instead this there's a pink/black rectangle!

[https://goo.gl/photos/jvV6tD3a8XM9T1NQA](url)

Best regards

**Comment by Azanor** [comment]
The link does not seem to work so I cant check, but do you use a language pack?

**Comment by Mexahoid** [comment]
I think that is the problem with old localization files.

**Comment by Azanor** [comment]
yup

**Comment by Azanor** [comment]
If I know which one I can try and go fix it myself I guess.

**Comment by marcoasfonseca** [comment]
If you copy and paste the link it will work!

But you're right, I changed for English and the images render; I'm using the pt_PT language.
I'm working in a pt_PT language file to latest version, by the way; when I finish I upload it

**Comment by jochuan** [comment]
> Azanor commented 2 days ago
If I know which one I can try and go fix it myself I guess.
could you do that to the pt_BR language ?

**Comment by Mexahoid** [comment]
@jochuan I think it was recently fixed so you can wait until fixed localization files appear in new TC version.

**Comment by jochuan** [comment]
@Mexahoid the only page that was fixed was the research page
