### ISSUE TITLE
Thaumonomicon not saving "reading progress" on multiplayer servers

### ISSUE THREAD

**Issue by davue** [Azanor/thaumcraft-5#44]
The golden stars and the green plus in the Thaumonomicon reappear after reconnecting to the server. Even if I already read them before. This does not happen in singleplayer.

Thaumcraft 5.0.1, Forge 11.14.3.1543

**Comment by Pika0** [comment]
This also happened to my brother when he joined my LAN world again.  He still had his research, but they were all marked with stars again.  And, it being my LAN world, it did not happen to me.
Forge 1.8-11.14.3.1543, Thaumcraft 5.0.0
