### ISSUE TITLE
Filling essentia transfuser priorities

### ISSUE THREAD

**Issue by Boingboingsplat** [Azanor/thaumcraft-5#440]
I posted this in the MCF thread but I thought it'd be a good idea to reiterate here.

Right now it seems as the the filling essentia transfuser prefers to fill labelled jars. If you have a labelled jar with some essentia in it, the transfuser will fill it before empty, unlabelled jars that are closer.

However, if the labelled jar is empty, it will fill an empty, unlabelled jar if it's closer to the transfuser.

I'm not sure if this is intended behavior, but I think it could be more useful if the transfuser always preferred to fill labelled jars, even if they are empty.

**Comment by Azanor** [comment]
It is intended - the transfuser always fills partially filled jars first.

**Comment by Boingboingsplat** [comment]
I think you misunderstood, my issue is that when both jars are empty, some times it will fill the unlabeled one first.

**Comment by MalkContent** [comment]
As fun as it is to giggle at your misery because you didn't use the holy tubes, you heretic, the transfusers should prefer filling labled jars before others. Also the transfusers will keep filling full (unlabeled or labeled) void jars over other (unlabeled or labeled) jars.
