### ISSUE TITLE
Regeneration Crash

### ISSUE THREAD

**Issue by jasendorf** [Azanor/thaumcraft-5#441]
I've been regenerating a 1.7.10 world adding Thaumcraft 5 (never had thaumcraft before).  I had great success regenerating plenty of the world.  Satisfied I had enough ore and crystals and trees, I turned all the regen settings to false and restarted my server.  A while later, I noticed a place where my daughter had set off a ton of dynamite and thought, "no worries, I'll regen this chunk here with WorldEdit."  Upon running //regen, the server crashed.  While trying to restart the server, I get an Index Out of Bounds error and the world will no longer start.

This could obviously be a problem in many places... WorldEdit, Forge itself, or Thaumcraft, but the error message seems to indicate something Thaumcraft's regen doesn't like.

Original Crash: http://pastebin.com/TjNTMEJZ

Startup Crash (with Sponge and Sponge mods removed): http://pastebin.com/xT2EgxcM

**Comment by MalkContent** [comment]
can you make a backup and see what happens when you reenable the regen settings?

**Comment by jasendorf** [comment]
Did that.  It fails to start, same error message.  Regardless of the regen settings (all false, all true, doesn't matter), if TC5 is in the mods folder now, the world will not finish startup.  Fails during the "Preparing spawn area" about halfway through.

I also attempted the following:
Remove TC5 mod from server mods folder -> Start server -> /fml confirm allowing the removal of all TC blocks -> world starts up OK -> stop server -> reintroduce tc5 to mods folder -> start server -> server crashes with same Index OOB error

I did this because I wanted to make sure there wasn't some sort of "pending" regen from WE that was prompting it at startup. If there had been, it would have finished during the startup while TC was removed.

I'm going to try and recreate with a clean server tonight to see if I can recreate.

**Comment by Azanor** [comment]
While thaumcraft is mentioned in the original crash report I don't think it was the cause - the line it crashed on is just used to check if a special vanilla structure is present in a chunk (witches hut, etc). It wasn't actually trying to generate something. I think you might have gotten a corrupt chunk or something and TC crashed while it was trying to get info on that chunk.

I can prevent the crash, but it won't do anything to the underlying corruption that occurred as that is out of my hands.
