### ISSUE TITLE
Aura Node Rendering

### ISSUE THREAD

**Issue by Izidore** [Azanor/thaumcraft-5#446]
Aura Nodes render behind (disappear from view) when looking at a block altered with Chisels and Bits mod.  This is what author, Algorithm X, said:

Seems to be caused when C&B's render switches to dynamic mode, so TESRs block the nodes visually, there is not much I can do about this you can report that TESRs block nodes to TC, maybe Azanor can resolve it by moving its render order further back.. not sure.

Note that I can reproduce the "issue" with vanilla items as well, such a a chest, or a creeper head. So for now I'd say its just an unfortunate kink in the way MC renders things, if anyone can fix it its probably Azanor since the nodes could probably ignore render order and render last to fix the issue, so if your worried about it I'd mentioned it to him.

Thought I would bring it up.  Not sure if you can or even want to do anything with this.

**Comment by Azanor** [comment]
Yup, not much I can do about it due to the order MC renders stuff. Well, I can do something, but not really worth the performance hit it might cause.
