### ISSUE TITLE
Feedback: Growing Tainted Shard clusters not feasable

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#455]
While it is possible to grow tainted clusters you have to absolutely bomb the area with flux for them to do so. The combination of the flux spreading into nearby chunks and high flux lowering itself by causing flux events makes it incredibly hard to try and grow these crystals. And if you employ totems to limit the spreading part, chances are you are gonna use more shards then you gain.
I personally don't mind it being hard to get them to grow, but it's really extreme AND there is the comparatively effortless alternative way to create tainted shards by turning primal shards.
(also the placable item is called "Flux Crystal" and the shard "Tainted Shard" and that might cause some confusion)

**Comment by Azanor** [comment]
Growing them is not supposed to be practical or easy. That is why I added the recipe.

**Comment by MalkContent** [comment]
Fair enough. Just felt like this was worth pointing out.
