### ISSUE TITLE
can't seem to get plantable crystal to grow

### ISSUE THREAD

**Issue by kashigolean** [Azanor/thaumcraft-5#46]
Thaumcraft 5 is my first thaumcraft, so this might just be me doing something wrong. I made the plant-able crystal, one for order, since i can hardly find any shards for it. I waited an in-game week and it doesn't look any different. Doesn't seem to be growing for me. I do have it on stone like the instructions said to.

**Comment by Azanor** [comment]
They don't just grow by themselves - the aura of that type in the chunk must be higher than the normal baseline amount. Under normal circumstances that doesn't happen so you must use artificial means to increase the aura. Hint: Totems.
