### ISSUE TITLE
[1.7.10] Thaumcraft prevents the loading of worlds

### ISSUE THREAD

**Issue by bigyihsuan** [Azanor/thaumcraft-5#460]
I've made a post about it on the Minecraft Forge forums [here](http://www.minecraftforge.net/forum/index.php/topic,37083.msg195407.html#msg195407), and the issue turned out to be Thaumcraft giving a Caught exception from denseores
java.lang.StackOverflowError".

[Pastebin of the error](http://pastebin.com/GqJwT2S1)
[Mod list](http://puu.sh/nrzeo/daf0afd21a.png)

**Comment by Azanor** [comment]
1.7.10 TC is no longer supported. This error is fixed in the 1.8 version.
