### ISSUE TITLE
Ore-dictionary Items and Golem Press

### ISSUE THREAD

**Issue by Terumoc** [Azanor/thaumcraft-5#461]
Thaumcraft 5.1.6, MC 1.8.9:
I am using another mod that adds metals/alloys and their products, including Brass. Thaumcraft generally accepts the materials from this mod like Brass Plates fine in crafting/arcane crafting recipies, I assume due to ore dictionary magic. However, the one exception is the Golem Press, as shown in the screenshot. I'm carrying 3 Brass Plates in my inventory but the press does not accept it.
![2016-03-03_20 27 28](https://cloud.githubusercontent.com/assets/285093/13516386/596c03f8-e17f-11e5-9cdc-d353a4bc1299.png)

Please let me know if this is intended behavior, or if this is in fact a bug.

In the meantime I'm going to add a tweak recipe to create "thaumcraft-brand" plates to my server. Thanks.

**Comment by Azanor** [comment]
I will add a ore-dict check.

**Comment by Terumoc** [comment]
Thank you!
