### ISSUE TITLE
Verdant Heart Band uses Primordeal Pearl, but is unlocked without PP

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#462]
Not sure if intended, but the void metal essentia smeltery and the primal crusher are hidden until after the primal pearl is researched.

**Comment by chrisbecke** [comment]
Isn't that from a different mod? Thats not a TC item.

**Comment by MalkContent** [comment]
as of today it is ;P check for updates and rejoice

**Comment by Azanor** [comment]
I'm not sure what you mean by visible?

**Comment by MalkContent** [comment]
When you have nothing researched, it's already visible, greyed out. The other things with primal pearl inside are completely hidden.

**Comment by Azanor** [comment]
That is because the other things that require primal pearls are either part of eldritch research or require loads of other requisites. Technically you can get pearls without a lick of research so they aren't a research requisite.

**Comment by MalkContent** [comment]
The other things require you to not only find, but research the pearl, though, which is the thing that felt off to me.
