### ISSUE TITLE
Arcane Bore grievances

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#463]
-does not produce clusters with new infusion enchanting: refining mechanic (only checks for pickaxe of the core, has no levels, doesn't work with other pickaxes)
-does not give vis discount if focus has frugal
-can't attach levers, torches, etc. to bore base side. arcane lamps work though

tag on: give excavation focus option to upgrade drowsing more than once? could stack with pickaxes refining. sidenote: destructive on pickaxe could increase width.

**Comment by chrisbecke** [comment]
I don't quite understand dowsing. Without the ability to upgrade to  "Dowsing III" to get 100% yield rate, a player concerned with ore doubling is going to have to build a Advanced Alchemy setup for ore doubling anyway. At which point, why waste a focus upgrade on dowsing?

**Comment by MalkContent** [comment]
If dowsing would be equivalent to refining, 3 wouldn't be max, 4 would be. And even at 4, yield rate wouldn't be 100%. Yieldrate is (1 + <lvl of refining>)*12,5%
If there was 4 levels of dowsing and it stacked, you could create a 100% yield bore for refining purposes /and/ make the yieldrate simply <lvl of refining+dowsing>*12,5% (for the bore)

Also a player concerned with ore doubling would just place the harvested ore blocks again to be reharvested until it's all clusters.
