### ISSUE TITLE
Placing Hover Harness/Verdant Heart Band into Recharge Pedestal crashes the game

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#466]
This time no other mods present.
Crashlog:
http://pastebin.com/rAswPNuX

**Comment by MalkContent** [comment]
(also: still requesting to just put any stuff into the recharge pedestal. and if it is a void metal thing or has repair on it, repair it.)

**Comment by Azanor** [comment]
Void metal does not use vis to recharge and as for the rest that may/will be coming in MC 1.9

**Comment by MalkContent** [comment]
Void metal was just for completeness, too little durability to be practical to place in there for repair. I guess it may need the player to hold it's hand to make it feel better :)
Other than that recharge pedestal would just be nice to use to put things on display. It looks fancy and doesn't interact with the infusion altar.
