### ISSUE TITLE
Sword of the Zephyr can't be crafted/recipe is bugged

### ISSUE THREAD

**Issue by LemonPeeler** [Azanor/thaumcraft-5#468]
Thaumcraft 5.2.0
Forge 11.15.1.1738

Looking at the recipe for the Sword of the Zephyr in the Thaumonomicon shows it outputting a Pickaxe of the Core with Arcing II, and attempting to craft it will result in a Pickaxe of the Core with Sounding II, Refining I and Arcing II.

**Comment by MalkContent** [comment]
:D get it while you can! arcing can't be applied to it normally ;)

**Comment by Azanor** [comment]
Oops, left some test code in.
