### ISSUE TITLE
Recharge pedestal crashes world

### ISSUE THREAD

**Issue by mujmajnkraft** [Azanor/thaumcraft-5#469]
I tried to place Thaumostatic harness on recharge pedestal and it crashed my world. I tried to load it again, but it always crashed. I created a new world and tried to place there Hearth band and it crashed my world as well. Wands were recharging normally. Amulet was impossible to place on the pedestal. Luckily, Irecovered my world with NBTExplorer.
Thaumcraft 5.2.0
JEI, JEI addons, JEResources, Xaeros minimap, Baubles

**Comment by MalkContent** [comment]
see https://github.com/Azanor/thaumcraft-5/issues/466
also: amulet's are no longer vis storages. Instead, they are mobile pedestals.
