### ISSUE TITLE
Minor: Vis Storage Amulett misnamed. It don't store vis no moar

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#471]
suggestions for new name:
Vis Channel Amulett
Channelling Crystal Amulett
Vis Crystal of Channeling
Charm of Vis Channelling
Channelling Channel of Channellinging
Quickus Drawus Visus
Gotta Go Vist
The Fast And the Visious

(also vis stone recharges everything, not just wands, as the tooltip would suggest)

**Comment by Shirolol** [comment]
Actually, why not have it charge up vis to a sizable buffer and only be able to draw vis when equipped, but still release vis when just kept somewhere in the inventory as long as the buffer has something?

**Comment by Azanor** [comment]
It was a toss up between Quickus Drawus Visus or Amulet of Vis. I ended up going with the boring option.
