### ISSUE TITLE
Collector infusion enchantment does not work on Pickaxe of the Core

### ISSUE THREAD

**Issue by runfalk** [Azanor/thaumcraft-5#474]
I tried to infuse my Pickaxe of the Core with the collection enchantment. When mining blocks they drop like normal instead of gravitating towards me. My Primal Crusher doesn't have this enchantment either since the update (though I assume that is intentended?)

This is version 5.2.1.

My pickaxe had the following enchantments before infusion:

Sounding II
Refining I
Repair II
Efficiency V
Silk Touch I

It may apply to all pickaxes, but I have only tried with this one.

**Comment by MalkContent** [comment]
related to https://github.com/Azanor/thaumcraft-5/issues/473
tried with axe of the stream, silktouch only
Collector get's broken by silktouch, too, apparently

**Comment by runfalk** [comment]
I just tried breaking an Everfull urn with the same pickaxe as in my initial post, which did gravitate towards me like expected. This is the only block I have found so far that works with the Collector enchantment.
