### ISSUE TITLE
(maybe) Infusion Enchanting chance to add Warping to Tool bound to player presence

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#475]
TC 5.2.1
See InfusionEnchantmentRecipe.getRecipeOutput
Came across this when snooping around for the warping chance.
The RNG deciding whether or not warping is added to the tool is based on the player.
If a player starts the infusion, leaves, get's the chunk to be loaded and the infusion finishes, player would be null and the chance to add warping to the tool circumvented.
I might be wrong about this and player might not end up null, but I remember that in TC4 one could avoid the chance to gain sticky warp from crafting flesh golems/advanced flesh golems/brain in a jar in much the same way.
If this would be the case here, too, there is no reason not to use a different RNG.
I did not verify this because its chanced based and would be a royal pita without debug breaks, not to mention getting a server and searching for a chunkloader.

**Comment by Azanor** [comment]
The player should not become null (as far as I know), but I guess I could just use my own random number instead of the players to make sure

**Comment by chrisbecke** [comment]
Also, shouldn't using +warping tools or armor keep the warp effects active counter refreshed? I can undertand a player with Thaumium fortress armor "opting out" of warp events, but the void robes? not so much.
