### ISSUE TITLE
When upgrading from 5.1 to 5.2 store seals with whitelist are not properly preserved

### ISSUE THREAD

**Issue by runfalk** [Azanor/thaumcraft-5#478]
When updating from 5.1 to 5.2 store seals can specify an amount to put in an inventory. Whitelists from 5.1 lack this feature and are converted to be 1 on every item in the whitelist instead of an arbitrary amount (the little x in the corner).

**Comment by Azanor** [comment]
Well yeah, you will have to convert them by hand. The default stack saved in seals has a stacksize of 1.
