### ISSUE TITLE
Burrowing does not work properly

### ISSUE THREAD

**Issue by Danymaddox** [Azanor/thaumcraft-5#483]
The new enchantmen "Burrowing" does not work as spected, it leaves blocks, here's a video:

https://www.youtube.com/watch?v=n8IJE_VQM6E

**Comment by Azanor** [comment]
Yes, to keep the code as efficient as possible it assumes the blocks will be clumped together, or 'tree' shaped. Serpentine shapes like that will probably cause some blocks to be missed. A more accurate algorithm will also be a LOT slower.
