### ISSUE TITLE
After Silk touching any infused stone you cannot then break it.

### ISSUE THREAD

**Issue by b0bst3r** [Azanor/thaumcraft-5#484]
Take any pick (works with vanilla picks too) with silk touch and mine infused stone.

Replace the block in the world and break it and you get the block back not the shards

Thaumcraft-1.7.10-4.2.3.5.jar (not sure if you're still maintaining this line since moving on to 1.8)

https://github.com/BevoTechPack/BevoTechPack/issues/893

If this is a mod interaction thing I've no clue where to even begin with this or is this by design?

**Comment by Azanor** [comment]
Not by design and I can't see how this could happen. Either way I am sorry to say 1.7.10 and that version of TC is not supported anymore.
