### ISSUE TITLE
(HEUREKA) Bug: Totem of Attraction ignores the cross of chunks it is placed in.

### ISSUE THREAD

**Issue by Shirolol** [Azanor/thaumcraft-5#486]
Earlier I reported in the API GitHub(Sorry about that) that the Totem of Attraction is unable to draw the 20 points from the 4 adjacent chunks of the totem, when I evaluated my tests
( https://www.youtube.com/watch?v=1g5ObGe3uhQ )

I came to the conclusion that either it can't draw from very close chunks, or not from very low amounts of vis, but further testing revealed that neither is the case.

When I released some flux in one of the diagonally adjacent chunks the totem found and removed it.
Because of that I got the idea that the totems actually just ignore the CROSS of chunks they are placed in, so I added a few outer poles and released some more flux: 5 in one distant chunk on the same line of chunks as the chunk the totem is placed in and 5 just one chunk to the left, technically even a little farther away from the totem.

Guess what: The totem did not find the flux in the first chunk, but it DID find the flux in the directly adjacent chunk.

My is that when you check whether a chunk is in the inner area you accidently use OR instead of AND when comparing the target chunk with the totem chunk, so you get a cross instead of a square. but I can't know.

The totem of Dispersal seems to work fine.

**Comment by Shirolol** [comment]
Oh and while we're at it : Is the chunk selection random because you think the machine should really work this way(don't want it to have a pattern) or because you could not think of a pattern that would resemble your idea of how it should work more closely?

**Comment by Azanor** [comment]
Yup that was the issue - sort of. Nothing to do with an or/and problem, but the way the random location was generated. It effects both totems, but I guess it is not as apparent with the dispersal one.

**Comment by Shirolol** [comment]
It was possible to discover this because unlike vis flux can be released very controlledly.

Perhaps troubleshooting things like that would be easier if we had items that allow us to add/remove any kind of vis from the aura at will?
