### ISSUE TITLE
Golems are holding items they dont have.

### ISSUE THREAD

**Issue by jrpoints** [Azanor/thaumcraft-5#488]
![2016-03-05_12 53 12](https://cloud.githubusercontent.com/assets/5988499/13550384/6e482d94-e2d1-11e5-8d40-7fba5a4909a7.png)

These two golems are both set to collect, sometimes after they drop there load off they will be left holding what I guess is a ghost block because picking the golem up does not drop the block that they are visually holding.

It also seems to take up that inventory spot as they seem to only grab one stack of items once they bug out.

**Comment by MalkContent** [comment]
see https://github.com/Azanor/thaumcraft-5/issues/427

**Comment by Azanor** [comment]
I'm not able to duplicate this, but I do suspect I found where it could possibly happen. Please keep an eye on this and reopen if it still occurs after the next version goes live.

**Comment by MalkContent** [comment]
This issue doesn't state it, but as the other one says, it only happens for golems with hauler.

**Comment by Azanor** [comment]
I assumed as much - it was clear from context.
