### ISSUE TITLE
AURAS TAKING X ms LONGER THAN NORMAL

### ISSUE THREAD

**Issue by Iudicoletum** [Azanor/thaumcraft-5#491]
X =ing anywhere between 100 to 1000, this message is spamming my server logs and slowing my server down.

**Comment by runfalk** [comment]
I had this issue with Forge 1.8.9-11.15.1.1764 but not 1.8.9-11.15.1.1738.

**Comment by sdiaz** [comment]
Same with me, only with Forge 1764 (Abyssal 1.8.9-1.9.0 forge min version needed).
I tested the client setup without Thaumcraft and everything runs smooth, after launching with Thaumcraft, start lagging until it freeze.

**Comment by sdiaz** [comment]
Hello guys, i have just gived more memory to the game and the issue is not reproducing anymore. Can you also check this? I have used this options:

-Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Xms1G -XX:MaxPermSize=256M

**Comment by kreezxil** [comment]
I have this same problem. http://paste.ee/p/Clhhs

I will try sdiaz's suggestion and report back if it stops.

**Comment by sdiaz** [comment]
just tips for memory configuration

-Xmx is the maximum of RAM wich Minecraft can allocate.
-Xms is the allocated RAM at the beginning.
-Xms can also be omitted. As result Minecraft will not allocate all Ram at once, but as much as needet.
-Xms must not be greater than -Xmx!

Java 32bit officially only supports up to 4GB. Most 32-bit based systems but only support 2GB. The limit depends on the system, if you got an error, try less allocation.
Be sure to use the right and newest Java version (64bit on 64bit-OS-Systems is recommended).

-Xmn : the size of the heap for the young generation

Young generation represents all the objects which have a short life of time. Young generation objects are in a specific location into the heap, where the garbage collector will pass often. All new objects are created into the young generation region (called "eden"). When an object survive is still "alive" after more than 2-3 gc cleaning, then it will be swap has an "old generation" : they are "survivor".

-XX:PermSize -XX:MaxPermSize are used to set size for Permanent Generation.

Permanent Generation: The Permanent Generation is where class files are kept. These are the result of compiled classes and jsp pages. If this space is full, it triggers a Full Garbage Collection. If the Full Garbage Collection cannot clean out old unreferenced classes and there is no room left to expand the Permanent Space, an Out‐of‐ Memory error (OOME) is thrown and the JVM will crash.

Starting with Java 8, both the permgen space and this setting are gone. The memory model used for loaded classes and methods is different and isn't limited (with default settings). You should not see this error any more.

**Comment by kwpugh** [comment]
I can confirm.   Memory setting just delays the problem.   I was getting the messages when players flew around or ran fast through new chucks.   After only downgrading from Forge 1764 to 1763, all the messages went away.

**Comment by kwpugh** [comment]
False alarm, the forge 1764 downgrade did not help.   The problem does take longer to rear its head, but it's still there.  

Any other ideas?

**Comment by Hydrargiros** [comment]
In my server, the Thread-7/WARN] [THAUMCRAFT]: AURAS TAKING ms LONGER THAN NORMAL
also happens. I have some friends there and when one of them starts thaumcraft, their area mess up auras, and server gets laggy when the aura delay is to big.
