### ISSUE TITLE
You can research Clockwork Minds without researching Magic Tallow

### ISSUE THREAD

**Issue by Zobody** [Azanor/thaumcraft-5#493]
Researching Clockword Minds automaticly unlocks Golem Control Seals, and in Golem Control Seals page 1 a recipe of Blank Seal is shown, which has Magic Tallow in it.

**Comment by mujmajnkraft** [comment]
There is more "strange" things in thaumonomicon. You can recearch focus pouch before researching a single focus or hearth band without researching the pearl. I do not think Azanor will change it.

**Comment by Azanor** [comment]
Yeah it is fairly minor and someone might try and get golems and not figure out why it is locked because they don't have tallow yet. It doesn't seem like something they might need for golems. It is easier for them to then get it afterwards if they see they need it.
