### ISSUE TITLE
+Warping on tools should refresh the warp effects counter

### ISSUE THREAD

**Issue by chrisbecke** [Azanor/thaumcraft-5#498]
I noticed this in TC4 so I assume that it is still an 'issue' in TC5, if not I apologize for the redundant bug report.

Issue: While using +Warping tools and armor the warp effects active counter still counts down if no other warp inducing things are performed.
While I can understand players with Thaumium Fortress Armor and elemental tools opting out of warp events without using soap or bath salts, it seems silly that players can opt out while using void robes or anything with an explicit +warping effect.

+Warping items should surely be balanced for players who manage, rather than ignore, their warp levels.

**Comment by Azanor** [comment]
You bring up a good point. Maybe +warping effects could slow down the counter? I will take a look.

**Comment by MalkContent** [comment]
I still wish their selfrepair would have a very small chance to give temporary warp, sort of like they had in the beginning. So using them would affect the counter inheritly and they actually come with the cost of having to use soap if used excessively. And would give reason to use the soap more. I like the soap :)

**Comment by chrisbecke** [comment]
So, basically change "+Warping" to have a chance to add temp warp each time a void item self repairs? That's kind of elegant imo and it both keeps temp warp up a bit, making the occasional salt bath relevant, and refreshes the warp counter, necessitating the use of soap.
I Like.

**Comment by MalkContent** [comment]
I'd definitly keep the slowing down of the counter Azanor seems to have already done. Would be an actual passive penalty to being clad in void metal. The flat +warp the items add right now is hardly felt.
The tempwarp would just be the added active penalty for using it.

**Comment by chrisbecke** [comment]
Ultimately it is up to Azanor, but having two different code paths to achieve the same thing is a redundant waste of effort. 

With an active penalty, your ... encouragement to bathe would be proportional to the usage level of the tools and armor. And can be explained as the madness induced observing - or being close to - the material using its dark energies to self repair.

With such an active penalty, the passive penalty seems redundant, does not scale with the use of the armor, and has no easy cause as the armor and tools are entirely passive.

**Comment by Azanor** [comment]
Nope, adding temp warp will not be a good idea as that will cause the counter to never actually go down. Slowing down the 'warp decay' should be good enough. The Warping effect already increases the severity of warp events. More penalties are not required.

**Comment by MalkContent** [comment]
What if temp warp gain didn't affect the counter? Generally any warpy stuff caused by the player is pwarp or swarp anyways.

**Comment by chrisbecke** [comment]
You don't know the brains I eat!

**Comment by MalkContent** [comment]
brains will give you swarp eventually :)
