### ISSUE TITLE
Mercy for CPU

### ISSUE THREAD

**Issue by Zaltora** [Azanor/thaumcraft-5#50]
After tainted a complete area. i had test to remove the taint. It is work well but Degraded Taint Dust...
Some pictures:
![2015-11-02_19 16 59](https://cloud.githubusercontent.com/assets/5892130/10952090/4f0c44a0-8341-11e5-8f4b-8cfbccdc743f.png)
![2015-11-02_00 19 09](https://cloud.githubusercontent.com/assets/5892130/10952099/5acf7974-8341-11e5-8a16-2bd2a1b2c35d.png)

I like Dust but i admit for huge area and low configuration computer, i have 5-15 fps  (30-40 standard). And dust is very long to move or disappear.

It is possible like Stone that some dirt reverse as solid block like "Degraded Dirt". Add a config to set the % amount of taint who reverse into dust instead a solid block would be great if possible.

**Comment by Azanor** [comment]
I will add config options that will turn tainted soil into dirt instead of dust, as well as one which will increase the rate at which dust dissipates.

**Comment by MalkContent** [comment]
I think the issue with the dust is that it is flowing and checks for that everywhere. 1 dust dissipates, the whole region rumbles, chainreacting

**Comment by ewsmith** [comment]
can we have a degraded soil that decays into dust when exposed to air? 
that way, instead of a massive soup of dust, we could have useless dirt with a layering of dust on top.
