### ISSUE TITLE
possible non-issue: it's possible to sprint when flying with the Thaumostatic Harness

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#500]
TC 5.2.1
Sprinting while flying was possible in TC4, but the harness was going at the same speed, which is why I am mentioning this.
Depending on presence of haste enchant and thaumostatic girdle one can go very, very fast while flying with the harness.
You can't start sprinting with double tapping when in the air, but you can just use the sprinting key. Also you can start sprinting on the ground in any way, then jump and fly, remaining in sprint mode, which is how I discovered this.
If this isn't intentional, I wouldn't mind keeping sprint flight as a feature, maybe slowed down a bit, and the harness pooping some flux :3

**Comment by Azanor** [comment]
Hmmm, or possibly allow sprinting to some degree at a much greater charge cost. I'll take a look.
