### ISSUE TITLE
research mechanic buggy(Master aura tapping)

### ISSUE THREAD

**Issue by Pyro-Ninja** [Azanor/thaumcraft-5#501]
![2016-03-07_19 16 23](https://cloud.githubusercontent.com/assets/11063312/13580768/8ba72892-e49b-11e5-827c-60a8ef3557e5.png)

Am I derping out?

**Comment by MalkContent** [comment]
lower left corner, aer does not connect to potentia.
don't forget closing the issue ^^

**Comment by Pyro-Ninja** [comment]
woops xD sorry for wasting your time!
