### ISSUE TITLE
Can't scan Glyphed Stones

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#502]
TC 5.2.1, OpenComputers, Chisel n Bits
I can't scan glyphed stones, even though it has question mark particles.
So I tried again in creative, scanned other items until I knew all the aspects of glyphed stones -> glyphed stone still has question mark particles and I still can't scan it.
Basically researched everything else and have two dungeons cleared, but still lack the Revelations in the Outer Lands research, so probably trouble with that.

**Comment by runfalk** [comment]
I have the same problem, both with 5.1 and 5.2.

**Comment by Azanor** [comment]
Have you scanned a boss?

**Comment by MalkContent** [comment]
I did now. Same thing, bosses keep having questionmarks. The praetor gave me a clue, but I guess that was for armor research or something. I gave myself the ENTEROUTER research before and scanning the praetor didn't unlock the Revelations.

**Comment by Azanor** [comment]
I suspect the research is somehow requiring itself as a requisite or something silly like that. I will take a look.
