### ISSUE TITLE
Eldritch Eye dropchance is reasonably huge

### ISSUE THREAD

**Issue by Hyxaru** [Azanor/thaumcraft-5#507]
If you compare it to other rare drops like wither skulls, it drops maybe four times as often. Could be a bug, or an intentional change but never mentioned, because they used to be rarer.
On a second note, the flavoured subtext 'it seems to be watching you.' is missing.

**Comment by MalkContent** [comment]
Agreed. I don't have killed copious amounts of them, just a couple for farming essences and some in 2 outer lands labyrinths and I ended up with more than a stack of eyes (though that is with a Looting 3 sword).

**Comment by Azanor** [comment]
The drop chance hasn't changed since tc4 (1 in 10 chance + improved by looting modifier).

**Comment by Azanor** [comment]
However they really should drop a lot less in the outer lands now that I think about it.

**Comment by MalkContent** [comment]
*looks it up to be sure* in tc4 the eyes were in dropRareDrop, which is 2.5%, up to 5.5% with looting 3
right now it's probably possible to even drop multiple eyes, because it's in dropFewItems

**Comment by Azanor** [comment]
Hmm, you are correct. I think dropRareDrop was removed in 1.8. 1 in 10 still seems about right to me. I might reduce the effect looting has on the droprate. 
Multpile items cant be dropped however. dropFewItems is only ever called once and I only drop a single eye.

**Comment by MalkContent** [comment]
I think it's addRareDrop or something now. Definitly still there. And I wouldn't worry to much about multiple eyes dropping. 1% for two eyes, 0.1% for three eyes, 0.01% for four eyes, it's more like a "omg, you guy's, you won't believe what just happened" event ^^. Also I was assuming looting would just call the method multiple times, I might not even be right about this.

**Comment by Azanor** [comment]
The vanilla version of it drops multiple items if a getDropItem() is specified.

**Comment by MalkContent** [comment]
it's "addRandomDrop"

**Comment by Azanor** [comment]
Ah yes. Interestingly enough it seems to be never used in vanilla.

**Comment by MalkContent** [comment]
zombies, skeletons and rabbits have it :)
also the looting behaviour for normal drops is apparently different for different things, if the mc wiki can be believed
anyways, I'm gonna stop nitpicking now

**Comment by Azanor** [comment]
Ok, apparently eclipse's Java search doesn't work quite as well as it should. They do indeed call that method.

**Comment by MalkContent** [comment]
O i know that pain :D you can find it with a java search and selecting "Search for: Method", and checking all the boxes for "Search in".
That search for part was what did me in.
