### ISSUE TITLE
Can't infuse silverwood rod?

### ISSUE THREAD

**Issue by Zobody** [Azanor/thaumcraft-5#509]
I have all the items in the right positions, and silverwood log in the middle. When I right-click the runic matrix, infusion starts, but it doesn't drain vis like it should. Flux effects still occationally happen.

![2016-03-08_20 49 48](https://cloud.githubusercontent.com/assets/16544117/13612401/f60732a2-e56f-11e5-869f-a5157452b7a0.png)
![2016-03-08_20 49 50](https://cloud.githubusercontent.com/assets/16544117/13612405/f9fe6cc2-e56f-11e5-8c63-06ba424b265c.png)

It seems like it need potentia, which I have plenty of.

**Comment by MalkContent** [comment]
it starts from right to left, so you seem to be missing aer
