### ISSUE TITLE
Missing aspect on block

### ISSUE THREAD

**Issue by Zaltora** [Azanor/thaumcraft-5#51]
List of item missing:

-Cobblestone Slab
-Stone Bricks Slab
-Nether Bricks Slab
-Arcane Stone Slab
-Arcane Bricks Slab
-Ancient Stone Slab
-Eldritch Stone Slab
-Stone Slab
-Glass Pane ( and all colors variant )
-Cobblestone Wall
-Mossy Cobblestone Wall
-Porous Stone
-Amber Bricks
-Tainted Rock
-Sugar
-Bottle o' Enchanting ?
-Firework Star
-Miner's Ring
-Ring of Protection
-Triple Meat Treat
-Bucket of Purifying Fluid

I think it is all :D

**Comment by Azanor** [comment]
Many of these aren't supposed to have aspects simply because of how the recipe calculation system works and to prevent getting free essentia. 
There are a few I did miss however :)
