### ISSUE TITLE
Vanilla Chest has zero Vacuos Aspect

### ISSUE THREAD

**Issue by ErdrickXLII** [Azanor/thaumcraft-5#511]
It's not that it doesn't _have_ the Vacuos aspect on it, it's that it has _zero_ of it.  The Vacuos icon shows up when you mouse over it, but no number appears in the lower right.  The Essentia Smeltery will give you only 6 Herba, and throwing it into a Crucible will give you 6 Herba and Zero Vacuos, which can't be used for crafting, but will eventually dissipate into flux.

**Comment by Azanor** [comment]
What version of TC is this? This has been fixed ages ago as far as I am aware.

**Comment by ErdrickXLII** [comment]
Sorry, forgot to mention.  I'm running version 5.2.1 for Minecraft 1.8.9.

**Comment by MalkContent** [comment]
confirmed for me. chests have a numberless vacuus aspect in game and smelting doesn't give any vacuus.
work around using bowls for now :)

**Comment by Azanor** [comment]
Stupid trapped chest messing with the aspects :<
