### ISSUE TITLE
Golem provision requests don't ignore metadata

### ISSUE THREAD

**Issue by Tuhljin** [Azanor/thaumcraft-5#512]
Provision requests from golem seals are inflexible in that they require a specific damage value. This has made it so seals requesting a tool only get one with no damage (or whatever specific damage value is specified). This is the case even if both seals are set to ignore metadata (and a similar issue may exist when it comes to ignoring NBT, using the ore dictionary, etc.).

To test, you can put a shovel with no damage as the whitelist for the Use seal. Next, put damaged shovels in a chest with a Provide seal. A golem will not take any of the shovels from the chest even if the seals are set to ignore metadata. If you put an undamaged shovel into the chest, the golem will take it almost right away.

Incidentally, I'm in need of a fix for this to make provision requests viable with a seal in my addon. It's fairly pointless if it only gets undamaged versions of a tool only to go ahead and damage them upon use.

**Comment by Azanor** [comment]
The solved is in regards to damageable tools and the use seal set to ignore metadata. The rest is best discussed in the other issue.
