### ISSUE TITLE
Colored Seals issueing tickets to uncolored golems and uncolored to colored

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#516]
At the moment the only way to get golems to work specific seals only is to color all seals AND all golems in the area, because uncolored golems will work for colored seals and colored golems will work for uncolored seals.
I'd love if colored seals would only issue tickets to their specific colored golems, as to not have all the uncolored general purpose golems in the area "help" and all out of the sudden the greatwood pals find out that they are more flammable than their clay buddy working in the lava pit (yes I made this up).
I think this is probably more intuitive than the other way around.

**Comment by Azanor** [comment]
I have to disagree. Why limit options that simply coloring your golems/seals would solve?

**Comment by MalkContent** [comment]
hmmmmmm. fair enough! I should reimplement my essentia dyes x)
