### ISSUE TITLE
"Flying is not enabled on this server" for Grappler, but not Harness

### ISSUE THREAD

**Issue by chrisbecke** [Azanor/thaumcraft-5#519]
I play on a server that (apparently) has flying disabled in the server.properties.

When I use the TC harness, this is not a problem - the creative flight it grants seems immune to the flying check.

However, I made the regrettable mistake of adding "Sticky" to my latest Grappler focus, fired it at a nearby wall, hung there for a second and got disconnected with the "Flying is not enabled on this server" message..

I guess that, with items like the Harness, we should enable flying, but that presumably allows hacked clients to cheat, as the harness implements its flight on the server, but the Grappler (and hacked clients) simply don't fall down.

**Comment by Azanor** [comment]
I am not sure why the hover harness doesn't trigger the check tbh, but in theory any extended time spent off the ground should trigger it.
I'll look into it, but I am hesitant to mess with it too much.

**Comment by Azanor** [comment]
Nm, turns out that was a pretty easy fix.

**Comment by chrisbecke** [comment]
I was about to say perhaps the bug is that the harness is not triggering the check. :P

But then my thought was that, the "flight disabled" check is to catch cheating with a client side mod/hack, and server mod enabled flight should not be subject to the check.

**Comment by Azanor** [comment]
I actually specifically work around that check for the harness. I did it so long ago I completely forgot it existed :). It was easy enough to add to the grapple focus.

**Comment by NinjaCatFail** [comment]
You might look into the levitation platform as well. I was just kicked for using two them stacked on top of each other.
