### ISSUE TITLE
Sky render bug while holding an item that creates an on-screen gui (wands, thaumometer, etc)

### ISSUE THREAD

**Issue by SilverDavidMC** [Azanor/thaumcraft-5#52]
Thaumcraft 5.0.0 - 5.0.2
Forge 11.14.3.1521, and Forge 11.14.3.1543

While holding a wand, thaumometer, sanity checker, or anything else that would create a GUI on screen, the raw texture files for the sun, moon, stars, and anything else for the sky will render. The main, and most obvious, being the sun. As you can see, it has a black box rendering around it, just like the raw texture file. The moment I hold something that doesn't have a GUI, it renders as it should. Along with that, something rendering in the chat, or having the NEI tool tips at the top of the screen temporarily fix it as long as their GUIs are visible. This bug happens when Thaumcraft is installed on its own, or with other mods. The thing about NEI somewhat fixing it, while its tool tip GUI is on screen, was just an observation that I felt like I should note.

![2015-11-04_18 20 05](https://cloud.githubusercontent.com/assets/15661705/10955456/e35f7b56-8321-11e5-9821-179500951fc7.png)

**Comment by Zaltora** [comment]
I had this bug too only when i installed Optifine. It is your case ?
I dont no if it is a bug from optifine or TC5.

**Comment by SilverDavidMC** [comment]
This happened regardless of the mod combination. If Thaumcraft was there, I'd get the bug. I seems to fix itself while you have something else display on the screen. For example, opening a chest, something in chat, pausing the game, or having a minimap mod installed.

**Comment by Zsashas** [comment]
I have noticed this with Thaumcraft, without Optifine. Also, not sure if it's related, but leaves and such seem to...shiver, if that's the right word. The edges won't stop moving slightly, even far away.

**Comment by SilverDavidMC** [comment]
I've seen the leaves too. Not personally, but in Haighyorkie chilled's tutorial. Remember, the comments isn't where you post a bug report. They belong as a separate issue.

**Comment by Azanor** [comment]
I've seen people report this as being a Waila issue.
