### ISSUE TITLE
Grappling hook foci charge off

### ISSUE THREAD

**Issue by peeken1** [Azanor/thaumcraft-5#520]
When spamming with the grappling hook wand charges momentum that releases upon successful swing when you have landed. this mechanic have killed me several times. this is in the version for 1.8.9 Minecraft. 

a Gif of me executing said bug/mechanic
http://i.imgur.com/bIK2Tnm.gifv

**Comment by MalkContent** [comment]
I can't reciplicate this. Could you make a walkthrough for dummies?

**Comment by peeken1** [comment]
this might be a clearer less messy gif to try to replicate and with 2 failed attempts in the begining

http://i.imgur.com/92et8d9.gifv

**Comment by MalkContent** [comment]
nope. can't do it. can you try kicking all other mods and see if it still works that way for you?
