### ISSUE TITLE
Minor: Sounding triggers when interacting with things

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#522]
interacting = rmb-ing a thing.
Only blockbased things, ofc.
TC 5.2.1

**Comment by chrisbecke** [comment]
Opening chests with a pickaxe of the core active was not an issue in TC 5.1 or earlier. Post 5.2 the "Sounding" sfx triggers if the pickaxe is current and I open / interact with anything.

**Comment by Azanor** [comment]
Unfortunately I won't be able to prevent this. It now triggers off a forge event. I could cancel the event after triggering the pulse, but that means anything with this enchant will not be able to be used for right clicking. Triggering the pulse is probably the lesser of the two evils.
