### ISSUE TITLE
Interacting with Pech to open trade window does not cancel the items right click

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#523]
TC 5.2.1
turns out they don't like being zapped :/

**Comment by Azanor** [comment]
Don't click with a wand then :p

**Comment by Azanor** [comment]
Ok, investigated it a bit and looks like it won't be fixable. The event the 'activate focus' code occurs in happens before the 'interact with entity' code so I cant stop one in favour of the other without breaking wands completely. In previous versions foci got triggered in a different event, but it had to be changed for various reasons.

**Comment by MalkContent** [comment]
It's not just with wands, it's with everything. Villagers are interactable with that way, I think it's with returning a boolean on interaction that prevents the item use from fireing. I might be wrong though.

**Comment by MalkContent** [comment]
This also counts for interacting with villagers with wand+focus in hand.
The focus does not fire then.
The reason I am pressing the issue is that pech trade for ender pearls, and throwing ender pearls at them is another thing they do not like :/

**Comment by Azanor** [comment]
Well, I can fix it specifically for the pechs (which I did), but not much I can do about other mobs.

**Comment by MalkContent** [comment]
Wand+Focus does not fire when interacting with anything vanilla (minecarts, minecart+chestetc, horses, villagers) or the one other interactable mob I have, which is OC drones.
So now I am wondering what you fixed there specifically (might be misunderstand this). I'm pretty sure there's a generic way.
The deal with pech is not specific to wand+focus.
