### ISSUE TITLE
Void metal items accept Repair enchantment

### ISSUE THREAD

**Issue by chrisbecke** [Azanor/thaumcraft-5#526]
Given that void metal items have a built in repair mechanism, it is not obvious to me that they should, additionally, be eligible for the repair enchantment. 

Is this intentional?

Also, this is in TC 5.1.6 - The new Infusion enchanting mechanisim in 5.2 should fix this.

**Comment by Azanor** [comment]
Does it matter? You can have your tools repair extra fast if you want.

**Comment by chrisbecke** [comment]
It matters I guess, only in so much that the ability to stack "Repair" with "Unbreaking" is considered unbalanced or not. I for one will not put unbreaking on an item with Repair as that was the original intention.But that makes this a balance issue, rather than a bug. And hence off topic for a bug report.
