### ISSUE TITLE
Silk Touch prevents most tool Infusion enchantments from working

### ISSUE THREAD

**Issue by Pitfallingpat** [Azanor/thaumcraft-5#528]
Thaumcraft version 1.8.9-5.2.1
Forge Version 1.8.9-11.15.1.1764

As the name implies, Refining, Destructive, and Collector do not work on any tool with the vanilla silk touch enchantment on them. (Collector is not the right click of the axe of the stream)

Destructive does not dig in a 3x3, Refining never drops native clusters, and Collector doesn't have items magnet towards the player.

For some reason Burrowing still works though.

**Comment by Azanor** [comment]
Already reported here and will be fixed in next version

**Comment by codewarrior0** [comment]
Auto-smelt (from EnderIO, I think?) has a similar issue. The Collector infusion overrides auto-smelt and draws in iron ores instead of allowing iron ingots to appear.
