### ISSUE TITLE
Blackscreen suddenly ingame

### ISSUE THREAD

**Issue by ThexXTURBOXx** [Azanor/thaumcraft-5#532]
Sorry if my explainations are wrong... I am pretty new with Thaumcraft 5:

2 days ago my friend and me played a private modpack including Thaumcraft 5.2.1.
He plays on a pretty bas laptop and suddenly his Minecraft-screen turned black. We both thought, his graphic card or something like this broke...
But now, as it happened to me, I looked through the logs and then I saw this text:
"The light suddenly becomes overwhelmingly bright and burns your skin." (A text like the other ones, if you "become too evil")
I think, that this message is the trigger for the blackscreen.

The bug would be then, that even the pause menu is turned black and you can only hard find the Quit-/Disconnect-Button.

**Comment by Azanor** [comment]
Your computers probably doesn't like the shaders I use. You can turn them off in the TC config.

**Comment by ThexXTURBOXx** [comment]
Okay, I will try that. Thanks!
