### ISSUE TITLE
Verdant Heart Band not eligible for Runic Shielding infusions

### ISSUE THREAD

**Issue by codewarrior0** [Azanor/thaumcraft-5#535]
Thaumcraft-1.8.9-5.2.1

Verdant Heart Band (Lifegiver) in central pedestal, diamond and salis on two other pedestals. Right-click matrix with wand, nothing happens.

**Comment by Azanor** [comment]
Not a bug - it is not supposed to accept runic enchantments atm.

**Comment by codewarrior0** [comment]
If that's the case, a note in the research page would be appropriate.
