### ISSUE TITLE
Aggression Module not built-in for Claw golems

### ISSUE THREAD

**Issue by codewarrior0** [Azanor/thaumcraft-5#537]
Thaumcraft-1.8.9-5.2.1

Crafting a golem with Claw Arms requires an Aggression Module as a component. A golem with Dart Launcher Arms does not require the module. The tooltips for both arm options say "Comes with a built-in aggression module". It seems like the module should be a component for both arm types, or for neither.

**Comment by Azanor** [comment]
Good point

**Comment by LegendWayfarer** [comment]
I'm sorry, but I would like to play with minecraft thaumcraft 4.2.3.5. Is there not to have such a version, or maybe you send me the source code, so that I can implement this myself? 

It would be greatly appreciated!
