### ISSUE TITLE
Fire arrows don't deal pure fire damage

### ISSUE THREAD

**Issue by Hyxaru** [Azanor/thaumcraft-5#539]
You can hurt nether mobs with it, for instance.

**Comment by Azanor** [comment]
Huh? Isn't hurting other mobs the point?

They aren't supposed to deal pure fire damage anyway. They do normal arrow damage and set whatever they hit on fire.

**Comment by Hyxaru** [comment]
Well the thaumonomican says pure fire damage, making me believe the damage is coded as fire. It would make sense because what else does a fire arrow have to offer when there is flame on a bow? Atleast it could be used vs armor that had projectile protection. but not fire protection.
