### ISSUE TITLE
completion percentage and new pages

### ISSUE THREAD

**Issue by kashigolean** [Azanor/thaumcraft-5#54]
When i scanned a pure node, i got a new page in the aura's and nodes book in the Basic Information tab,  even though it already had 100%. After that i scanned a tainted node and got a new page as well, still with 100%.

If missing pages aren't supposed to count in the pages, then i would like to submit this as a suggestion for whenever.

**Comment by Azanor** [comment]
The percentage only counts actual research topics, not unlocks like the extra pages.
