### ISSUE TITLE
[5.2.2] Arcane Pattern Crafter dosen't work right

### ISSUE THREAD

**Issue by marcoasfonseca** [Azanor/thaumcraft-5#543]
I was testing the new device "Arcane Pattern Crafter" and the récipes are all switched. I set it to 2 horizontal spaces (https://www.dropbox.com/s/3bcmb8nq5dx23pa/2016-03-15_16.45.34.png?dl=0) and instead a pressure plate it craft a wooden trapdoor. It happens in every recipe: instead a crafting table it craft a Chest; instead 9 iron nuggets it craft an iron plate; etc...

**Comment by marcoasfonseca** [comment]
Apparently, restarting the game fix that problem :) sorry for bore you

**Comment by Azanor** [comment]
The client pattern displayed probably desynced from the pattern on the server. Let me know if it happens again.
