### ISSUE TITLE
5.2.2  Carry golems still stuck holding ghost items

### ISSUE THREAD

**Issue by jrpoints** [Azanor/thaumcraft-5#545]
Whatever you did to fix this bug did not help, carry golems will still hold onto a ghost item causing them to only be able to carry one item stack at a time.

![2016-03-15_19 40 38](https://cloud.githubusercontent.com/assets/5988499/13800366/e158cf98-eae5-11e5-880d-eea9bdb28dbf.png)

Also in this picture is another bug I have been having, my harvest golems just seem to slow down and sometimes just stop harvesting after a minute or two, not just the sugarcane but all crops. If I relog or unload/re-load the chunks they kick into overdrive and harvest very quickly for a bit then slow down again. I can make another issue for this bug if you would like.

**Comment by Azanor** [comment]
How big a harvest area do you have defined?

The ghost item problem is a tough one. I have never been able to replicate it so I can't  track down exactly what is causing it. I will keep digging.

**Comment by Azanor** [comment]
Finally managed to duplicate the issue and it was never with the golems themselves, but with the pickup seal - it would occasionally leave null-sized itemstacks lying around that.

**Comment by jrpoints** [comment]
Good to hear you were finally able duplicated it.

As far as that second issue, it doesn't matter the farm size or how many golems, I even made a quick video showing it, first part of the video is after a few minutes of the lamp running, the golem is still doing his job but is very inefficient at it, not replanting and not harvesting crops for awhile and making lots of trips to the chest. After the restart you can see he starts to work much better harvesting and replanting much quicker and spending less time making trips to the chest. But after awhile he will slow down again.

https://vid.me/e/nd9Q

**Comment by Azanor** [comment]
I've managed to duplicate that as well and I'm now busy trying to figure out what is causing it. It seems certain harvest tasks are getting stuck.
