### ISSUE TITLE
Golems with Harvest Core don't replant seeds

### ISSUE THREAD

**Issue by solarregis** [Azanor/thaumcraft-5#547]
Thaumcraft version: 5.2.3

Thought this was an issue with some mod related plants, but they won't even replant Wheat. Golems harvest the crops perfectly fine, but having to manually replant kinda defeats the point of having them.

Golem is Void Plated with the Uniwheel, Biothaumic Mind, and Precision Arms (basically, it has the Deft and Smart traits required by the core)

No information regarding this in the Thaumonomicon, so assuming it's a bug.

**Comment by Xiaminou** [comment]
I have the same issue, and they no longer cut down trees.

**Comment by jrpoints** [comment]
Having the tree issue also. When first placed down it will go and start to chop the tree down then a ? over its head before resetting back to home and not doing anything else.

**Comment by Azanor** [comment]
The lumberjack seal is indeed bugged and I will take a look at that, but the harvest seals seems to be working fine for me. Its replanting and harvesting quite happily. Could you maybe post screenshots of your setup and seal settings?

**Comment by Azanor** [comment]
Lol, turns out both the lumberjack and breaker seals were actually broken all along, but they worked because of the bug I fixed with tasks in 5.2.3. With that bug fixed their brokenness is finally revealed. Luckily not that hard to fix them.

**Comment by Xiaminou** [comment]
Well, unfortunately I dismantled my farm in favor of Ender IO's farm. But it's the one I've been using since I installed thaumcraft, so I would assume, unless the seals somehow got reset, that it would work.
