### ISSUE TITLE
Golems with Harvest Core don't replant seeds (5.2.4)

### ISSUE THREAD

**Issue by solarregis** [Azanor/thaumcraft-5#549]
Thaumcraft version: 5.2.4

Golems using the Harvest Seal still won't replant crops (carrots seen in the screenshot were replanted manually)

![2016-03-17_12 08 54](https://cloud.githubusercontent.com/assets/11564009/13845911/2210f730-ec3b-11e5-9afa-72691337102e.png)
![2016-03-17_12 08 59](https://cloud.githubusercontent.com/assets/11564009/13845910/221100a4-ec3b-11e5-8c5e-bf8ef1651712.png)

This one is simply to show that the seal covers the farm properly:
![2016-03-17_12 09 32](https://cloud.githubusercontent.com/assets/11564009/13845912/2210f3e8-ec3b-11e5-8fc3-a49347fd57f7.png)

**Comment by Azanor** [comment]
Are they not replanting at all or just doing it slowly? I see you have a huge area defined so the seal will take a long time to process that.

**Comment by solarregis** [comment]
I'll do a longer test later and let you know

**Comment by solarregis** [comment]
Did a longer test and the golem didn't replant anything. I even moved the seal within range of an inventory that the golem could've obtained the seeds from just in case, and no joy

This was after about five minutes of waiting for him to replant, during which time he harvested other plants from a close proximity (same settings were used):
![2016-03-17_15 17 52](https://cloud.githubusercontent.com/assets/11564009/13853991/38829ce6-ec61-11e5-8836-ba815de806be.png)

**Comment by codewarrior0** [comment]
This might sound dumb, but I don't see a Gather seal nearby. He won't replant seeds unless a Gather seal or Provide seal puts the seeds in his hands.

**Comment by Azanor** [comment]
Yes, they only replant if they actually are carrying something that they can use to replant - unless you use a provide seal or a gather seal it wont happen. Also if you _do_ have a gather or provide seal, but also have a store seal with a much higher priority than the harvest seal then they will obviously put away the seeds first and thus have nothing to replant.

**Comment by solarregis** [comment]
Can confirm that this was the issue. Assumed it was a bug because this wasn't mentioned in the Thaumonomicon entry for the Harvest Seal
