### ISSUE TITLE
Thaumcraft 4.2.3.5 and 1.8

### ISSUE THREAD

**Issue by LegendWayfarer** [Azanor/thaumcraft-5#557]
#I'm sorry, but I would like to play minecraft 1.8 with thaumcraft 4.2.3.5. Is you not to have such a version, or maybe you send me the source code, so that I can implement this myself? I would be greatly appreciated!

**Comment by NarigudoBR** [comment]
nope.many mods that exist in 1.7.10 will not be updated, because updating from 1.7 to 1.8 is hard as "feather" .So many people decided to do a rewrite of the mods which by the way is way more cool because you have new features :P . yeah if you want it, you will have to rewrite it

**Comment by MalkContent** [comment]
the source is "open" as in visible already, nothing stopping you from doing a private port.

**Comment by jochuan** [comment]
i don't think that this is a issue
