### ISSUE TITLE
Problem with crafting recipes learned from shared discoveries (property setting for multiple discoveries)

### ISSUE THREAD

**Issue by Filipmathias** [Azanor/thaumcraft-5#56]
Using the property setting for creating multiple discoveries seems to cause a problem with crafting these objects(for the person not doing the research). The discovery shows in the book, but the recipe wont work ,we tried with the crucible and the arcane work table, this could be true for other crafting
appreciate the work being done on the mod;)

**Comment by Azanor** [comment]
Which recipe in particular? The recipes requiring multiple researches often requires something to have been scanned as well. This means that while the person might have the required research, they have not scanned whatever is required to actually make the item craftable.

**Comment by Filipmathias** [comment]
ah sorry about that.

the two recipes we tried were pretty earlygame stuff, the goggles and the new brass.

i spoke to him later on,  and he said that he actually discovered the brass himself, and he might just have done that one wrong xD.

but the goggles were definatly weird, i went to see if he just were doing it wrong, but i double checked the recipe and everything looked right (i could not craft it either)..  we broke the table and he tried again still no result, then i tried and it worked.

the way i "fixed" it was by giving him my .thaum save file.

**Comment by Azanor** [comment]
Goggles don't actually require multiple types of research. It could be that you did not have the wand in the table or the wand had insufficient vis

**Comment by Filipmathias** [comment]
well we tried with both mine and his wand i have a brass capped silverwood wand which should be filled vis. the blinking aspects that usually show up around the grid did not show up for him or me before i completely redid the recipe, it have been a while now so not sure if im remembering correctly though

any way its not a problem for us anymore, and if nobody else seem to have the same problem, you might as well work at other stuff, i wish we had tested it more before "fixing" it...

thanks for your hard work, appreciate it:)

**Comment by Azanor** [comment]
Cool. I'll keep the issue open in case anyone else has similar issues.
