### ISSUE TITLE
Problem with ichor

### ISSUE THREAD

**Issue by RevengeLP** [Azanor/thaumcraft-5#568]
Hello!
I got an interesting bug...
I used a commend to set my warp to 1 after i did nearly all research..

But i forgot some ichor researches.
1.They blacked out and i cant get em anymore cause i was out of warp.
2.I get some warp back and was bale to research more BUT 
after 2 days now the researches disappeard i cant get it anymore complete gone....

**Comment by Hyxaru** [comment]
Thaumic tinkerer 1.7.10 version issue, this is the wrong github.
