### ISSUE TITLE
Starry void cannot be removed in creative mode.

### ISSUE THREAD

**Issue by chrisbecke** [Azanor/thaumcraft-5#569]
While building a spawn area in creative mode, we placed some "Starry Void" blocks, and quickly realized our mistake. However, they cannot be targeted by Creative Mode players and blocks cannot be placed in the same place as them so they effective cannot be removed without the use of /fill

**Comment by Hyxaru** [comment]
Place water in the block the starry void was/essentialy still is.

**Comment by Azanor** [comment]
That is because they turn into vacuum blocks if exposed to air. This is not a bug - I should really just removed them from the creative menu.
