### ISSUE TITLE
Font size is too small for Unicode

### ISSUE THREAD

**Issue by oldjunyi** [Azanor/thaumcraft-5#57]
Hello Azanor, I'm here to report the long-standing font issue, which still exists in Thaumcraft 5:
![](http://i.imgur.com/9ovsY5n.png)
If a player is playing the Minecraft in Unicode Font mode, with screen size less than 960 pixels in height (for example, screen resolution = 1600 x 900), all text with small font size in TC will be illegible (as shown above).

It will bring bad game experience to international users (We need Unicode Font!), so, could you please fix it? I suggest all text should has the OpenGL scale ratio no less than 1.0

**Comment by handicraftsman** [comment]
+1 (i am russian)

**Comment by Mexahoid** [comment]
I think it's not the TC's problem but Minecraft's.
