### ISSUE TITLE
Bug/Problems with 5.2.4

### ISSUE THREAD

**Issue by Ssssusrgf** [Azanor/thaumcraft-5#574]
Hey, I hope this is correctly placed here as i cant find anywhere else to ask:
 I recently installed Thaumcraft 5.2.4 on Minecraft 1.8.9, but it seems I can't scan anything with the Thaumometer. 
 All it says is that "Nothing can be learned from this", but i instantly get "practical knowledge" of all aspects the item/block normally has.
 So i get the page in my Thaumonomicon with the "recipe" of the aspect, but i can't gain any research points in any way.
 Was the system of researching changed? Because as I read the Thaumonomicon, it's all like it used to be back on Minecraft 1.7.10 (Thaumcraft 3 i think).
 Also, Steve doesn't look THROUGH the taumonomicon anymore but just holds it on his side like any item. Is this normal?

**Comment by Oldskoolninja** [comment]
This is normal. The way research is conducted hasn't changed, but each research note has it's own set number of primals for you to use. Scanning with the Thaumometer is used to unlock research and information though.
