### ISSUE TITLE
Harvest Seal Requesting Provisioning not Working

### ISSUE THREAD

**Issue by MasterJediDigger** [Azanor/thaumcraft-5#576]
When I upgraded from TC 5.2.1 to TC 5.2.4, all of my golems would stopped performing their tasks. My sorting golem would not take items out of the input chest, my tree planter golem failed to see the "use" seals, and collect seals did not work at all. I fixed this problem mostly by removing and replacing seals, but my "provide" seal will not supply my farmer golem with adequate seeds to replant the crops. When the golem has seeds in his hand after he harvested a stalk of wheat, he will replant just fine. However, when he runs out of seeds he is not able to take items out of a chest marked with a "provide" seal to replant. I have my "harvest" seal to request provisioning.

**Comment by ThePB** [comment]
From the words of Azanor, from the thread in the Minecrafforum.net site:

"Warning:

The 5.2.2 patch brings some improvements to seals, but also a change in how the whitelist and blacklist works. An empty whitelist now means that you are not allowing any items through (which is the logical way for it to work).

By default seals will be set with an empty blacklist which allows anything, but existing seals in the world will not be changed. You just need to go twiddle their bits to get them to behave."

Prehaps it's just a problem with settings of filters?

(btw Azanor it would be possible to add this warning to the changelog in the thread and in the changelog file inside the Thaumcraft download? Thanks)

**Comment by MasterJediDigger** [comment]
Wow! Thank you so much, sir. That fixed everything! :D I really appreciate the help.
