### ISSUE TITLE
[Suggestion] Disabling Plate recipes when IC2 exists

### ISSUE THREAD

**Issue by MastaC729** [Azanor/thaumcraft-5#577]
I think it would be nice to be able to disable Thaumcraft's plate recipes, either through a config option or detection of IC2 or other mods that create plates for machinery. Obviously plates would be enabled by default, but modpack users could easily disable the recipes so that players can't short circuit the process of making plates in mods like IC2 where it involves the hammer, the metal former, or the Smeltery.

If you think this should be more of a job for Minetweaker, let me know. Other than that, I like the bronze plate requirements for alchemical devices; it's made it much harder to get that setup.

**Comment by Azanor** [comment]
https://github.com/Azanor/thaumcraft-suggestions/

**Comment by MastaC729** [comment]
Ah crap, thanks for the link.
