### ISSUE TITLE
Golems seeing outside seal radius

### ISSUE THREAD

**Issue by Narook** [Azanor/thaumcraft-5#578]
I tend to use vertical farms to save one space. I setup the first layer the other day and the golem behaved normally, harvesting and collecting. I setup the second layer yesterday and that is when things went downhill. An hour or so later I noticed the bottom golem was no longer harvesting. No big deal, I picked him up and put him back down and he was happy again. Then I noticed the top one had stopped working. Did the same and it was good again. Of course that broke the bottom one again. I picked up and replaced all the seals and both golems, but still no luck. This time I watched them for a bit. The top one was looking down and travelling to where crops needed harvesting on the bottom farm. So I placed him back down knowing it would break the bottom one. Sure enough the bottom one was doing the same, he was looking up and moving to where plants needed harvesting on the top farm. So whenever the second one is placed the first one is now looking outside the radius of its seals and looking inside the radius of the other seals. Is this something that can be fixed or will I have to scrap the vertical farms and stick to horizontal?

**Comment by Azanor** [comment]
Could you maybe post screenshots of your setup with the seal areas visible if possible?

**Comment by Narook** [comment]
Here you go. 2 screenshots. The [first](http://www.shadowdragonsonline.com/narook/minecraft/2016-04-08_16.43.14.png) is of the outside so you can see the layout I am working with. The [second](http://www.shadowdragonsonline.com/narook/minecraft/2016-04-08_16.55.08.png) shows the seals and the area. They are currently set one higher because I was hoping that would fix the issue I was having. The extra seals and radius you see are from the level above. In total there are 2 store seals on each side (just to save some time running back and forth), 1 harvest seal in the middle and 1 collect seal in the middle but one block below the harvest per level. I had all the seals in place when I first made the building. It all worked fine until that second golem was placed down.

**Comment by Azanor** [comment]
Both seals are uncoloured. Golems listen for tasks given by all seals unless they and the seals are colored. Any golems placed would be in range of both taks from both those seals.

**Comment by Narook** [comment]
I figured the Y levels not touching would make them unviable options for the golems. But I get what you are saying. I will go ahead and try colouring them when I get on later. My apologizes for wasting your time on the matter.

**Comment by Azanor** [comment]
No problem :)
