### ISSUE TITLE
Dislocation focus can be used to dupe chests and their contents

### ISSUE THREAD

**Issue by Kadleck** [Azanor/thaumcraft-5#579]
Player uses a pool of flowing water and a nether portal.
A chest containing items to be duped is picked up by the dislocation wand.
The player then stands in the pool of water, which forces him into the nether portal. The player flies out of the portal before it takes effect.
The wand can now place multiple chests, with the same contents.
To repeat this, you just need a wand with at least 2 focii (including dislocation) and a portal/water setup like the one pictured. 

![2016-04-08_19 17 49](https://cloud.githubusercontent.com/assets/18244579/14393538/64ca05b8-fdbf-11e5-9fc3-48e086081517.png)
![2016-04-08_19 17 38](https://cloud.githubusercontent.com/assets/18244579/14393537/64c81348-fdbf-11e5-9349-957a99079faa.png)

**Comment by Hyxaru** [comment]
Close this issue as the dislocation focus is from a thaumcraft addon and not thaumcraft itself. Therefor this is not the right github for this issue.

**Comment by Hyxaru** [comment]
The right github is the one for thaumic tinkerer, if you weren't aware. Though this version is 1.7.10 and no longer supported. You might be able to get the bug recognized, but most likely no effort will be made to fix it in a version no longer used. Besides it is not something that crashes.
