### ISSUE TITLE
Golem creating 'clicking' sound that counts as hostile creature sound

### ISSUE THREAD

**Issue by seegge** [Azanor/thaumcraft-5#585]
My golem (doing harvest+pick up+deposit to chest) generates clicking sound while working, it's about once/10 secs. This sound is really annoying because I have all game sounds muted except hostile creatures.
In game options menu this sound seems to go 'hostile creatures' category (=follows the volume setting).

I'm suggesting that golem sounds would count as something else than 'hostiles' so they can be disabled easily.

I'm not sure what is actually causing the sound effect, the golem or the seals. It seems to appear randomly while golem is messing on the field and if I take golem away then sound stops.

TC 5.2.4, forge 11.15.1.1738, no other mods.

**Comment by Azanor** [comment]
Nothing I can do about this except remove the sound completely. This is the golem's default "ambient" sound and since they are non-animal/passive entities they will count as hostile creatures.
