### ISSUE TITLE
Thaumostatic Harness Issue

### ISSUE THREAD

**Issue by Crysis27** [Azanor/thaumcraft-5#586]
When I crafted my first Thaumostatic Harness in the last version, whenever I put it on my chest armor or had on the hand, it shows the image that I will attach. I can't get vis from ambient, neither where my house is, or in a place that I have not explored yet. I used the "Vis cleaner" from the Creative inventory and still doesn't work. The photo shows a bar under the Thaumostatic Harness icon, that flash in blue and black.
![2016-04-18_00 38 31](https://cloud.githubusercontent.com/assets/18520032/14590891/e961c5a0-04fd-11e6-975b-c8bba10e1e02.png)

**Comment by Azanor** [comment]
Its been changed in the latest version. You need to recharge it in a recharge pedestal or wear a vis amulet.

**Comment by Crysis27** [comment]
Many thanks, Azanor! I love your mod so much! ^^
