### ISSUE TITLE
Eldritch stone infusion altar not forming

### ISSUE THREAD

**Issue by kajatrijsburg** [Azanor/thaumcraft-5#590]
The eldritch version of the infusion altar appears in the Thaumonomicon but doesn't form when clicked with a wand. 
![2016-04-20_22 28 00](https://cloud.githubusercontent.com/assets/10869942/14689348/32a9f84a-0747-11e6-9e20-c55a74544ef0.png)

**Comment by OJwithC** [comment]
Not sure if this applies to Thaumcraft 5, but in 4, those candles between the columns would stop an altar from forming. Try breaking those first, then putting them back if the altar forms?

**Comment by Hyxaru** [comment]
Yeah that is the case.

**Comment by kajatrijsburg** [comment]
Thanks, I would've never figured that out on my own.
