### ISSUE TITLE
[5.2.4] Lag and crashes while staying on birch forest.

### ISSUE THREAD

**Issue by JDBS** [Azanor/thaumcraft-5#591]
While staying in birch forest some memory leak increases ticks delay until crashing.

**Comment by Azanor** [comment]
Why is this TC related?

**Comment by JDBS** [comment]
I think it could be thaumcraft, I'm using a server with thaumcraft 5.2.4 and forge-1.8.9-11.15.1.1855. but im gonna test without thaumcraft and forge too.

**Comment by jochuan** [comment]
this should be closed then
