### ISSUE TITLE
Some mods cause Thaumcraft graphics to be incorrectly loaded

### ISSUE THREAD

**Issue by charlesbevans** [Azanor/thaumcraft-5#595]
Playing the most recent FTB Unstable pack (SSP, Unstable 3.0.42, TC 5.2.4)
Some mods, including [Actually Adittions](http://minecraft.curseforge.com/projects/actually-additions) and [Quantum Flux](http://minecraft.curseforge.com/projects/quantumflux) cause some TC5 graphics to be replaced with fragments of other things or multicolored static. Screenshots below. I have already notified one of the mod authors and am notifying the other next in the hopes it will make the problem easier to identify.
So far, I've only seen one non-TC5 item affected, it was one of the two items from Thaumic Infusion. I'll notify that mod author as well.
![2016-04-25_08 09 43](https://cloud.githubusercontent.com/assets/15851438/14799045/7828498e-0aef-11e6-912a-4194fcf9d755.png)
![2016-04-25_08 11 59](https://cloud.githubusercontent.com/assets/15851438/14799046/7c0a656e-0aef-11e6-943d-0295f3265e43.png)
![2016-04-25_13 48 27](https://cloud.githubusercontent.com/assets/15851438/14799049/80413162-0aef-11e6-9c64-1f686fa87b19.png)
![2016-04-25_14 01 22](https://cloud.githubusercontent.com/assets/15851438/14799057/8e7b2d14-0aef-11e6-966f-6364a7684c32.png)

**Comment by Azanor** [comment]
Thanks, but since this does not seem to be a TC issue, but a modpack one so I'm closing this.
