### ISSUE TITLE
Escape closes Thaumonomicon when in entry

### ISSUE THREAD

**Issue by qwertyasdef** [Azanor/thaumcraft-5#598]
When I press escape when reading an entry in the thaumonomicon, it closes the book instead of returning to the main view. Minor issue, but is pretty annoying. I have some other mods installed, which I can list if necessary.

Minecraft version 1.8.9
Forge version 11.15.1.1855
Thaumcraft version 5.4.2

**Comment by Tuhljin** [comment]
FYI: I'm not sure whether Escape closing the entire GUI is intended or not, but in any case, you can use "E" to close just the entry you're looking at and return to the main Thaumonomicon GUI.

**Comment by Azanor** [comment]
It is intended - way back when it was actually requested as it used to just take you back to the browser gui, but people asked for a way to get out completely.
