### ISSUE TITLE
[1.8.9] Breaking Cauldrons with Wand Focus: Excavation transforms them into Crucibles

### ISSUE THREAD

**Issue by Xiaminou** [Azanor/thaumcraft-5#602]
So here I was breaking up my Immersive Engineering's fermenter with my Wand Focus: Excavation and it turned the Cauldrons into Crucibles. It only does so when you're in range of normal right-click, but I still think it should be changed if possible.

**Comment by MyNameIsKodos** [comment]
Not sure I'd consider this a bug, since that's a working as intended feature. Maybe just don't stand within click range of the cauldron? Or sneak while using the Excavation focus

**Comment by Xiaminou** [comment]
I never called it a bug

**Comment by MyNameIsKodos** [comment]
No, you did not, but this issue tracker is for bug reports. Which is why I said that.
