### ISSUE TITLE
Casting conflict between Thaumcraft node on Botania flower

### ISSUE THREAD

**Issue by 5aturat3dmark** [Azanor/thaumcraft-5#605]
TC: 4.2.3.5  Forge: 10.13.2.1277
So long story short, my world save was corrupted after a power surge and after spending time fixing the other bugs, I concluded that this one was far outside my realm of expertise to handle and would like to request your input. I apologize in advance if this is the wrong forum to report to or if this is Botania's issue and not yours; also if this is client-side only and I just have to accept it as is.

I may not be good at coding but the basic crash reports kept returning a casting conflict between Thaumcraft nodes on Botania flowers in general. I thought it to be a specific node and flower somewhere in the world that i could resolve with MCedit like the rest of the bugs but the report did not post the coordinates like the other bugged areas had, so i assumed that was not the case anymore.

I'm using the CrackPack from ATLauncher. Fastcraft is also in the mod pack if that means anything.
  (I replicated the exact crash with and without Fastcraft present in the mods folder.)

Also to note is that this issue only happens on a specific world save after that power surge happened so I'm certain that it might be just the corrupted world itself and not the mod, but I want to make sure before I have to accept my loss.

Crash Report: http://pastebin.com/nPb8Lj56

FML Log: https://gist.github.com/5aturat3dmark/c3eb7aa5423318b0d50a04678ca4939c

**Comment by Azanor** [comment]
The actual error occurs on the botania side, but the cause is almost certainly world corruption - a TC tile entity is somehow located in a botania flower from the looks of it. I don't think there is much to be done beyond deleting that flower from you save.
