### ISSUE TITLE
CPW's inventory sorter, compatability, duplication bug with baubles inventory.

### ISSUE THREAD

**Issue by milla-sedai** [Azanor/thaumcraft-5#608]
cross posting this bug for you

> Since baubles is part of TC I'll just add that sorting when you have the baubles window open duplicates all your armor and baubles
> Still happens with forge 1902, and the following mods, bolded TC/Baubles, and Inventory Sorter versions (latest)
> 
> Baubles-1.8.9-1.1.3.0.jar"
> 
> Botania-unofficial.r1.8-299.jar"
> Chameleon-1.8.9-1.1.2.jar"
> CompassCoords-1.8.9-0.2.6.jar"
> FastLeafDecay-1.8-1.6.jar"
> hopperducts-mc1.8.8-1.4.6.jar"
> ironchest-1.8.9-6.0.125.770.jar"
> inventorysorter-1.8.9-0.7.7+27.jar"
> jei_1.8.9-2.28.18.186.jar"
> JEIAddons_1.8.9-0.12.0.57.jar"
> journeymap-1.8.9-5.2.0-unlimited.jar"
> JustEnoughResources-1.8.9-0.4.0.23.jar"
> LLOverlayReloaded-1.0.7-mc1.8.9.jar"
> StorageDrawers-1.8.9-2.6.4.jar"
> Thaumcraft-1.8.9-5.2.4.jar"
> Waila-1.6.0-B3_1.8.8.jar"
> 
> Out of curiosity is 1.8.9 considered deprecated or obsolete in the modding circle? Should I just move on?

inventory tweaks gets around this by dissallowing sorting outside of the player inventory and in the baubles inventory

**Comment by Azanor** [comment]
This would be a bug with the inventory sorter and it is highly unlikely to be something on the Baubles side.

**Comment by Azanor** [comment]
Also this the Thaumcraft issue tracker, not the Baubles ones.
