### ISSUE TITLE
[1.7.10] Crash when holding shift and mousing over certain items

### ISSUE THREAD

**Issue by Thedrummonger** [Azanor/thaumcraft-5#637]
I get this weird crash when holding shift and mousing over the charm of dislocation from Draconic Evolution. I would normally assume that this is a Draconic Evolution crash but the crash report is nothing but Thaumcraft. I've researched this issue a ton and have noticed people have this same type of crash on world load with witching gadgets and disabling a config option fixes it. I do have witching gadgets but the config option is disabled and my crash does not happen at world load. The weirdest part is this crash is fairly new. I'm playing a custom pack and have not updated/added any mods in quite a while. I know for a fact I could previously shift over the charm of dislocation with no crash. I have no idea what could have changed to cause this problem.

Crash Report: http://pastebin.com/aw0cNxBy

edit: I should also note that I do have Optifine but I have replicated this crash without it.

**Comment by Azanor** [comment]
That is a classical circular recipe problem. I'm guessing there is a recipe for that charm that has itself as a ingredient. Normally I catch that sort of thing, but occasionally there is something strange or unusual in the way an item is defined that manages to break my safety checks.
I'm not updating this branch of TC anymore, but that code is getting a revision in TC 6.
