### ISSUE TITLE
[1.7.10] [4.2.3.5.] ItemPhysic mod causes items to spin on pedestals

### ISSUE THREAD

**Issue by Bushcrafts** [Azanor/thaumcraft-5#639]
Placing items on the pedestals causes them to spin violently. They also are not placed upright, they just lay down flat and just spin, spin, spin.

It looks like this was mentioned on ItemPhysic's github and acknowledged last year. Are there any updates to this? 

ItemPhysic link:
https://github.com/CreativeMD/ItemPhysic/issues/9

Thanks!

**Comment by Azanor** [comment]
This is not something that needs to be fixed on my side.
