### ISSUE TITLE
Error Creating Larger Maps

### ISSUE THREAD

**Issue by ProphetOfWhy** [Azanor/thaumcraft-5#640]
When creating a larger map using the Map (explored) + 8 Paper, it creates a map that has a "0" count on it, as if it is in a stack of 0. When this new map is used, it disappears. I do not know if this is an issue with this mod, but I am attempting to find out what is causing it.

Minecraft Version 1.8.9

Mods:
Minecraft Coder Pack 9.19 (I don't know where this came from)
Forge Mod Loader 8.0.99.99 (required for Forge)
Minecraft Forge 11.15.1.1902 (required for Thaumcraft)
Mantle 0.9.2 (required for Forge)
Tinker's Construct 1.8.9-2.2.1 (installed, but problem persists when this is disabled)
Baubles 1.1.3.0 (required for Thaumcraft)
Thaumcraft 5.2.4

**Comment by Azanor** [comment]
Definitely not TC related.
