### ISSUE TITLE
Autocasters attack other autocasters

### ISSUE THREAD

**Issue by nnystyxx** [Azanor/thaumcraft-5#65]
Autocasters, when tuned only to attack "Mobs", will attack other (player-placed!) autocasters, usually preferentially over anything else. Is this a consequence of the entity design? Can they be altered not to do so?

**Comment by Azanor** [comment]
Placed by different players I assume?

**Comment by nnystyxx** [comment]
Placed by the same player. I'm testing it again on 5.0.2 just to be absolutely sure.

**Comment by Azanor** [comment]
I cant duplicate this. I placed several autocasters near each other with absolutely no issues. Occasionally one might hit another with a stray shot, but they never actively attacked anything other than their target.
Is this in SP or on a server?

**Comment by nnystyxx** [comment]
SP. I placed two Autocasters on a wall-- the left had no focus, the right had an unaltered Shock focus. Several times in a row the right Autocaster attacked the left specifically, then started attacking -me- (in creative and in survival) despite being 'programmed' only to attack mobs.

**Comment by Azanor** [comment]
Would it attack till you move out of range while looking at you, or would it just occasionally shoot and then stop?

**Comment by nnystyxx** [comment]
It would attack me until out of range. Preferentially, unless a mob was closer.
