### ISSUE TITLE
mysterious bungee bug

### ISSUE THREAD

**Issue by yuankun1** [Azanor/thaumcraft-5#655]
1 the cryptic 4 and straddle bug jumps to the faucet end of the service to the mod mod end core direct failure

**Comment by XombyCraft** [comment]
2 resolute, primarily start the pipe withholding peaches.  furthermore, focus the outlet port of oscillation overthruster to the inlet port of flux capacitor.  finally ceasing straddling bug jumps.

**Comment by yuankun1** [comment]
It is the mysterious mod step into the faucet end in the mod terminal mysterious core failure solution

**Comment by XombyCraft** [comment]
regards and removes flannel shirts.  initiates mysterious core success. peaches!

**Comment by yuankun1** [comment]
Do you want me to delete the mystery? I like the mystery. Can you fix this bug? It's a 1.7.10 version of the mystery 4 request to help fix it

**Comment by XombyCraft** [comment]
I like the mystery too.  any logs?

**Comment by yuankun1** [comment]
no

**Comment by XombyCraft** [comment]
then how "core failure"?  high CPU% usage? RAM 100%? slow HDD?

**Comment by yuankun1** [comment]
There's no logs but he's going to take it to the faucet and then cross over to the mod and the mysterious core is broken and you can test it with a cross-suit

**Comment by yuankun1** [comment]
F key doesn't hold the core

**Comment by XombyCraft** [comment]
F key bound to another mod? or core not visible in wand menu?

**Comment by yuankun1** [comment]
no

**Comment by XombyCraft** [comment]
no yes or no no

**Comment by yuankun1** [comment]
It's the F key that opens the menu and then moves the mouse to the core core and doesn't fit

**Comment by yuankun1** [comment]
I am Chinese I can hit the words you can translate

**Comment by XombyCraft** [comment]
understood.  "CORE" for crafting wand/staff/scepter, and "FOCUS" put in F-key GUI.

**Comment by yuankun1** [comment]
1.7.10端 用跨服 进入登录大厅 水龙头服务端 然后在进入mod服务器然后 神秘mod核心F键打开菜单 然后移动到 火核心 其他核弹 都装不上去 在背包里面
你可以试试用1.7-1.8跨服核心试试 准备一个服务端和mod服务端 自己测试一下

**Comment by yuankun1** [comment]
You can't put it in the Chinese BBS and you're talking about it every day and you ask the author if you can solve the problem

**Comment by XombyCraft** [comment]
I don't speak Chinese.  Maybe pictures help better. -- after translating your comments make no sense

**Comment by yuankun1** [comment]
Over a period of time, I'll send you a picture

**Comment by XombyCraft** [comment]
I wait patiently. hopeful to help.

**Comment by yuankun1** [comment]
Is bungee CRD - 1.8 straddle to spigot in the straddle to cauldron, then f key to open the GUI to move to any core can not be installed, you do your own test to know what reason

**Comment by yuankun1** [comment]
Do you understand? if you don't understand a period of time, I'll send a picture

**Comment by XombyCraft** [comment]
So it works on spigot but NOT on cauldron?  You realize cauldron hasn't been updated since 2015, right?

**Comment by liach** [comment]
@yuankun1 试试thermos

**Comment by XombyCraft** [comment]
http://amzn.to/2uxaChc  ?

**Comment by liach** [comment]
https://github.com/CyberdyneCC/Thermos

**Comment by XombyCraft** [comment]
was a joke.
