### ISSUE TITLE
Not a issues but a ?

### ISSUE THREAD

**Issue by ghost** [Azanor/thaumcraft-5#657]
Will you be updating Thaumcraft to 1.11 or above

**Comment by Hyxaru** [comment]
Development of future versions for Thaumcraft are on hold. This means Thaumcraft is currently not being worked on, and may or may not be updated.
Citing Azanor from the thaumcraft forum:
''Between work and family I have been unable to work on Thaumcraft even a fraction as much as I have been able to in the past. I have recently decided to continue my studies after-hours which means what little time I had left will disappear for the next couple of years. The studies will be mostly to further my career, but the good news is that I am going to sneak in some gaming related courses in there. I am hoping to return to modding eventually, or maybe even publish a game of my own.
I will continue to maintain Baubles – it is small enough that keeping it running doesn’t occupy much time. Thaumcraft is a different beast however. I will try and work on TC 6 whenever I get the chance, but I cannot promise when it will be done or even if it ever will be done. Sorry guys.''

Could you close this issue as this isn't an issue report and your question has been answered?
