### ISSUE TITLE
[Minecraft 1.10.2 TC6 v.6.0.BETA2] "Types of Knowledge" page overlapping buttons & formatting

### ISSUE THREAD

**Issue by VallenFrostweaver** [Azanor/thaumcraft-5#660]
See image below of the knowledge page. 1 of the 3 buttons at the bottom cover the writing and there is a decorative line break overlapping as well. This is the same at any video setting. No, I don't have Optifine installed.
![book](https://user-images.githubusercontent.com/13642054/35345735-46c95e2e-0128-11e8-8532-e10420bb2fd1.png)

**Comment by MainFreak** [comment]
I had a few similar formatting issues (on some pages also a few missing words). I set my UI size to “medium”, in case that is relevant.

**Comment by MainFreak** [comment]
PS: shouldn't this issue be reported [here](https://github.com/Azanor/thaumcraft-beta)?

**Comment by VallenFrostweaver** [comment]
Ah crud. Yes. :3. I'm on mobile now so it'll be a few hours before i can repost there.

**Comment by VallenFrostweaver** [comment]
Closed. Wrong version. The current Thaumcraft "issues" tab directed me to this repository instead of the TC Beta one.
