### ISSUE TITLE
(Concept Idea) Witches's Broom

### ISSUE THREAD

**Issue by SimulatorSia** [Azanor/thaumcraft-5#667]
Late game fast witches's broom that has purple lightning around it as to signify thaumcraft theme but it doesn't go up fast  and maybe even stalls like a plane of you go straight up and it mustn't require any fuel/essentia to keep going.

No magic mods updated past 1.10 carry a witches broom, I mean a witches's broom is one of the core ideas when it comes to magic. Maybe it's really hard to obtain or you have to carry the latest game wand or even craft it with a jar containing the most powerful node you could make. Reason it shouldn't require fuel is because if it does it'll be obsolete/never used compared to any Extra Utilities 2 Wing Rings or Botania's Flügel Tiara.

(Just suggestion is all)

**Comment by MainFreak** [comment]
The repository for 1.10.2 is [here](https://github.com/Azanor/thaumcraft-beta/issues)

**Comment by SimulatorSia** [comment]
Oh my, I didn't know I was on Thaumcraft 5's issue list. Thank you for letting me know.
