### ISSUE TITLE
[Suggestion] About some upgrades of the Essentia output and the Essentia input for TC6 Beta 4

### ISSUE THREAD

**Issue by Lazy-Rabbit-2001** [Azanor/thaumcraft-5#672]
To be honest, this idea had been come up before I finished my Thaumcraft 5.
Now I'd like to show Azanor the idea I said.

==============The Upgrades of Essentia Transfusers==============
You've known how to use the Filling Essentia Transfusers and Emptying Essentia Transfusers. However, you soon found that it would lead you an unstable place: You saw that the flying essentia would sometimes fly into other jars which have the same essentia and it'd flies so slowly. So to solve this problem, you got an idea about upgrade those who are too old to be put into longer use.
Then you researched it and finally got it.
These are "the upgrading cores of thaumic transfusers".
Each core need an blank model:
![blank model](https://user-images.githubusercontent.com/22123964/35732343-026fbe0c-0854-11e8-8d9f-655c3367981e.png)
Now you have to have this blank model infused by crystals, and different crystals of basic aspects have different effects to the core.
[Aer]
The power of Aer can support the tranfusers in higher efficiency to work on essentia emptying and filling.
![aer core](https://user-images.githubusercontent.com/22123964/35732317-ee7c967c-0853-11e8-997e-737ade9ab01f.png)
[Aqua]
The power of Aqua can make the essentia that is been ejected flies faster.
![aqua core](https://user-images.githubusercontent.com/22123964/35732498-83df7c66-0854-11e8-8644-7da83d0e2a9a.png)
[Ignis]
The power of Ignis can sometimes make the essentia be in double amount.
![ignis core](https://user-images.githubusercontent.com/22123964/35732587-e7ad8300-0854-11e8-8f5e-c8e420502ee4.png)
[Terra]
The power of Terra can make the working range of the tranfuser increase.
![terrain core](https://user-images.githubusercontent.com/22123964/35732715-77e4e5c6-0855-11e8-8fe0-69c200a2fac4.png)
[Ordo]
The power of Ordo can make the essentia fly more regular, which means the essentia will firstly flies into the unfull jars, then it'll flies into another one which is not full.
![ordo core](https://user-images.githubusercontent.com/22123964/35732901-3d99bbd4-0856-11e8-9c4c-c03cb85495cb.png)
[Perditio]
The power of Perditio allows the essentia to try hurting the monsters that collides with it.
<The recipe seems to be lost>

**Comment by MainFreak** [comment]
Belongs over [here](https://github.com/Azanor/thaumcraft-beta/issues)
