### ISSUE TITLE
Golem crash with FTB Utilities

### ISSUE THREAD

**Issue by NyanHype** [Azanor/thaumcraft-5#676]
Aparently if you have FTB Utilities and you make the golem right click something it will make a crash, it seems it tries to check if the golem has permission but i'm not an expert at reading these codes

[crash-2018-02-03_21.19.13-server.txt](https://github.com/Azanor/thaumcraft-5/files/1692304/crash-2018-02-03_21.19.13-server.txt)
[crash-2018-02-03_18.24.49-server.txt](https://github.com/Azanor/thaumcraft-5/files/1692305/crash-2018-02-03_18.24.49-server.txt)

I've got two crash reports, it was in a test world fortunately cause the world can't be opened again, i've tried with claimed and unclaimed chunks and both lead up to a crash

**Comment by MainFreak** [comment]
Issues for the beta belong [here](https://github.com/Azanor/thaumcraft-beta/issues)
