### ISSUE TITLE
"Basic Thaumaturgy" research not possible to complete

### ISSUE THREAD

**Issue by CrazyAboutMaths** [Azanor/thaumcraft-5#682]
![unknown](https://user-images.githubusercontent.com/37678694/37806836-021f177a-2e3a-11e8-9ebc-49b34a6e9e84.png)
![unknown 1](https://user-images.githubusercontent.com/37678694/37806837-02389222-2e3a-11e8-8c26-fae59f72c2ee.png)
I was playing foolcraft 2.12 and was going through the progression and got stuck at this reseach that was looking for a fire focus with 4.4 damage but the wand focus that is craftable has 5 making it not possible to continue,
I would greatly appreciate it if you could fix this (sorry if it has already been fixed I couldn't see a report about it). For now I had to use /thaum research @p BASEAUROMANCY

**Comment by MainFreak** [comment]
This is the github for ThaumCraft 5. For ThaumCraft 6, please repost this [here](https://github.com/Azanor/thaumcraft-beta/issues)
