### ISSUE TITLE
Stronghold library chests are empty

### ISSUE THREAD

**Issue by Fjolsvin** [Azanor/thaumcraft-5#69]
Chests in stronghold libraries contains nothing. Easy to verify.

**Comment by MalkContent** [comment]
you got that multiple times?

**Comment by Pika0** [comment]
All the chests in my stronghold were empty.

**Comment by MalkContent** [comment]
that's not true for me. i only had 3 empty chests, all in the library

**Comment by Fjolsvin** [comment]
Confirmed. Forge issue. I presumed it has something to do with TC changes of content of chests.
