### ISSUE TITLE
[TC6] How to prevent Rifts from spawning in a certain dimension?

### ISSUE THREAD

**Issue by ben-mkiv** [Azanor/thaumcraft-5#699]
Hi,

after looking at the thaum api i'm a bit confused about how to prevent rifts from spawning in a dimension like overworld.

so whats the way to go? Actually it looks like i have to catch onJoin event and look if its a rift, and drain all flux from that area to prevent new spawn events.

feedback is appreciated :) thanks

**Comment by MainFreak** [comment]
Sorry that I can't redirect you to the appropriate repositories right now since I am using a phone, but this is for the no longer supported Thaumcraft 5 for 1.8. Please repost this issue on either the Thaumcraft 6 or Thaumcraft API GitHub

**Comment by ben-mkiv** [comment]
ok, thanks. will post it on the API tracker

moved over here => https://github.com/Azanor/thaumcraft-api/issues/39
