### ISSUE TITLE
extreme amount of vis shards 

### ISSUE THREAD

**Issue by Filipmathias** [Azanor/thaumcraft-5#70]
i'm not sure if this is supposed to happen, but i think i'm set for life with order shards

![image](https://cloud.githubusercontent.com/assets/5849075/11015697/ff9db6c8-8567-11e5-9d59-c2eef0c55fef.png)

might be my fault set up the server with extra nodes xD

**Comment by handicraftsman** [comment]
o_O

**Comment by Zsashas** [comment]
Hallelujah it's raining order shards.
