### ISSUE TITLE
Arcane Bore stalls out

### ISSUE THREAD

**Issue by obrseamus** [Azanor/thaumcraft-5#76]
Arcane bore seems to be only digging out the 'edge' of its mining area.  Mining width was 9.  It'll dig all to the full distance taking out all the edge pieces, and the ones in the way, but leave a large cone in the middle.
New blocks placed on the edge will be detected and bug, but this does not trigger the center to be carved out then as well.

**Comment by Azanor** [comment]
Could you post a screenshot of this please? I cant seem to replicate this.

**Comment by Azanor** [comment]
Nevermind, I was able to replicate. It turns out the arcane lamp glimmers was the cause. I guess you were using one?
