### ISSUE TITLE
Apprentices rings aspects messed

### ISSUE THREAD

**Issue by Fjolsvin** [Azanor/thaumcraft-5#82]
Apprentices rings of Aqua, Ignis and Terra have its respective aspects (aqua, ignis, terra) messed. Rings of Aer, Ordo and Perditio are alright.

**Comment by Azanor** [comment]
Everything seems fine to me. What precisely do you mean by messed up?

**Comment by Fjolsvin** [comment]
Apprentices ring of <b>Aqua</b> = 2× Auram, 1× Metalum, 1× <b>Terra</b>
Apprentices ring of <b>Ignis</b> = 2× Auram, 1× Metalum, 1× <b>Aqua</b>
Apprentices ring of <b>Terra</b> = 2× Auram, 1× Metalum, 1× <b>Ignis</b>

Apprentices ring of <b>Aer</b> = 2× Auram, 1× Metalum, 1× <b>Aer</b>
Apprentices ring of <b>Ordo</b> = 2× Auram, 1× Metalum, 1× <b>Ordo</b>
Apprentices ring of <b>Perditio</b> = 2× Auram, 1× Metalum, 1× <b>Perditio</b>

**Comment by Azanor** [comment]
Oh, THOSE aspects. Got it.
