### ISSUE TITLE
Arcane workbench issues when multiple players use it 

### ISSUE THREAD

**Issue by Filipmathias** [Azanor/thaumcraft-5#86]
me and my friend was crafting stuff in the arcane workbench both players looking in the table. crafting got weird, items and wands disappearing at random when trying to create stuff, some items reapeared with a red zero and then disappeared after a while. this was also an issue in 5.0.2. 

love the mod, really looking forward to the new golem system:)

**Comment by Azanor** [comment]
This does seem buggy, but is actually relatively "normal" MC behaviour with containers. 

Was any items duplicated, or was it all just visual?

**Comment by Filipmathias** [comment]
well, no items were dublicated but some items, and often the wand disapeared for good, we  lost 3 wands while i was helping him make some essentia distelation stuff;)
