### ISSUE TITLE
Cinderpearl enhancement spawn

### ISSUE THREAD

**Issue by Zaltora** [Azanor/thaumcraft-5#87]
I had noticed since 1.7.10 world update than cinderpearl are more difficult to get. I don't no if it is was intentional Nerf but with theses additional biome, People are lower chance to found desert. And some little desert doesn't have these beautiful "flowers".
![2015-11-08_12 23 38](https://cloud.githubusercontent.com/assets/5892130/11074859/5674d09e-87f2-11e5-8673-cc699601006a.png)
![2015-11-08_12 40 32](https://cloud.githubusercontent.com/assets/5892130/11074862/5d4f8300-87f2-11e5-90b8-f0c492e81ae1.png)

When they appears, we can found many of them but they are very concentrate into a place. In my world, in a area 2000x2000 block, i estimate the maximum to 80-90 cinderpearl.

I suggest the possibility to them to appears on red sand from mesa biome and if possible to have a config  to do some ajustements.

Edit: Little misstake => i forget negatif area  it is for 4000*4000 block :p

**Comment by Fjolsvin** [comment]
I'm sorry, but I strongly disagree with Zaltora, as his opinion doesn't seem to be objective to me. I just thought Cinderpearls are quite abundant. It seems to be more plentiful than Shimmerleaves and there are more than enough of them to make supplies of blaze powder before a player dares to enter the Nether. I do believe Cinderpearls should be rather rare than common. Don't make Cinderpearls be like cacti.

If so, consider rather ability to spread like mushrooms, while I'd suggest a lesser limit or a bigger area adjustment. And if so, consider the same about Shimmerleaves. Nevertheless I'm for preserving the actual state rather.

**Comment by Azanor** [comment]
They were supposed to actually spawn on red sand, but a bug was preventing that. They should start showing up there, but I agree they should still be as rare as they are now.

**Comment by Zaltora** [comment]
I will explain why i said that. I suggest that settings and that upgrade because, in multiplayers, is not abundant like you can think. ( It is depend )
In my case i imagine just a server with 4k*4k blocks  and 10 players. In this server, you can found a huge desert and some little desert. 
If one or two player found the huge desert first and farm cinderpearl. He can found 30-40 cinderpearl easily ( it is abundant for them ). And for others players, it is became very hard to found these or impossible. small desert have very low chance to have theses flowers, huge desert was farm by 1 or 2 player who coming first and world is huge.

A way to equilibrate the number of cinderpearl loot by player, it is to disperse theses flowers.
With theses conditions:
-little desert have more chance to get these flowers but with lowers numbers (1-2)
-huge desert have less cindepearl by spawn (5-6) => (3-4)  but mesa can spawn cinderpearl too.

It will not increase significantly the numbers of cinderpearl in my 4k*4k world but they will be more dispersed.
More players can get theses and players who search to farm need  work harder.

Something else, you speak about "blaze powder" and i agree but player can use them to get Auram aspect now.

**Comment by Fjolsvin** [comment]
I understand your wailing, nevertheless you can say the same about any non-renewable resource. Using numbers you provided, if there are 80-90 Cinderpearls in your world and you're playing with 9 more players, then if a singe player steals 30-40 Cinderpearls for himself, of course you have a problem to find any. But it really doesn't sound like an adjustment issue to me.

Furthermore, there are other sources of blaze powder or auram than Cinderpearls. You'll have much bigger problem, if your comrades steal all the Shimmerleaves. Or a dragon egg. Dead bushes. Lily pads. Sand.

**Comment by Zaltora** [comment]
Yeah, non-renewable ressources have the same problems, that why it can be cool to adjust the spawn in config file (like eerie biome, nodes, taint,...) and test generation world.
In my example, eerie biome spawn in many distance location ( north , south, east, west ). So i dont worry about players who can found Shimmerleaves and loot what they want. ( i have modified 
slightly the config file )
That can be great to add or remove biome for cinderpearl generation too, especially for those who have additional biome. 
And last , mesa is sooooooo empty space :)

PS : i checked Lily pads too :D, it is ok .
