### ISSUE TITLE
Lesser Crimson portal bug/enhancement ?

### ISSUE THREAD

**Issue by Zaltora** [Azanor/thaumcraft-5#88]
The day, we see portal try to spawn some "crimson" mobs without succes. It is become easy to destroy these portals the day.
The night, it is a true "mini-challenge" to try to destroy them.

It is possible that crimson mobs appears day and night ?  crimson mobs don't burn  :p
or
It is possible that the portal appear only the night ?

**Comment by Azanor** [comment]
They are supposed to spawn whenever you come close, but obviously there might be a bug. I will look into it.
