### ISSUE TITLE
Thaumometer Reacts to Glyphed Stone but unable to Research Anything

### ISSUE THREAD

**Issue by Xirema** [Azanor/thaumcraft-5#89]
![2015-11-10_22 10 44](https://cloud.githubusercontent.com/assets/1447761/11083667/efa73450-87f7-11e5-84da-bef8b7af4fad.png)

The question marks are popping up as though there's something to learn from scanning it, but I learn nothing when I actually do scan it.

**Comment by Azanor** [comment]
Hmmm, I did some testing and everything works like it should for me. They might have been triggering on something else?

**Comment by Xirema** [comment]
It was very clearly just the Glyphed stone. If I point at anything else, I don't get the indicators, and if I mine a Glyphed stone block and toss it to the ground, the indicators light up around the loose block item.

According to my Thaumonomicon, I'm missing a few research items in the Eldritch tab, but I've researched everything up to and including the Primordial Pearl and the Primal Crusher.

**Comment by Xirema** [comment]
![2015-11-11_20 14 55](https://cloud.githubusercontent.com/assets/1447761/11108921/ecb340a4-88b0-11e5-9930-2f95fa7dc2ad.png)

This is what the Eldritch tab looks like at the moment. Only that and the golemancy tabs lack research right now.

**Comment by obrseamus** [comment]
I'm also experiencing this issue.  Screenshot attached to this issue.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292130-thaumcraft-5-0-3-updated-2015-11-9?comment=30990
