### ISSUE TITLE
aspect points on items feedback

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#90]
-cake has metallum again (18!) somethingsomething container items
-pumpkin pie has 1 herba, nothing else (guessing automatically assigned aspects)
-water, lava, milk and liquid death buckets all have vacuus, though that might be intentional (bucket of purifying fluid doesn't have it though)
-enchanted fabric and primordial perls don't have aer
-scribing tools have volatus, which i assume is automatically assigned, but seems a bit off, given it has nothing to do with flight anymore
-trapped chest has no vinculum (guessing automatically assigned aspects)
-jack o' lantern has no lux (g.a.a.a.)
-both damaged anvils are missing aspect points completely

Edit:
-i feel like stained glass should have sensus, akin to hardened clay

**Comment by Azanor** [comment]
Dammit Cake! I've told you so many times to stop eating buckets!

**Comment by MalkContent** [comment]
buckets are the cakes of the cake world :)
short after word:
-filled waterbottles have aqua + vitreus, empty water bottles only have vacuus (gaaa?)
    -that said none of the potions have vitreus
-zombie heads have humanus where the skeleton heads have exanimis, maybe intentional with rotten flesh having humanus and all that
-sugar has desidarium, which i think is intentional, but on the off chance it's not, i put it on this here list

**Comment by Zsashas** [comment]
I thought it was intentional for Empty Bottles to have Vacuos? 
In 1.7.10 Skeleton heads have Mortuus, while Zombie heads have Exanimis.

Wouldn't it make more sense to hard-code at least some vanilla and TC aspects instead of having every block/item determine aspects from recipes?

Would possibly prevent things like books, paper, enchanted books, and Thaumonomicons having massive amounts of Lucrum and Vitreus in CrundeeCraft...

**Comment by MalkContent** [comment]
My problem with bottles is not that they have vacous, but either that they are lacking vitreus or that the filled ones do have vitreus.

Also LOTS of things have hardcoded aspects. Idk what CrundeeCraft does but it's apparently a modpack not just a mod, so meh. If it adds strange recipes, there's gonna be strange aspects ^^
