### ISSUE TITLE
Thaumcraft4 compatibility with Forestry4 woods and planks

### ISSUE THREAD

**Issue by leagris** [Azanor/thaumcraft-5#93]
Dear Sir @Azanor would you please be able to fix Thaumcraft4 compatibility with Forestry 4 woods?

The wand focus of equal trade does not work with Forestry4 planks. See [Issue #342 from BeyondRealityModPack](https://github.com/Beyond-Reality/BeyondRealityModPack/issues/342)

**Comment by Mexahoid** [comment]
I think TC 4 is not supported anymore.

**Comment by Azanor** [comment]
Yup, sorry. I'm not updating TC 4 anymore. Either way that doesn't look like something I would have been able to fix on my side anyway.
