### ISSUE TITLE
Guardians (and probably elder Guardians) lack mob aspects.

### ISSUE THREAD

**Issue by Hyxaru** [Azanor/thaumcraft-5#97]
I know its a minor thing but I am looking forward to make a guardian farm with liquid death.
I would suggest aqua, tenebrae and perhaps bestia.

**Comment by MalkContent** [comment]
piggybacking on this: endermites are lacking aspects, too
and the crimsons don't drop Crystalized Essence when liquid deathed, for some reason :/
